In [1]:
import glob
import pandas as pd
from collections import defaultdict
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from numpy.testing.print_coercion_tables import print_new_cast_table
from scipy.stats import gmean
import scipy.stats as stats
import re
import os

from functools import reduce
from matplotlib.colors import to_rgb, to_hex
import colorsys

from mpl_toolkits.axes_grid1.inset_locator import inset_axes, mark_inset

In [2]:
fname= "./dynamic_results_eager.txt"
dfdyn = pd.read_csv(fname, delimiter=' ', header=0, on_bad_lines="skip")
#df = df.drop(columns=['best', 'minuses'])
print(dfdyn)

                            vertex    start_time   finish_time  proc_num
0            get_software_versions      0.000000     20.978000         5
1             output_documentation      0.000000     20.978000         1
2                           kraken     20.978000     41.956000         5
3      lanemerge_hostremoval_fastq     20.978000     41.956000         1
4                    indexinputbam      0.000000     55.941333         3
5                       convertBam     41.956000     62.934000         5
6                             malt     41.956000     62.934000         1
7                  unzip_reference     62.934000     83.912000         5
8                     kraken_parse     83.912000    104.890000         5
9                            fastp    104.890000    125.868000         5
10                          fastqc    125.868000   1980.466250         5
11                     maltextract     62.934000     83.912000         1
12                    makeBWAIndex   1980.466250   2001.444250         5
13               circulargenerator   2001.444250   2022.422250         5
14                  makeFastaIndex   2022.422250   2043.400250         5
15                     makeSeqDict   2043.400250   2064.378250         5
16     mask_reference_for_pmdtools   2064.378250   2085.356250         5
17                    kraken_merge   2085.356250   2106.334250         5
18                 adapter_removal   2106.334250   8021.980000         5
19                       lanemerge   8021.980000   8042.958000         5
20           fastqc_after_clipping   8042.958000   8797.852500         5
21          post_ar_fastq_trimming   8797.852500   8818.830500         5
22                             bwa   8818.830500  32112.888250         5
23                  circularmapper  32112.888250  32133.866250         5
24                          bwamem  32133.866250  32154.844250         5
25                         bowtie2  32154.844250  32175.822250         5
26                   seqtype_merge  32175.822250  32196.800250         5
27         hostremoval_input_fastq  32196.803710  32217.781710         5
28                 samtools_filter  32217.781710  32310.472585         5
29               samtools_flagstat  32310.472585  32392.797710         5
30                  markduplicates  32392.797710  33000.426210         5
31                           dedup  33000.426210  33021.404210         5
32  samtools_flagstat_after_filter  33021.404210  33042.382210         5
33                          preseq  33042.382210  33209.929710         5
34   metagenomic_complexity_filter  33209.929710  33230.907710         5
35                        endorSpy  33230.907710  33251.885710         5
36                   library_merge  33251.885710  33272.863710         5
37           nuclear_contamination  33272.863710  33293.841710         5
38                  damageprofiler  33293.841710  33861.708085         5
39                              fr  33861.708085  33882.686085         5
40                        bam_trim  33882.686085  33903.664085         5
41                        pmdtools  33903.664085  33924.642085         5
42             mapdamage_rescaling  33924.642085  33945.620085         5
43                        bedtools  33945.620085  33966.598085         5
44        additional_library_merge  33966.598085  33987.576085         5
45     print_nuclear_contamination  33987.576085  34008.554085         5
46                   genotyping_hc  34008.554085  60428.103085         5
47         genotyping_pileupcaller  60428.103085  60449.081085         5
48              sexdeterrmine_prep  60449.081085  60470.059085         5
49                   genotyping_ug  60470.059085  60491.037085         5
50                        qualimap  60491.037085  60792.409085         5
51            genotyping_freebayes  60792.409085  60813.387085         5
52                genotyping_angsd  60813.387085  60834.365085         5
53                  bcftools_stats  60834.365085  60916.962960         5
54         eigenstrat_snp_coverage  60916.962960  60937.940960         5
55                   sexdeterrmine  60937.940960  60958.918960         5
56                multivcfanalyzer  60958.918960  60979.896960         5
57                      vcf2genome  60979.896960  61000.874960         5
58                         multiqc  61000.882893  61021.860893         5

In [31]:
fname= "./static_results_eager.txt"
dfstat = pd.read_csv(fname, delimiter=' ', header=0, on_bad_lines="skip")
#df = df.drop(columns=['best', 'minuses'])
print(dfstat)

                            vertex    start_time   finish_time  proc_num
0                       convertBam      0.000000     20.978000         5
1                            fastp     20.978000     41.956000         5
2                  adapter_removal     41.956000   5957.601750         5
3                  unzip_reference      0.000000     20.978000         1
4                     makeBWAIndex     20.978000     41.956000         1
5                        lanemerge   5957.601750   5978.579750         5
6                              bwa   5978.579750  29272.637500         5
7                circulargenerator     41.956000     62.934000         1
8                    indexinputbam      0.000000     55.941333         3
9                   circularmapper  29272.637500  29293.615500         5
10                          bwamem  29293.615500  29314.593500         5
11                         bowtie2  29314.593500  29335.571500         5
12                   seqtype_merge  29335.571500  29356.549500         5
13                 samtools_filter  29356.549500  29449.240375         5
14                  markduplicates  29449.240375  30056.868875         5
15                           dedup  30056.868875  30077.846875         5
16                   library_merge  30077.846875  30098.824875         5
17                        bam_trim  30098.824875  30119.802875         5
18        additional_library_merge  30119.802875  30140.780875         5
19                     makeSeqDict     62.934000     83.912000         1
20                  makeFastaIndex     83.912000    104.890000         1
21                   genotyping_hc  30140.780875  56560.329875         5
22                          kraken      0.000000     83.912000         4
23           nuclear_contamination  56560.329875  56581.307875         5
24         genotyping_pileupcaller  56581.307875  56602.285875         5
25                            malt      0.000000    111.882667         2
26              sexdeterrmine_prep  56602.285875  56623.263875         5
27                    kraken_parse     83.912000    167.824000         4
28               samtools_flagstat  56623.263875  56705.589000         5
29                   genotyping_ug  56705.589000  56726.567000         5
30  samtools_flagstat_after_filter  56726.567000  56747.545000         5
31                          fastqc  56747.545000  58602.143250         5
32           fastqc_after_clipping  58602.143250  59357.037750         5
33                  damageprofiler  59357.037750  59924.904125         5
34                        qualimap  59924.904125  60226.276125         5
35                          preseq  60226.276125  60393.823625         5
36            genotyping_freebayes  60393.823625  60414.801625         5
37                  bcftools_stats  60414.801625  60497.399500         5
38                     maltextract    111.882667    223.765333         2
39                   sexdeterrmine  60497.399500  60518.377500         5
40     print_nuclear_contamination  60518.377500  60539.355500         5
41         eigenstrat_snp_coverage  60539.355500  60560.333500         5
42                        endorSpy  60560.333500  60581.311500         5
43   metagenomic_complexity_filter  60581.311500  60602.289500         5
44                multivcfanalyzer  60602.289500  60623.267500         5
45                              fr  60623.267500  60644.245500         5
46           get_software_versions     55.941333    111.882667         3
47     lanemerge_hostremoval_fastq    104.890000    125.868000         1
48     mask_reference_for_pmdtools    125.868000    146.846000         1
49          post_ar_fastq_trimming  60644.245500  60665.223500         5
50                        pmdtools  60665.223500  60686.201500         5
51             mapdamage_rescaling  60686.201500  60707.179500         5
52                genotyping_angsd  60707.179500  60728.157500         5
53                      vcf2genome  94642.751497  94663.729497         5
54                         multiqc  94663.729497  94684.707497         5
55         hostremoval_input_fastq  94684.707497  94705.685497         5
56                        bedtools  94705.685497  94726.663497         5
57                    kraken_merge    167.824000    251.736000         4
58            output_documentation    111.882667    167.824000         3

In [3]:
def byProcessor(somedf):
    for proc, df_proc in somedf.groupby("proc_num"):
        print(f"\n=== Processor {proc} ===")
        df_sorted = df_proc.sort_values("start_time")

        for _, r in df_sorted.iterrows():
            print(f"{r['start_time']:>10.3f}  {r['finish_time']:>10.3f}  {r['vertex']}")


#for proc, df_proc in dfdyn.groupby("proc_num"):
#    print(f"\n=== Processor {proc} ===")
#    df_sorted = df_proc.sort_values("start_time")#

#    for _, r in df_sorted.iterrows():
#        print(f"{r['start_time']:>10.3f}  {r['finish_time']:>10.3f}  {r['vertex']}")

byProcessor(dfdyn)

=== Processor 0 ===
     0.000      37.156  get_software_versions_00001786
    37.156      74.312  output_documentation_00001699
    74.312     111.468  get_software_versions_00001606
   111.468     148.623  get_software_versions_00001570
   148.623     185.779  get_software_versions_00001534
   185.779     222.935  get_software_versions_00001498
   222.935     260.091  get_software_versions_00001462
   260.091   15786.542  fastqc_00001436
 15786.542   15823.698  get_software_versions_00001078
 15823.698   15860.854  output_documentation_00001063
 15860.854   15898.010  output_documentation_00001039
 15898.010   15935.166  get_software_versions_00001006
 15935.166   15972.322  output_documentation_00000979
 15972.322   16009.478  get_software_versions_00000946
 16009.478   16046.633  get_software_versions_00000910
 16046.633   16083.789  get_software_versions_00000874
 16083.789   16120.945  get_software_versions_00000838
 16120.945   16158.101  get_software_versions_00000802
 16158.101   16195.257  get_software_versions_00000778
 16195.257   31721.708  fastqc_00000764
 31721.708   31758.864  get_software_versions_00000562
 31758.864   31796.020  get_software_versions_00000538
 31796.020   31833.176  output_documentation_00000511
 31833.176   31870.332  get_software_versions_00000478
 31870.332   31907.487  get_software_versions_00000442
 31907.487   31944.643  get_software_versions_00000406
 31944.643   31981.799  get_software_versions_00000370
 31981.799   32018.955  get_software_versions_00000346
 32018.955   47545.407  fastqc_00000332
 47545.407   47582.562  get_software_versions_00000130
 47582.562   47619.718  get_software_versions_00000106
 47619.718   47656.874  output_documentation_00000079
 47656.874   47694.030  get_software_versions_00000046
 47694.030   47731.186  output_documentation_00000019

=== Processor 1 ===
     0.000      37.156  output_documentation_00001795
    37.156      74.312  get_software_versions_00001702
    74.312     111.468  output_documentation_00001615
   111.468     148.623  output_documentation_00001579
   148.623     185.779  output_documentation_00001543
   185.779     222.935  output_documentation_00001507
   222.935     260.091  output_documentation_00001471
   260.091     297.247  get_software_versions_00001438
   297.247     334.402  output_documentation_00001423
   334.402     371.558  output_documentation_00001411
   371.558   15898.010  fastqc_00001400
 15898.010   15935.166  get_software_versions_00001030
 15935.166   15972.322  output_documentation_00001003
 15972.322   16009.478  get_software_versions_00000970
 16009.478   16046.633  get_software_versions_00000934
 16046.633   16083.789  get_software_versions_00000898
 16083.789   16120.945  get_software_versions_00000862
 16120.945   16158.101  get_software_versions_00000826
 16158.101   16195.257  output_documentation_00000799
 16195.257   31721.708  fastqc_00000776
 31721.708   31758.864  get_software_versions_00000574
 31758.864   31796.020  get_software_versions_00000550
 31796.020   31833.176  get_software_versions_00000526
 31833.176   31870.332  output_documentation_00000499
 31870.332   31907.487  get_software_versions_00000466
 31907.487   31944.643  get_software_versions_00000430
 31944.643   31981.799  get_software_versions_00000394
 31981.799   32018.955  output_documentation_00000367
 32018.955   32056.111  output_documentation_00000343
 32056.111   32093.267  output_documentation_00000331
 32093.267   32130.423  output_documentation_00000319
 32130.423   32167.578  get_software_versions_00000310
 32167.578   47694.030  fastqc_00000308
 47694.030   47731.186  output_documentation_00000012

=== Processor 2 ===
     0.000      37.156  get_software_versions_00001798
    37.156      74.312  output_documentation_00001711
    74.312     111.468  get_software_versions_00001618
   111.468     148.623  get_software_versions_00001582
   148.623     185.779  get_software_versions_00001546
   185.779     222.935  get_software_versions_00001510
   222.935     260.091  get_software_versions_00001474
   260.091     297.247  output_documentation_00001447
   297.247   15823.698  fastqc_00001424
 15823.698   15860.854  output_documentation_00001075
 15860.854   15898.010  output_documentation_00001051
 15898.010   15935.166  get_software_versions_00001018
 15935.166   15972.322  output_documentation_00000991
 15972.322   16009.478  get_software_versions_00000958
 16009.478   16046.633  get_software_versions_00000922
 16046.633   16083.789  get_software_versions_00000886
 16083.789   16120.945  get_software_versions_00000850
 16120.945   16158.101  get_software_versions_00000814
 16158.101   16195.257  output_documentation_00000787
 16195.257   16232.413  get_software_versions_00000766
 16232.413   16269.568  get_software_versions_00000754
 16269.568   16306.724  output_documentation_00000751
 16306.724   16343.880  get_software_versions_00000742
 16343.880   31870.332  fastqc_00000740
 31870.332   31907.487  output_documentation_00000451
 31907.487   31944.643  output_documentation_00000415
 31944.643   31981.799  output_documentation_00000379
 31981.799   32018.955  output_documentation_00000355
 32018.955   32056.111  get_software_versions_00000334
 32056.111   32093.267  get_software_versions_00000322
 32093.267   47619.718  fastqc_00000320
 47619.718   47656.874  get_software_versions_00000082
 47656.874   47694.030  output_documentation_00000055
 47694.030   47731.186  get_software_versions_00000022

=== Processor 3 ===
     0.000      37.156  output_documentation_00001807
    37.156      74.312  get_software_versions_00001714
    74.312     111.468  output_documentation_00001627
   111.468     148.623  output_documentation_00001591
   148.623     185.779  output_documentation_00001555
   185.779     222.935  output_documentation_00001519
   222.935     260.091  output_documentation_00001483
   260.091   15786.542  fastqc_00001448
 15786.542   15823.698  output_documentation_00001087
 15823.698   15860.854  get_software_versions_00001066
 15860.854   15898.010  get_software_versions_00001042
 15898.010   15935.166  output_documentation_00001015
 15935.166   15972.322  get_software_versions_00000982
 15972.322   16009.478  output_documentation_00000955
 16009.478   16046.633  output_documentation_00000919
 16046.633   16083.789  output_documentation_00000883
 16083.789   16120.945  output_documentation_00000847
 16120.945   16158.101  output_documentation_00000811
 16158.101   31684.553  fastqc_00000788
 31684.553   31721.708  get_software_versions_00000586
 31721.708   31758.864  output_documentation_00000571
 31758.864   31796.020  output_documentation_00000547
 31796.020   31833.176  get_software_versions_00000514
 31833.176   31870.332  output_documentation_00000487
 31870.332   31907.487  get_software_versions_00000454
 31907.487   31944.643  get_software_versions_00000418
 31944.643   31981.799  get_software_versions_00000382
 31981.799   47508.251  fastqc_00000356
 47508.251   47545.407  get_software_versions_00000154
 47545.407   47582.562  output_documentation_00000139
 47582.562   47619.718  output_documentation_00000115
 47619.718   47656.874  output_documentation_00000091
 47656.874   47694.030  get_software_versions_00000058
 47694.030   47731.186  output_documentation_00000031

=== Processor 4 ===
     0.000      37.156  get_software_versions_00001810
    37.156      74.312  output_documentation_00001723
    74.312     111.468  get_software_versions_00001630
   111.468     148.623  get_software_versions_00001594
   148.623     185.779  get_software_versions_00001558
   185.779     222.935  get_software_versions_00001522
   222.935     260.091  get_software_versions_00001486
   260.091     297.247  get_software_versions_00001450
   297.247     334.402  get_software_versions_00001426
   334.402   15860.854  fastqc_00001412
 15860.854   15898.010  get_software_versions_00001054
 15898.010   15935.166  output_documentation_00001027
 15935.166   15972.322  get_software_versions_00000994
 15972.322   16009.478  output_documentation_00000967
 16009.478   16046.633  output_documentation_00000931
 16046.633   16083.789  output_documentation_00000895
 16083.789   16120.945  output_documentation_00000859
 16120.945   16158.101  output_documentation_00000823
 16158.101   16195.257  get_software_versions_00000790
 16195.257   16232.413  output_documentation_00000775
 16232.413   16269.568  output_documentation_00000763
 16269.568   31796.020  fastqc_00000752
 31796.020   31833.176  output_documentation_00000523
 31833.176   31870.332  get_software_versions_00000490
 31870.332   31907.487  output_documentation_00000463
 31907.487   31944.643  output_documentation_00000427
 31944.643   31981.799  output_documentation_00000391
 31981.799   32018.955  get_software_versions_00000358
 32018.955   47545.407  fastqc_00000344
 47545.407   47582.562  get_software_versions_00000142
 47582.562   47619.718  get_software_versions_00000118
 47619.718   47656.874  get_software_versions_00000094
 47656.874   47694.030  output_documentation_00000067
 47694.030   47731.186  get_software_versions_00000034
36869955.191  36869992.346  multiqc_00000989

=== Processor 5 ===
     0.000      37.156  output_documentation_00001819
    37.156      74.312  get_software_versions_00001726
    74.312     111.468  output_documentation_00001639
   111.468     148.623  output_documentation_00001603
   148.623     185.779  output_documentation_00001567
   185.779     222.935  output_documentation_00001531
   222.935     260.091  output_documentation_00001495
   260.091     297.247  output_documentation_00001459
   297.247     334.402  output_documentation_00001435
   334.402     371.558  get_software_versions_00001414
   371.558     408.714  get_software_versions_00001402
   408.714     445.870  output_documentation_00001399
   445.870     483.026  get_software_versions_00001390
   483.026   16009.478  fastqc_00001388
 16009.478   16046.633  output_documentation_00000943
 16046.633   16083.789  output_documentation_00000907
 16083.789   16120.945  output_documentation_00000871
 16120.945   16158.101  output_documentation_00000835
 16158.101   31684.553  fastqc_00000800
 31684.553   31721.708  output_documentation_00000595
 31721.708   31758.864  output_documentation_00000583
 31758.864   31796.020  output_documentation_00000559
 31796.020   31833.176  output_documentation_00000535
 31833.176   31870.332  get_software_versions_00000502
 31870.332   31907.487  output_documentation_00000475
 31907.487   31944.643  output_documentation_00000439
 31944.643   31981.799  output_documentation_00000403
 31981.799   47508.251  fastqc_00000368
 47508.251   47545.407  output_documentation_00000163
 47545.407   47582.562  output_documentation_00000151
 47582.562   47619.718  output_documentation_00000127
 47619.718   47656.874  output_documentation_00000103
 47656.874   47694.030  get_software_versions_00000070
 47694.030   47731.186  output_documentation_00000043
 47731.186   47768.342  get_software_versions_00000005

=== Processor 6 ===
     0.000       4.644  output_documentation_00001963
     4.644       9.289  get_software_versions_00001942
     9.289    1950.095  fastqc_00001928
  1950.095    3890.902  fastqc_00001892
  3890.902   21059.363  trim_galore_00001860
 21059.363   23000.170  fastqc_00001160
 23000.170   24940.976  fastqc_00001028
7342088.251  7380316.076  trim_galore_00000996
14705235.866  14739572.789  trim_galore_00000708
22064492.579  22098829.502  trim_galore_00000492
29423749.292  29458086.215  trim_galore_00000204
36783006.005  36811802.275  bismark_align_00001851
36811802.275  36823430.083  bismark_align_00001767
36823430.083  36835057.892  bismark_align_00000987
36835057.892  36846685.700  bismark_align_00000699
36846685.700  36858313.508  bismark_align_00000483
36858313.508  36869941.317  bismark_align_00000195
39565739.529  39565744.174  multiqc_00001853
41196738.593  41196743.238  multiqc_00000737
41201043.141  41201047.786  multiqc_00001889
41202957.328  41202961.973  bismark_summary_00000422
41202967.865  41202972.510  multiqc_00000425
41203102.977  41203110.691  bismark_report_00000282
41203202.677  41203210.391  bismark_report_00000774

=== Processor 7 ===
     0.000    1940.806  fastqc_00001964
  1940.806   19109.268  trim_galore_00001908
 19109.268   21050.074  fastqc_00001256
 21050.074   22990.881  fastqc_00001196
 22990.881   24931.687  fastqc_00001052
7342088.251  7378365.981  trim_galore_00001020
14703285.771  14737622.694  trim_galore_00000732
22062542.484  22096879.407  trim_galore_00000516
29421799.196  29456136.119  trim_galore_00000228
36781055.909  36809852.179  bismark_align_00001911
36809852.179  36821479.988  bismark_align_00001803
36821479.988  36833107.796  bismark_align_00001011
36833107.796  36844735.605  bismark_align_00000723
36844735.605  36856363.413  bismark_align_00000507
36856363.413  36867991.221  bismark_align_00000219
36869953.555  36869958.200  multiqc_00001037
41196732.703  41196737.348  multiqc_00001013
41196737.356  41196742.001  multiqc_00000725
41196747.894  41196752.539  bismark_summary_00000542
41196752.539  41196757.183  bismark_deduplicate_00000225
41196757.183  41196761.828  preseq_00000227
41196761.828  41196900.824  bismark_methXtract_00000220
41196900.824  41196930.060  qualimap_00000217
41196930.060  41196937.774  bismark_report_00000222
41196937.774  41196942.418  bismark_summary_00000218
41196942.418  41196947.063  multiqc_00000221
41202957.323  41202965.037  bismark_report_00000426
41203179.151  41203183.796  bismark_summary_00001346
41203189.691  41203194.336  multiqc_00001349
41203202.670  41203207.314  bismark_summary_00000914

=== Processor 8 ===
     0.000       4.644  get_software_versions_00001966
     4.644   17173.106  trim_galore_00001944
 17173.106   19113.912  fastqc_00001364
 19113.912   21054.719  fastqc_00001244
 21054.719   22995.525  fastqc_00001184
7342088.251  7376429.819  trim_galore_00001044
14701349.609  14735686.532  trim_galore_00000756
22060606.322  22094943.245  trim_galore_00000540
29419863.035  29454199.957  trim_galore_00000252
36779119.747  36807916.017  bismark_align_00001923
36807916.017  36819543.826  bismark_align_00001839
36819543.826  36831171.634  bismark_align_00001035
36831171.634  36842799.443  bismark_align_00000747
36842799.443  36854427.251  bismark_align_00000531
36854427.251  36866055.059  bismark_align_00000243
41196714.800  41196719.445  multiqc_00001769
41196732.703  41196737.348  multiqc_00000749
41196743.246  41196747.891  multiqc_00000713
41201207.160  41201211.805  multiqc_00001361
41201813.771  41201818.415  multiqc_00001937
41203171.312  41203175.956  bismark_summary_00001418
41203181.852  41203186.496  multiqc_00001421
41203194.830  41203199.475  bismark_summary_00001130
41203205.370  41203210.015  multiqc_00001133

=== Processor 9 ===
     0.000   17168.461  trim_galore_00001968
 17168.461   19109.268  fastqc_00001376
 19109.268   21050.074  fastqc_00001268
 21050.074   22990.881  fastqc_00001208
 22990.881   24931.687  fastqc_00001064
7342088.251  7376425.174  trim_galore_00001056
14701344.964  14735681.887  trim_galore_00000768
22060601.677  22094938.600  trim_galore_00000552
29419858.390  29454195.313  trim_galore_00000264
36779115.103  36807911.373  bismark_align_00001947
36807911.373  36819539.181  bismark_align_00001827
36819539.181  36831166.990  bismark_align_00001047
36831166.990  36842794.798  bismark_align_00000759
36842794.798  36854422.607  bismark_align_00000543
36854422.607  36866050.415  bismark_align_00000255
41196724.405  41196729.049  multiqc_00001829
41196732.699  41196737.343  multiqc_00001049
41196737.352  41196741.996  multiqc_00000761
41196742.005  41196749.719  bismark_report_00000546
41196752.546  41196757.190  multiqc_00000545
41200986.324  41200990.969  multiqc_00001961
41203171.305  41203179.018  bismark_report_00001422
41203186.991  41203191.635  bismark_summary_00001274
41203197.531  41203202.175  multiqc_00001277
41203208.069  41203212.714  bismark_summary_00000770
41203218.609  41203223.253  multiqc_00000773

=== Processor 10 ===
     0.000       4.644  output_documentation_00001975
     4.644       9.289  output_documentation_00001951
     9.289   17177.750  trim_galore_00001932
 17177.750   19118.557  fastqc_00001352
 19118.557   21059.363  fastqc_00001232
 21059.363   23000.170  fastqc_00001172
 23000.170   24940.976  fastqc_00001040
7342088.251  7376434.463  trim_galore_00001032
14701354.253  14735691.176  trim_galore_00000744
22060610.966  22094947.889  trim_galore_00000528
29419867.679  29454204.602  trim_galore_00000240
36779124.392  36807920.662  bismark_align_00001899
36807920.662  36819548.470  bismark_align_00001815
36819548.470  36831176.279  bismark_align_00001023
36831176.279  36842804.087  bismark_align_00000735
36842804.087  36854431.895  bismark_align_00000519
36854431.895  36866059.704  bismark_align_00000231
41196713.078  41196717.722  multiqc_00001841
41196738.594  41196743.238  multiqc_00001001
41201016.092  41201020.736  multiqc_00001985
41201070.191  41201074.835  multiqc_00001793
41201097.240  41201101.885  multiqc_00001721
41201124.290  41201128.934  multiqc_00001649
41201153.061  41201157.706  multiqc_00001577
41201180.111  41201184.755  multiqc_00001433
41201234.210  41201238.854  multiqc_00001289
41201261.259  41201265.904  multiqc_00001145
41201288.308  41201292.953  multiqc_00000929
41201315.358  41201320.002  multiqc_00000785
41201789.440  41201794.084  multiqc_00001973
41201823.386  41201831.100  bismark_report_00001866
41201843.539  41201848.183  multiqc_00001865
41201870.588  41201875.232  multiqc_00001781
41201886.670  41201891.314  bismark_summary_00001706
41201979.658  41201984.302  bismark_summary_00001634
41203163.473  41203168.117  bismark_summary_00001562
41203174.012  41203178.657  multiqc_00001565
41203186.984  41203194.697  bismark_report_00001278
41203202.662  41203210.376  bismark_report_00000918
41203296.590  41203301.234  bismark_summary_00000626

=== Processor 11 ===
     0.000    1940.806  fastqc_00001976
  1940.806    3881.613  fastqc_00001916
  3881.613   21050.074  trim_galore_00001884
 21050.074   22990.881  fastqc_00001220
 22990.881   24931.687  fastqc_00001076
7342088.251  7380306.787  trim_galore_00001008
14705226.577  14739563.500  trim_galore_00000720
22064483.290  22098820.213  trim_galore_00000504
29423740.003  29458076.926  trim_galore_00000216
36782996.716  36811792.986  bismark_align_00001875
36811792.986  36823420.794  bismark_align_00001755
36823420.794  36835048.603  bismark_align_00000999
36835048.603  36846676.411  bismark_align_00000711
36846676.411  36858304.219  bismark_align_00000495
36858304.219  36869932.028  bismark_align_00000207
41196721.682  41196726.327  multiqc_00001877
41196735.413  41196740.058  multiqc_00001757
41200620.021  41200624.666  preseq_00000131
41200968.890  41200976.604  bismark_report_00001962
41200978.503  41200983.147  bismark_summary_00001958
41200995.940  41201003.654  bismark_report_00001986
41201005.552  41201010.197  bismark_summary_00001982
41201022.989  41201030.703  bismark_report_00001890
41201032.601  41201037.246  bismark_summary_00001886
41201050.039  41201057.752  bismark_report_00001794
41201059.651  41201064.295  bismark_summary_00001790
41201077.088  41201084.802  bismark_report_00001722
41201086.700  41201091.345  bismark_summary_00001718
41201104.137  41201111.851  bismark_report_00001650
41201113.750  41201118.394  bismark_summary_00001646
41201132.909  41201140.623  bismark_report_00001578
41201142.521  41201147.166  bismark_summary_00001574
41201159.959  41201167.672  bismark_report_00001434
41201169.571  41201174.215  bismark_summary_00001430
41201187.008  41201194.722  bismark_report_00001362
41201196.620  41201201.265  bismark_summary_00001358
41201214.057  41201221.771  bismark_report_00001290
41201223.670  41201228.314  bismark_summary_00001286

In [33]:

byProcessor(dfstat)

=== Processor 1 ===
     0.000      20.978  unzip_reference
    20.978      41.956  makeBWAIndex
    41.956      62.934  circulargenerator
    62.934      83.912  makeSeqDict
    83.912     104.890  makeFastaIndex
   104.890     125.868  lanemerge_hostremoval_fastq
   125.868     146.846  mask_reference_for_pmdtools

=== Processor 2 ===
     0.000     111.883  malt
   111.883     223.765  maltextract

=== Processor 3 ===
     0.000      55.941  indexinputbam
    55.941     111.883  get_software_versions
   111.883     167.824  output_documentation

=== Processor 4 ===
     0.000      83.912  kraken
    83.912     167.824  kraken_parse
   167.824     251.736  kraken_merge

=== Processor 5 ===
     0.000      20.978  convertBam
    20.978      41.956  fastp
    41.956    5957.602  adapter_removal
  5957.602    5978.580  lanemerge
  5978.580   29272.638  bwa
 29272.638   29293.615  circularmapper
 29293.615   29314.593  bwamem
 29314.593   29335.571  bowtie2
 29335.571   29356.550  seqtype_merge
 29356.550   29449.240  samtools_filter
 29449.240   30056.869  markduplicates
 30056.869   30077.847  dedup
 30077.847   30098.825  library_merge
 30098.825   30119.803  bam_trim
 30119.803   30140.781  additional_library_merge
 30140.781   56560.330  genotyping_hc
 56560.330   56581.308  nuclear_contamination
 56581.308   56602.286  genotyping_pileupcaller
 56602.286   56623.264  sexdeterrmine_prep
 56623.264   56705.589  samtools_flagstat
 56705.589   56726.567  genotyping_ug
 56726.567   56747.545  samtools_flagstat_after_filter
 56747.545   58602.143  fastqc
 58602.143   59357.038  fastqc_after_clipping
 59357.038   59924.904  damageprofiler
 59924.904   60226.276  qualimap
 60226.276   60393.824  preseq
 60393.824   60414.802  genotyping_freebayes
 60414.802   60497.399  bcftools_stats
 60497.399   60518.378  sexdeterrmine
 60518.378   60539.355  print_nuclear_contamination
 60539.355   60560.334  eigenstrat_snp_coverage
 60560.334   60581.312  endorSpy
 60581.312   60602.289  metagenomic_complexity_filter
 60602.289   60623.268  multivcfanalyzer
 60623.268   60644.245  fr
 60644.245   60665.224  post_ar_fastq_trimming
 60665.224   60686.202  pmdtools
 60686.202   60707.179  mapdamage_rescaling
 60707.179   60728.158  genotyping_angsd
 94642.751   94663.729  vcf2genome
 94663.729   94684.707  multiqc
 94684.707   94705.685  hostremoval_input_fastq
 94705.685   94726.663  bedtools

In [27]:
# compute durations
dfdyn["duration_dyn"] = dfdyn["finish_time"] - dfdyn["start_time"]
dfstat["duration_stat"] = dfstat["finish_time"] - dfstat["start_time"]

# rename processors
dfdyn = dfdyn.rename(columns={"proc_num": "processor_dyn"})
dfstat = dfstat.rename(columns={"proc_num": "processor_stat"})

# merge
merged = dfdyn.merge(dfstat, on="vertex", suffixes=("_dyn", "_stat"))

# find mismatches
diff = merged[ (merged["duration_dyn"] != merged["duration_stat"] )]# & (merged["processor_dyn"] == merged["processor_stat"])  ]

# pick columns to show
diff = diff[[
    "vertex",
    "duration_dyn",
    "processor_dyn",
    "duration_stat",
    "processor_stat"
]]

print(diff)

                            vertex  duration_dyn  processor_dyn  \
0            get_software_versions     20.978000              5
1             output_documentation     20.978000              1
2                           kraken     20.978000              5
3      lanemerge_hostremoval_fastq     20.978000              1
5                       convertBam     20.978000              5
6                             malt     20.978000              1
7                  unzip_reference     20.978000              5
8                     kraken_parse     20.978000              5
9                            fastp     20.978000              5
10                          fastqc   1854.598250              5
11                     maltextract     20.978000              1
12                    makeBWAIndex     20.978000              5
13               circulargenerator     20.978000              5
14                  makeFastaIndex     20.978000              5
15                     makeSeqDict     20.978000              5
16     mask_reference_for_pmdtools     20.978000              5
17                    kraken_merge     20.978000              5
20           fastqc_after_clipping    754.894500              5
21          post_ar_fastq_trimming     20.978000              5
25                         bowtie2     20.978000              5
26                   seqtype_merge     20.978000              5
27         hostremoval_input_fastq     20.978000              5
29               samtools_flagstat     82.325125              5
31                           dedup     20.978000              5
32  samtools_flagstat_after_filter     20.978000              5
36                   library_merge     20.978000              5
37           nuclear_contamination     20.978000              5
39                              fr     20.978000              5
41                        pmdtools     20.978000              5
42             mapdamage_rescaling     20.978000              5
43                        bedtools     20.978000              5
44        additional_library_merge     20.978000              5
45     print_nuclear_contamination     20.978000              5
46                   genotyping_hc  26419.549000              5
47         genotyping_pileupcaller     20.978000              5
48              sexdeterrmine_prep     20.978000              5
49                   genotyping_ug     20.978000              5
50                        qualimap    301.372000              5
52                genotyping_angsd     20.978000              5
55                   sexdeterrmine     20.978000              5

    duration_stat  processor_stat
0       55.941333               3
1       55.941333               3
2       83.912000               4
3       20.978000               1
5       20.978000               5
6      111.882667               2
7       20.978000               1
8       83.912000               4
9       20.978000               5
10    1854.598250               5
11     111.882667               2
12      20.978000               1
13      20.978000               1
14      20.978000               1
15      20.978000               1
16      20.978000               1
17      83.912000               4
20     754.894500               5
21      20.978000               5
25      20.978000               5
26      20.978000               5
27      20.978000               5
29      82.325125               5
31      20.978000               5
32      20.978000               5
36      20.978000               5
37      20.978000               5
39      20.978000               5
41      20.978000               5
42      20.978000               5
43      20.978000               5
44      20.978000               5
45      20.978000               5
46   26419.549000               5
47      20.978000               5
48      20.978000               5
49      20.978000               5
50     301.372000               5
52      20.978000               5
55      20.978000               5

In [37]:
fname= "./dynamic_results_atacseq.txt"
dfdyn = pd.read_csv(fname, delimiter=' ', header=0, on_bad_lines="skip")
#df = df.drop(columns=['best', 'minuses'])
#print(dfdyn)
fname= "./static_results_atacseq.txt"
dfstat = pd.read_csv(fname, delimiter=' ', header=0, on_bad_lines="skip")
#df = df.drop(columns=['best', 'minuses'])
#print(dfstat)

byProcessor(dfdyn)
print("--------------------------")
byProcessor(dfstat)

=== Processor 30 ===
     0.000   58022.363  CHECK_DESIGN
 58022.363  668136.425  TRIMGALORE
668136.425  908829.550  FASTQC
908829.550  2220030.487  BWA_MEM
2220030.487  2494927.263  SORT_BAM
2494927.263  3416329.587  MERGED_LIB_BAM
3416329.587  4095709.612  MERGED_LIB_BAM_FILTER
4095709.612  4487844.100  MERGED_LIB_BAM_REMOVE_ORPHAN
4487844.100  4872804.287  MERGED_LIB_MACS2
4872855.265  5073354.227  MERGED_LIB_BIGWIG
5073354.227  5275942.327  MERGED_LIB_PICARD_METRICS
5275942.327  5333964.690  MERGED_LIB_PLOTFINGERPRINT
5334020.435  5498967.160  MERGED_LIB_ATAQV
5498967.160  5562937.122  MERGED_LIB_MACS2_ANNOTATE
5562937.122  5620959.485  MERGED_LIB_CONSENSUS_COUNTS
5620959.485  5678981.847  MERGED_LIB_ATAQV_MKARV
5678981.847  5737004.210  MERGED_LIB_MACS2_QC
5737004.210  5795026.572  MERGED_LIB_CONSENSUS_DESEQ2
5795028.910  5853051.273  MULTIQC
5853064.702  5911087.064  IGV

=== Processor 31 ===
     0.000   58022.363  BWA_INDEX

=== Processor 32 ===
     0.000   58022.363  MAKE_GENE_BED
 58022.363  116044.725  MAKE_TSS_BED
5325637.695  5612261.395  MERGED_LIB_PLOTPROFILE

=== Processor 33 ===
     0.000   58022.363  MAKE_GENOME_FILTER
4702688.099  4760710.462  MERGED_REP_BIGWIG
4897092.456  4955114.819  MERGED_REP_MACS2_QC

=== Processor 34 ===
     0.000   58022.363  get_software_versions
4871005.854  4929028.216  MERGED_REP_CONSENSUS_ANNOTATE
5273486.256  5331508.618  MERGED_LIB_CONSENSUS
5331508.618  5389530.981  MERGED_LIB_CONSENSUS_ANNOTATE

=== Processor 35 ===
     0.000   58022.363  output_documentation
3520877.558  3578899.920  MERGED_LIB_PRESEQ
4592392.070  4650414.433  MERGED_REP_BAM
4650414.433  4708436.795  MERGED_REP_MACS2
4708436.795  4766459.158  MERGED_REP_CONSENSUS
4766459.158  4824481.520  MERGED_REP_MACS2_ANNOTATE
5221316.083  5279338.445  MERGED_REP_CONSENSUS_COUNTS
5279338.445  5337360.808  MERGED_REP_CONSENSUS_DESEQ2
--------------------------

=== Processor 11 ===
     0.000   58022.363  output_documentation

=== Processor 30 ===
     0.000   58022.363  get_software_versions

=== Processor 31 ===
4630209.218  4688231.580  MERGED_REP_BIGWIG
4734647.462  4792669.824  MERGED_REP_CONSENSUS_ANNOTATE

=== Processor 32 ===
     0.000   58022.363  MAKE_GENE_BED
 58022.363  116044.725  MAKE_TSS_BED
4630317.350  4688339.712  MERGED_REP_MACS2_ANNOTATE
4688339.712  4746362.075  MERGED_REP_MACS2_QC

=== Processor 33 ===
     0.000   58022.363  MAKE_GENOME_FILTER
4840980.956  4899003.319  MERGED_REP_CONSENSUS_COUNTS
4899003.319  4957025.681  MERGED_REP_CONSENSUS_DESEQ2
5925207.275  5983229.638  IGV

=== Processor 34 ===
     0.000   58022.363  BWA_INDEX
4351698.945  4409721.308  MERGED_REP_BAM
4409721.308  4467743.670  MERGED_REP_MACS2
4467743.670  4525766.033  MERGED_REP_CONSENSUS
4736659.133  4794681.495  MERGED_LIB_CONSENSUS
4794681.495  4852703.858  MERGED_LIB_CONSENSUS_COUNTS
4852703.858  4910726.220  MERGED_LIB_CONSENSUS_DESEQ2
5795419.453  5853441.815  MERGED_LIB_MACS2_QC
5897969.330  5955991.692  MERGED_LIB_ATAQV_MKARV
5955991.692  6014014.055  MERGED_LIB_CONSENSUS_ANNOTATE

=== Processor 35 ===
     0.000   58022.363  CHECK_DESIGN
 58022.363  668136.425  TRIMGALORE
668136.425  1979337.363  BWA_MEM
1979337.363  2254234.138  SORT_BAM
2254234.138  3175636.462  MERGED_LIB_BAM
3175636.462  3855016.487  MERGED_LIB_BAM_FILTER
3855016.487  4247150.975  MERGED_LIB_BAM_REMOVE_ORPHAN
4247150.975  4632111.162  MERGED_LIB_MACS2
4632111.162  4832610.125  MERGED_LIB_BIGWIG
4832610.125  5119233.825  MERGED_LIB_PLOTPROFILE
5119233.825  5359926.950  FASTQC
5359926.950  5562515.050  MERGED_LIB_PICARD_METRICS
5562515.050  5727461.775  MERGED_LIB_ATAQV
5727461.775  5791431.737  MERGED_LIB_MACS2_ANNOTATE
5791431.737  5849454.100  MERGED_LIB_PLOTFINGERPRINT
5849454.100  5907476.463  MERGED_LIB_PRESEQ
5907476.463  5965498.825  MULTIQC

In [4]:
fname= "./dynamic_results_methylseq_2000.txt"
dfdyn = pd.read_csv(fname, delimiter=' ', header=0, on_bad_lines="skip")
#df = df.drop(columns=['best', 'minuses'])
#print(dfdyn)
fname= "./static_results_methylseq_2000.txt"
dfstat = pd.read_csv(fname, delimiter=' ', header=0, on_bad_lines="skip")
#df = df.drop(columns=['best', 'minuses'])
#print(dfstat)

byProcessor(dfdyn)
print("--------------------------")
byProcessor(dfstat)

=== Processor 0 ===
     0.000      37.156  get_software_versions_00001786
    37.156      74.312  output_documentation_00001699
    74.312     111.468  get_software_versions_00001606
   111.468     148.623  get_software_versions_00001570
   148.623     185.779  get_software_versions_00001534
   185.779     222.935  get_software_versions_00001498
   222.935     260.091  get_software_versions_00001462
   260.091   15786.542  fastqc_00001436
 15786.542   15823.698  get_software_versions_00001078
 15823.698   15860.854  output_documentation_00001063
 15860.854   15898.010  output_documentation_00001039
 15898.010   15935.166  get_software_versions_00001006
 15935.166   15972.322  output_documentation_00000979
 15972.322   16009.478  get_software_versions_00000946
 16009.478   16046.633  get_software_versions_00000910
 16046.633   16083.789  get_software_versions_00000874
 16083.789   16120.945  get_software_versions_00000838
 16120.945   16158.101  get_software_versions_00000802
 16158.101   16195.257  get_software_versions_00000778
 16195.257   31721.708  fastqc_00000764
 31721.708   31758.864  get_software_versions_00000562
 31758.864   31796.020  get_software_versions_00000538
 31796.020   31833.176  output_documentation_00000511
 31833.176   31870.332  get_software_versions_00000478
 31870.332   31907.487  get_software_versions_00000442
 31907.487   31944.643  get_software_versions_00000406
 31944.643   31981.799  get_software_versions_00000370
 31981.799   32018.955  get_software_versions_00000346
 32018.955   47545.407  fastqc_00000332
 47545.407   47582.562  get_software_versions_00000130
 47582.562   47619.718  get_software_versions_00000106
 47619.718   47656.874  output_documentation_00000079
 47656.874   47694.030  get_software_versions_00000046
 47694.030   47731.186  output_documentation_00000019

=== Processor 1 ===
     0.000      37.156  output_documentation_00001795
    37.156      74.312  get_software_versions_00001702
    74.312     111.468  output_documentation_00001615
   111.468     148.623  output_documentation_00001579
   148.623     185.779  output_documentation_00001543
   185.779     222.935  output_documentation_00001507
   222.935     260.091  output_documentation_00001471
   260.091     297.247  get_software_versions_00001438
   297.247     334.402  output_documentation_00001423
   334.402     371.558  output_documentation_00001411
   371.558   15898.010  fastqc_00001400
 15898.010   15935.166  get_software_versions_00001030
 15935.166   15972.322  output_documentation_00001003
 15972.322   16009.478  get_software_versions_00000970
 16009.478   16046.633  get_software_versions_00000934
 16046.633   16083.789  get_software_versions_00000898
 16083.789   16120.945  get_software_versions_00000862
 16120.945   16158.101  get_software_versions_00000826
 16158.101   16195.257  output_documentation_00000799
 16195.257   31721.708  fastqc_00000776
 31721.708   31758.864  get_software_versions_00000574
 31758.864   31796.020  get_software_versions_00000550
 31796.020   31833.176  get_software_versions_00000526
 31833.176   31870.332  output_documentation_00000499
 31870.332   31907.487  get_software_versions_00000466
 31907.487   31944.643  get_software_versions_00000430
 31944.643   31981.799  get_software_versions_00000394
 31981.799   32018.955  output_documentation_00000367
 32018.955   32056.111  output_documentation_00000343
 32056.111   32093.267  output_documentation_00000331
 32093.267   32130.423  output_documentation_00000319
 32130.423   32167.578  get_software_versions_00000310
 32167.578   47694.030  fastqc_00000308
 47694.030   47731.186  output_documentation_00000012

=== Processor 2 ===
     0.000      37.156  get_software_versions_00001798
    37.156      74.312  output_documentation_00001711
    74.312     111.468  get_software_versions_00001618
   111.468     148.623  get_software_versions_00001582
   148.623     185.779  get_software_versions_00001546
   185.779     222.935  get_software_versions_00001510
   222.935     260.091  get_software_versions_00001474
   260.091     297.247  output_documentation_00001447
   297.247   15823.698  fastqc_00001424
 15823.698   15860.854  output_documentation_00001075
 15860.854   15898.010  output_documentation_00001051
 15898.010   15935.166  get_software_versions_00001018
 15935.166   15972.322  output_documentation_00000991
 15972.322   16009.478  get_software_versions_00000958
 16009.478   16046.633  get_software_versions_00000922
 16046.633   16083.789  get_software_versions_00000886
 16083.789   16120.945  get_software_versions_00000850
 16120.945   16158.101  get_software_versions_00000814
 16158.101   16195.257  output_documentation_00000787
 16195.257   16232.413  get_software_versions_00000766
 16232.413   16269.568  get_software_versions_00000754
 16269.568   16306.724  output_documentation_00000751
 16306.724   16343.880  get_software_versions_00000742
 16343.880   31870.332  fastqc_00000740
 31870.332   31907.487  output_documentation_00000451
 31907.487   31944.643  output_documentation_00000415
 31944.643   31981.799  output_documentation_00000379
 31981.799   32018.955  output_documentation_00000355
 32018.955   32056.111  get_software_versions_00000334
 32056.111   32093.267  get_software_versions_00000322
 32093.267   47619.718  fastqc_00000320
 47619.718   47656.874  get_software_versions_00000082
 47656.874   47694.030  output_documentation_00000055
 47694.030   47731.186  get_software_versions_00000022

=== Processor 3 ===
     0.000      37.156  output_documentation_00001807
    37.156      74.312  get_software_versions_00001714
    74.312     111.468  output_documentation_00001627
   111.468     148.623  output_documentation_00001591
   148.623     185.779  output_documentation_00001555
   185.779     222.935  output_documentation_00001519
   222.935     260.091  output_documentation_00001483
   260.091   15786.542  fastqc_00001448
 15786.542   15823.698  output_documentation_00001087
 15823.698   15860.854  get_software_versions_00001066
 15860.854   15898.010  get_software_versions_00001042
 15898.010   15935.166  output_documentation_00001015
 15935.166   15972.322  get_software_versions_00000982
 15972.322   16009.478  output_documentation_00000955
 16009.478   16046.633  output_documentation_00000919
 16046.633   16083.789  output_documentation_00000883
 16083.789   16120.945  output_documentation_00000847
 16120.945   16158.101  output_documentation_00000811
 16158.101   31684.553  fastqc_00000788
 31684.553   31721.708  get_software_versions_00000586
 31721.708   31758.864  output_documentation_00000571
 31758.864   31796.020  output_documentation_00000547
 31796.020   31833.176  get_software_versions_00000514
 31833.176   31870.332  output_documentation_00000487
 31870.332   31907.487  get_software_versions_00000454
 31907.487   31944.643  get_software_versions_00000418
 31944.643   31981.799  get_software_versions_00000382
 31981.799   47508.251  fastqc_00000356
 47508.251   47545.407  get_software_versions_00000154
 47545.407   47582.562  output_documentation_00000139
 47582.562   47619.718  output_documentation_00000115
 47619.718   47656.874  output_documentation_00000091
 47656.874   47694.030  get_software_versions_00000058
 47694.030   47731.186  output_documentation_00000031

=== Processor 4 ===
     0.000      37.156  get_software_versions_00001810
    37.156      74.312  output_documentation_00001723
    74.312     111.468  get_software_versions_00001630
   111.468     148.623  get_software_versions_00001594
   148.623     185.779  get_software_versions_00001558
   185.779     222.935  get_software_versions_00001522
   222.935     260.091  get_software_versions_00001486
   260.091     297.247  get_software_versions_00001450
   297.247     334.402  get_software_versions_00001426
   334.402   15860.854  fastqc_00001412
 15860.854   15898.010  get_software_versions_00001054
 15898.010   15935.166  output_documentation_00001027
 15935.166   15972.322  get_software_versions_00000994
 15972.322   16009.478  output_documentation_00000967
 16009.478   16046.633  output_documentation_00000931
 16046.633   16083.789  output_documentation_00000895
 16083.789   16120.945  output_documentation_00000859
 16120.945   16158.101  output_documentation_00000823
 16158.101   16195.257  get_software_versions_00000790
 16195.257   16232.413  output_documentation_00000775
 16232.413   16269.568  output_documentation_00000763
 16269.568   31796.020  fastqc_00000752
 31796.020   31833.176  output_documentation_00000523
 31833.176   31870.332  get_software_versions_00000490
 31870.332   31907.487  output_documentation_00000463
 31907.487   31944.643  output_documentation_00000427
 31944.643   31981.799  output_documentation_00000391
 31981.799   32018.955  get_software_versions_00000358
 32018.955   47545.407  fastqc_00000344
 47545.407   47582.562  get_software_versions_00000142
 47582.562   47619.718  get_software_versions_00000118
 47619.718   47656.874  get_software_versions_00000094
 47656.874   47694.030  output_documentation_00000067
 47694.030   47731.186  get_software_versions_00000034
36869955.191  36869992.346  multiqc_00000989

=== Processor 5 ===
     0.000      37.156  output_documentation_00001819
    37.156      74.312  get_software_versions_00001726
    74.312     111.468  output_documentation_00001639
   111.468     148.623  output_documentation_00001603
   148.623     185.779  output_documentation_00001567
   185.779     222.935  output_documentation_00001531
   222.935     260.091  output_documentation_00001495
   260.091     297.247  output_documentation_00001459
   297.247     334.402  output_documentation_00001435
   334.402     371.558  get_software_versions_00001414
   371.558     408.714  get_software_versions_00001402
   408.714     445.870  output_documentation_00001399
   445.870     483.026  get_software_versions_00001390
   483.026   16009.478  fastqc_00001388
 16009.478   16046.633  output_documentation_00000943
 16046.633   16083.789  output_documentation_00000907
 16083.789   16120.945  output_documentation_00000871
 16120.945   16158.101  output_documentation_00000835
 16158.101   31684.553  fastqc_00000800
 31684.553   31721.708  output_documentation_00000595
 31721.708   31758.864  output_documentation_00000583
 31758.864   31796.020  output_documentation_00000559
 31796.020   31833.176  output_documentation_00000535
 31833.176   31870.332  get_software_versions_00000502
 31870.332   31907.487  output_documentation_00000475
 31907.487   31944.643  output_documentation_00000439
 31944.643   31981.799  output_documentation_00000403
 31981.799   47508.251  fastqc_00000368
 47508.251   47545.407  output_documentation_00000163
 47545.407   47582.562  output_documentation_00000151
 47582.562   47619.718  output_documentation_00000127
 47619.718   47656.874  output_documentation_00000103
 47656.874   47694.030  get_software_versions_00000070
 47694.030   47731.186  output_documentation_00000043
 47731.186   47768.342  get_software_versions_00000005

=== Processor 6 ===
     0.000       4.644  output_documentation_00001963
     4.644       9.289  get_software_versions_00001942
     9.289    1950.095  fastqc_00001928
  1950.095    3890.902  fastqc_00001892
  3890.902   21059.363  trim_galore_00001860
 21059.363   23000.170  fastqc_00001160
 23000.170   24940.976  fastqc_00001028
7342088.251  7380316.076  trim_galore_00000996
14705235.866  14739572.789  trim_galore_00000708
22064492.579  22098829.502  trim_galore_00000492
29423749.292  29458086.215  trim_galore_00000204
36783006.005  36811802.275  bismark_align_00001851
36811802.275  36823430.083  bismark_align_00001767
36823430.083  36835057.892  bismark_align_00000987
36835057.892  36846685.700  bismark_align_00000699
36846685.700  36858313.508  bismark_align_00000483
36858313.508  36869941.317  bismark_align_00000195
39565739.529  39565744.174  multiqc_00001853
41196738.593  41196743.238  multiqc_00000737
41201043.141  41201047.786  multiqc_00001889
41202957.328  41202961.973  bismark_summary_00000422
41202967.865  41202972.510  multiqc_00000425
41203102.977  41203110.691  bismark_report_00000282
41203202.677  41203210.391  bismark_report_00000774

=== Processor 7 ===
     0.000    1940.806  fastqc_00001964
  1940.806   19109.268  trim_galore_00001908
 19109.268   21050.074  fastqc_00001256
 21050.074   22990.881  fastqc_00001196
 22990.881   24931.687  fastqc_00001052
7342088.251  7378365.981  trim_galore_00001020
14703285.771  14737622.694  trim_galore_00000732
22062542.484  22096879.407  trim_galore_00000516
29421799.196  29456136.119  trim_galore_00000228
36781055.909  36809852.179  bismark_align_00001911
36809852.179  36821479.988  bismark_align_00001803
36821479.988  36833107.796  bismark_align_00001011
36833107.796  36844735.605  bismark_align_00000723
36844735.605  36856363.413  bismark_align_00000507
36856363.413  36867991.221  bismark_align_00000219
36869953.555  36869958.200  multiqc_00001037
41196732.703  41196737.348  multiqc_00001013
41196737.356  41196742.001  multiqc_00000725
41196747.894  41196752.539  bismark_summary_00000542
41196752.539  41196757.183  bismark_deduplicate_00000225
41196757.183  41196761.828  preseq_00000227
41196761.828  41196900.824  bismark_methXtract_00000220
41196900.824  41196930.060  qualimap_00000217
41196930.060  41196937.774  bismark_report_00000222
41196937.774  41196942.418  bismark_summary_00000218
41196942.418  41196947.063  multiqc_00000221
41202957.323  41202965.037  bismark_report_00000426
41203179.151  41203183.796  bismark_summary_00001346
41203189.691  41203194.336  multiqc_00001349
41203202.670  41203207.314  bismark_summary_00000914

=== Processor 8 ===
     0.000       4.644  get_software_versions_00001966
     4.644   17173.106  trim_galore_00001944
 17173.106   19113.912  fastqc_00001364
 19113.912   21054.719  fastqc_00001244
 21054.719   22995.525  fastqc_00001184
7342088.251  7376429.819  trim_galore_00001044
14701349.609  14735686.532  trim_galore_00000756
22060606.322  22094943.245  trim_galore_00000540
29419863.035  29454199.957  trim_galore_00000252
36779119.747  36807916.017  bismark_align_00001923
36807916.017  36819543.826  bismark_align_00001839
36819543.826  36831171.634  bismark_align_00001035
36831171.634  36842799.443  bismark_align_00000747
36842799.443  36854427.251  bismark_align_00000531
36854427.251  36866055.059  bismark_align_00000243
41196714.800  41196719.445  multiqc_00001769
41196732.703  41196737.348  multiqc_00000749
41196743.246  41196747.891  multiqc_00000713
41201207.160  41201211.805  multiqc_00001361
41201813.771  41201818.415  multiqc_00001937
41203171.312  41203175.956  bismark_summary_00001418
41203181.852  41203186.496  multiqc_00001421
41203194.830  41203199.475  bismark_summary_00001130
41203205.370  41203210.015  multiqc_00001133

=== Processor 9 ===
     0.000   17168.461  trim_galore_00001968
 17168.461   19109.268  fastqc_00001376
 19109.268   21050.074  fastqc_00001268
 21050.074   22990.881  fastqc_00001208
 22990.881   24931.687  fastqc_00001064
7342088.251  7376425.174  trim_galore_00001056
14701344.964  14735681.887  trim_galore_00000768
22060601.677  22094938.600  trim_galore_00000552
29419858.390  29454195.313  trim_galore_00000264
36779115.103  36807911.373  bismark_align_00001947
36807911.373  36819539.181  bismark_align_00001827
36819539.181  36831166.990  bismark_align_00001047
36831166.990  36842794.798  bismark_align_00000759
36842794.798  36854422.607  bismark_align_00000543
36854422.607  36866050.415  bismark_align_00000255
41196724.405  41196729.049  multiqc_00001829
41196732.699  41196737.343  multiqc_00001049
41196737.352  41196741.996  multiqc_00000761
41196742.005  41196749.719  bismark_report_00000546
41196752.546  41196757.190  multiqc_00000545
41200986.324  41200990.969  multiqc_00001961
41203171.305  41203179.018  bismark_report_00001422
41203186.991  41203191.635  bismark_summary_00001274
41203197.531  41203202.175  multiqc_00001277
41203208.069  41203212.714  bismark_summary_00000770
41203218.609  41203223.253  multiqc_00000773

=== Processor 10 ===
     0.000       4.644  output_documentation_00001975
     4.644       9.289  output_documentation_00001951
     9.289   17177.750  trim_galore_00001932
 17177.750   19118.557  fastqc_00001352
 19118.557   21059.363  fastqc_00001232
 21059.363   23000.170  fastqc_00001172
 23000.170   24940.976  fastqc_00001040
7342088.251  7376434.463  trim_galore_00001032
14701354.253  14735691.176  trim_galore_00000744
22060610.966  22094947.889  trim_galore_00000528
29419867.679  29454204.602  trim_galore_00000240
36779124.392  36807920.662  bismark_align_00001899
36807920.662  36819548.470  bismark_align_00001815
36819548.470  36831176.279  bismark_align_00001023
36831176.279  36842804.087  bismark_align_00000735
36842804.087  36854431.895  bismark_align_00000519
36854431.895  36866059.704  bismark_align_00000231
41196713.078  41196717.722  multiqc_00001841
41196738.594  41196743.238  multiqc_00001001
41201016.092  41201020.736  multiqc_00001985
41201070.191  41201074.835  multiqc_00001793
41201097.240  41201101.885  multiqc_00001721
41201124.290  41201128.934  multiqc_00001649
41201153.061  41201157.706  multiqc_00001577
41201180.111  41201184.755  multiqc_00001433
41201234.210  41201238.854  multiqc_00001289
41201261.259  41201265.904  multiqc_00001145
41201288.308  41201292.953  multiqc_00000929
41201315.358  41201320.002  multiqc_00000785
41201789.440  41201794.084  multiqc_00001973
41201823.386  41201831.100  bismark_report_00001866
41201843.539  41201848.183  multiqc_00001865
41201870.588  41201875.232  multiqc_00001781
41201886.670  41201891.314  bismark_summary_00001706
41201979.658  41201984.302  bismark_summary_00001634
41203163.473  41203168.117  bismark_summary_00001562
41203174.012  41203178.657  multiqc_00001565
41203186.984  41203194.697  bismark_report_00001278
41203202.662  41203210.376  bismark_report_00000918
41203296.590  41203301.234  bismark_summary_00000626

=== Processor 11 ===
     0.000    1940.806  fastqc_00001976
  1940.806    3881.613  fastqc_00001916
  3881.613   21050.074  trim_galore_00001884
 21050.074   22990.881  fastqc_00001220
 22990.881   24931.687  fastqc_00001076
7342088.251  7380306.787  trim_galore_00001008
14705226.577  14739563.500  trim_galore_00000720
22064483.290  22098820.213  trim_galore_00000504
29423740.003  29458076.926  trim_galore_00000216
36782996.716  36811792.986  bismark_align_00001875
36811792.986  36823420.794  bismark_align_00001755
36823420.794  36835048.603  bismark_align_00000999
36835048.603  36846676.411  bismark_align_00000711
36846676.411  36858304.219  bismark_align_00000495
36858304.219  36869932.028  bismark_align_00000207
41196721.682  41196726.327  multiqc_00001877
41196735.413  41196740.058  multiqc_00001757
41200620.021  41200624.666  preseq_00000131
41200968.890  41200976.604  bismark_report_00001962
41200978.503  41200983.147  bismark_summary_00001958
41200995.940  41201003.654  bismark_report_00001986
41201005.552  41201010.197  bismark_summary_00001982
41201022.989  41201030.703  bismark_report_00001890
41201032.601  41201037.246  bismark_summary_00001886
41201050.039  41201057.752  bismark_report_00001794
41201059.651  41201064.295  bismark_summary_00001790
41201077.088  41201084.802  bismark_report_00001722
41201086.700  41201091.345  bismark_summary_00001718
41201104.137  41201111.851  bismark_report_00001650
41201113.750  41201118.394  bismark_summary_00001646
41201132.909  41201140.623  bismark_report_00001578
41201142.521  41201147.166  bismark_summary_00001574
41201159.959  41201167.672  bismark_report_00001434
41201169.571  41201174.215  bismark_summary_00001430
41201187.008  41201194.722  bismark_report_00001362
41201196.620  41201201.265  bismark_summary_00001358
41201214.057  41201221.771  bismark_report_00001290
41201223.670  41201228.314  bismark_summary_00001286

In [3]:
%run ChartsCommon.ipynb
labels = ['A1', 'A2', 'A3', 'BASE']

path = "./ruben-werte/final-kinda/merged/*.txt"
print(path)

patterndevs = r'^(BASE|A\d+)-(ndev)'

dfs=read_dfs(path,patterndevs, 2)

dfsVar1 = [dfs[('A1','ndev')], dfs[('A2','ndev')], dfs[('A3','ndev')], dfs[('BASE','ndev')]]
#print(dfsVar1)
merged_df_var1 = merge_correct_columns(dfsVar1, labels)
plot_df_old = buld_plot_df(merged_df_var1)
plot_df_old = plot_df_old[plot_df_old["size"]!= 18000]

print("----------------------------------------------")
print(plot_df_old.info)

print("----------------------------------------------")

path = "./results-3-12/merged/*.txt"
print(path)

patterndevs = r'^(BASE|A\d+)-(ndev)'

dfs=read_dfs(path,patterndevs, 2)

dfsVar1 = [dfs[('A1','ndev')], dfs[('A2','ndev')], dfs[('A3','ndev')], dfs[('BASE','ndev')]]
#print(dfsVar1)
merged_df_var1 = merge_correct_columns(dfsVar1, labels)
plot_df_new = buld_plot_df(merged_df_var1)
plot_df_new = plot_df_new[plot_df_new["size"]!= 18000]

print(plot_df)

./ruben-werte/final-kinda/merged/*.txt
----------------------------------------------
<bound method DataFrame.info of        size              wf_name     inp_size      relation     ratio  \
0     30000    atacseq_30000.dot  14091675276      internal  1.301302
1     15000    chipseq_15000.dot  41366257414      internal  1.307672
2     15000  methylseq_15000.dot   6761426956      internal  0.898391
3       100                eager  19075314980      internal  0.545767
4      1000       eager_1000.dot  25705994498      internal  1.057662
...     ...                  ...          ...           ...       ...
2272    100              atacseq   2223941232  stat_vs_base  0.805369
2273    100              atacseq   3908761308  stat_vs_base  0.824926
2274    100              atacseq  11187378708  stat_vs_base  0.933790
2275    100              atacseq  11809629756  stat_vs_base  0.929529
2276    100              atacseq  14091675276  stat_vs_base  1.042867

     algorithm
0     MeDiH-BL
1     MeDiH-BL
2     MeDiH-BL
3     MeDiH-BL
4     MeDiH-BL
...        ...
2272  MeDiH-MM
2273  MeDiH-MM
2274  MeDiH-MM
2275  MeDiH-MM
2276  MeDiH-MM

[2277 rows x 6 columns]>
----------------------------------------------
./results-3-12/merged/*.txt

NameError: name 'plot_df' is not defined

In [34]:
plot_df_old2 = plot_df_old.rename(columns={"ratio": "ratio_old"})
plot_df_new2 = plot_df_new.rename(columns={"ratio": "ratio_new"})
merged_plots_dfs = plot_df_old2.merge(
    plot_df_new2,
    on=["wf_name", "inp_size", "algorithm", "relation"],
   # how="outer"
    how="inner"
)

diff = merged_plots_dfs[merged_plots_dfs["ratio_old"] != merged_plots_dfs["ratio_new"]]
#print(diff[["wf_name","size_x", "relation", "ratio_old", "ratio_new"]])
#diff[["wf_name","size_x", "relation", "ratio_old", "ratio_new"]].to_csv("not_equal_ratios.csv", index=False)

diff_correct_cols= diff[["wf_name","inp_size", "size_x", "relation", "ratio_old", "ratio_new"]]

#print(diff_correct_cols[diff_correct_cols["ratio_old"]<diff_correct_cols["ratio_new"]])
print(diff_correct_cols[diff_correct_cols["relation"] == "stat_vs_base"])
stat_vs_base_rels= diff_correct_cols[diff_correct_cols["relation"] == "stat_vs_base"]
print(stat_vs_base_rels[stat_vs_base_rels["size_x"]<1000])


#same = merged_plots_dfs[merged_plots_dfs["ratio_old"] == merged_plots_dfs["ratio_new"]]
#print("-----------------------------------\n Same: \n", same)
#same.to_csv("equal_ratios.csv", index=False)

                  wf_name     inp_size  size_x      relation    ratio_old  \
482     atacseq_30000.dot  14091675276   30000  stat_vs_base  5159.513264
483     chipseq_15000.dot  41366257414   15000  stat_vs_base  1592.410410
484   methylseq_15000.dot   6761426956   15000  stat_vs_base   120.453235
485        eager_1000.dot  25705994498    1000  stat_vs_base  2079.474207
486       eager_20000.dot   8330435694   20000  stat_vs_base  9258.240122
...                   ...          ...     ...           ...          ...
2163  methylseq_25000.dot  22500260922   25000  stat_vs_base   812.601269
2164    chipseq_30000.dot   3793245764   30000  stat_vs_base  6352.195862
2165   methylseq_1000.dot   8885797810    1000  stat_vs_base    99.796692
2166  methylseq_10000.dot  17027257018   10000  stat_vs_base   159.696540
2168    chipseq_10000.dot   4807293396   10000  stat_vs_base  8702.253677

      ratio_new
482    5.202210
483    1.180069
484    0.657512
485    2.352241
486    4.450395
...         ...
2163   3.508881
2164  16.462359
2165   0.884677
2166   3.041744
2168  14.384162

[661 rows x 6 columns]
                wf_name      inp_size  size_x      relation     ratio_old  \
489     chipseq_200.dot    5058052541     200  stat_vs_base  11822.491706
512     atacseq_200.dot   11809629756     200  stat_vs_base    184.221327
516     chipseq_200.dot   32978181418     200  stat_vs_base    101.376025
522     chipseq_200.dot    4807293396     200  stat_vs_base   9165.253599
523     chipseq_200.dot    3793245764     200  stat_vs_base  11880.786008
552       eager_200.dot   25705994498     200  stat_vs_base      1.130711
554   methylseq_200.dot  110641579976     200  stat_vs_base     56.112653
597     chipseq_200.dot    4605965334     200  stat_vs_base   8963.231725
602     atacseq_200.dot    2223941232     200  stat_vs_base    320.478758
631       eager_200.dot   19100037384     200  stat_vs_base      1.511974
646     atacseq_200.dot   11187378708     200  stat_vs_base    149.174777
664       eager_200.dot   19075314980     200  stat_vs_base      1.322802
689     chipseq_200.dot   41366257414     200  stat_vs_base    318.457411
690       eager_200.dot   19132169434     200  stat_vs_base      1.171357
703       eager_200.dot   14754556884     200  stat_vs_base      1.415419
1212    chipseq_200.dot    5058052541     200  stat_vs_base  11655.292958
1235    atacseq_200.dot   11809629756     200  stat_vs_base    180.151938
1239    chipseq_200.dot   32978181418     200  stat_vs_base    101.271668
1245    chipseq_200.dot    4807293396     200  stat_vs_base   9359.211764
1246    chipseq_200.dot    3793245764     200  stat_vs_base  11856.229022
1275      eager_200.dot   25705994498     200  stat_vs_base      1.130711
1277  methylseq_200.dot  110641579976     200  stat_vs_base     56.112653
1320    chipseq_200.dot    4605965334     200  stat_vs_base   9007.750164
1325    atacseq_200.dot    2223941232     200  stat_vs_base    350.757100
1354      eager_200.dot   19100037384     200  stat_vs_base      1.511974
1369    atacseq_200.dot   11187378708     200  stat_vs_base    151.546372
1387      eager_200.dot   19075314980     200  stat_vs_base      1.322802
1412    chipseq_200.dot   41366257414     200  stat_vs_base    318.774831
1413      eager_200.dot   19132169434     200  stat_vs_base      1.171357
1426      eager_200.dot   14754556884     200  stat_vs_base      1.415419
1935    chipseq_200.dot    5058052541     200  stat_vs_base   6746.443696
1958    atacseq_200.dot   11809629756     200  stat_vs_base     29.400184
1962    chipseq_200.dot   32978181418     200  stat_vs_base     80.275275
1968    chipseq_200.dot    4807293396     200  stat_vs_base   7871.179525
1969    chipseq_200.dot    3793245764     200  stat_vs_base   6932.428379
1998      eager_200.dot   25705994498     200  stat_vs_base      0.603450
2000  methylseq_200.dot  110641579976     200  stat_vs_base     42.426100
2030    atacseq_200.dot   14091675276     200  stat_vs_base      0.254085
2043    chipseq_200.dot    4605965334     200  stat_vs_base   7148.680104
2046    atacseq_200.dot    3908761308     200  stat_vs_base      0.315229
2048    atacseq_200.dot    2223941232     200  stat_vs_base    106.839234
2077      eager_200.dot   19100037384     200  stat_vs_base      0.625633
2092    atacseq_200.dot   11187378708     200  stat_vs_base     26.348167
2110      eager_200.dot   19075314980     200  stat_vs_base      0.712869
2135    chipseq_200.dot   41366257414     200  stat_vs_base    299.477894
2136      eager_200.dot   19132169434     200  stat_vs_base      0.630112
2149      eager_200.dot   14754556884     200  stat_vs_base      1.077311

      ratio_new
489    9.312028
512    1.000000
516    0.899865
522   10.259098
523   10.051255
552    1.000000
554    0.245337
597   10.022958
602    1.016083
631    1.000000
646    1.000000
664    1.000000
689    0.986926
690    1.000000
703    1.000000
1212   9.418232
1235   0.977910
1239   1.005228
1245  10.146422
1246  10.030480
1275   1.000000
1277   0.245337
1320  10.106862
1325   1.112081
1354   1.000000
1369   1.015898
1387   1.000000
1412   0.999778
1413   1.000000
1426   1.000000
1935   5.805472
1958   0.234854
1962   0.818833
1968   6.782807
1969   5.920655
1998   0.533691
2000   0.757676
2030   0.270092
2043   6.297573
2046   0.334845
2048   0.359098
2077   0.446347
2092   0.234495
2110   0.538908
2135   0.908232
2136   0.537934
2149   0.761125

In [4]:
def byProcessor(somedf, proc_column_name, start_time_column_name, finish_time_column_name):
    for proc, df_proc in somedf.groupby(proc_column_name):
        print(f"\n=== Processor {proc} ===")
        df_sorted = df_proc.sort_values(start_time_column_name)

        for _, r in df_sorted.iterrows():
            print(f"{r[start_time_column_name]:>10.3f}  {r[finish_time_column_name]:>10.3f}  {r['vertex']}")
            
fname= "./bl_vs_heft.txt"
bl_and_heft = pd.read_csv(fname, delimiter='\t', header=0, on_bad_lines="warn")
print(bl_and_heft.head())

byProcessor(bl_and_heft, "proc_bl", "start_bl", "finish_bl")

print("------------------------------")

byProcessor(bl_and_heft, "proc_heft", "start_heft", "finish_heft")

                 vertex  start_bl   finish_bl  proc_bl  variant_bl  \
0  trim_galore_00000192       0.0  8887618.95       35           1
1  trim_galore_00000168       0.0  8887618.95       34           1
2  trim_galore_00000072       0.0  8887618.95       33           1
3  trim_galore_00000084       0.0  8887618.95       32           1
4  trim_galore_00000096       0.0  8887618.95       31           1

                vertex1  start_heft  finish_heft  proc_heft  variant_heft
0  trim_galore_00000192         0.0   8887618.95         35             1
1  trim_galore_00000168         0.0   8887618.95         34             1
2  trim_galore_00000072         0.0   8887618.95         33             1
3  trim_galore_00000084         0.0   8887618.95         32             1
4  trim_galore_00000096         0.0   8887618.95         31             1

=== Processor 0 ===
     0.000    1462.400  output_documentation_00000187
  1462.400    2924.800  output_documentation_00000055
  2924.800    4387.200  output_documentation_00000163

=== Processor 1 ===
     0.000    1462.400  get_software_versions_00000070
  1462.400    2924.800  output_documentation_00000091
  2924.800    4387.200  output_documentation_00000019

=== Processor 2 ===
     0.000    1462.400  get_software_versions_00000142
  1462.400    2924.800  output_documentation_00000151
  2924.800    4387.200  output_documentation_00000043

=== Processor 3 ===
     0.000    1462.400  get_software_versions_00000082
  1462.400    2924.800  output_documentation_00000012
  2924.800    4387.200  output_documentation_00000079
  4387.200    5849.600  output_documentation_00000115

=== Processor 4 ===
     0.000    1462.400  get_software_versions_00000118
  1462.400    2924.800  output_documentation_00000127
  2924.800    4387.200  output_documentation_00000175
  4387.200    5849.600  output_documentation_00000103

=== Processor 5 ===
     0.000    1462.400  get_software_versions_00000106
  1462.400    2924.800  output_documentation_00000139
  2924.800    4387.200  output_documentation_00000067
  4387.200    5849.600  output_documentation_00000031

=== Processor 6 ===
     0.000  1093624.938  fastqc_00000092
1093624.938  2187249.875  fastqc_00000001
283706116.774  283706299.574  bismark_deduplicate_00000033
283706299.574  283713939.499  bismark_methXtract_00000028
283713939.499  283721579.424  bismark_methXtract_00000148
306189934.119  306190811.844  bismark_report_00000042
306190811.844  306191689.569  bismark_report_00000090
306197573.879  306198451.604  bismark_report_00000150
306198451.604  306199329.329  bismark_report_00000162
306199329.329  306199512.129  multiqc_00000149
372662075.801  372662258.601  multiqc_00000089
372662258.601  372662441.401  multiqc_00000113

=== Processor 7 ===
     0.000  1093624.938  fastqc_00000032
1093624.938  2187249.875  fastqc_00000080
283706117.084  283706299.884  bismark_deduplicate_00000105
283706299.884  283713939.809  bismark_methXtract_00000100
283713939.809  283716428.634  qualimap_00000157
306189938.885  306190816.610  bismark_report_00000054
306197573.879  306198451.604  bismark_report_00000114
372661892.857  372662075.657  multiqc_00000161
372662076.041  372662258.841  multiqc_00000101

=== Processor 8 ===
     0.000  1093624.938  fastqc_00000116
1093624.938  2187249.875  fastqc_00000140
283706116.618  283706299.418  bismark_deduplicate_00000057
283706299.418  283706482.218  bismark_deduplicate_00000165
283706482.218  283714122.143  bismark_methXtract_00000160
306189936.502  306190814.227  bismark_report_00000078
306197567.735  306198445.460  bismark_report_00000066
306198445.460  306199323.185  bismark_report_00000102
372654253.313  372654436.113  preseq_00000131
372661893.073  372662075.873  preseq_00000143
372662075.873  372662258.673  multiqc_00000077
372662258.673  372662441.473  multiqc_00000029

=== Processor 9 ===
     0.000  1093624.938  fastqc_00000044
1093624.938  2187249.875  fastqc_00000020
261222487.981  261222670.781  bismark_deduplicate_00000081
283706116.929  283706299.729  bismark_deduplicate_00000117
283706299.729  283713939.654  bismark_methXtract_00000112
283713939.654  283716428.479  qualimap_00000145
306189934.119  306190811.844  bismark_report_00000186
306197567.735  306198445.460  bismark_report_00000174
306198445.460  306199323.185  bismark_report_00000030
372654253.313  372654436.113  preseq_00000007
372661892.673  372662075.473  bismark_summary_00000134
372662075.885  372662258.685  multiqc_00000173

=== Processor 10 ===
     0.000  1093624.938  fastqc_00000056
1093624.938  2187249.875  fastqc_00000128
283706116.774  283706299.574  bismark_deduplicate_00000093
283706299.574  283713939.499  bismark_methXtract_00000088
283713939.499  283721579.424  bismark_methXtract_00000052
306189928.235  306192417.060  qualimap_00000169
372654253.173  372656741.998  qualimap_00000121
372661892.673  372662075.473  bismark_summary_00000122
372662075.986  372662258.786  multiqc_00000185

=== Processor 11 ===
     0.000  1093624.938  fastqc_00000104
1093624.938  2187249.875  fastqc_00000068
261222487.826  261222670.626  bismark_deduplicate_00000189
283706116.618  283706299.418  bismark_deduplicate_00000045
283706299.418  283706482.218  bismark_deduplicate_00000153
283706482.218  283714122.143  bismark_methXtract_00000040
306189928.235  306192417.060  qualimap_00000061
372654253.173  372656741.998  qualimap_00000013
372661893.073  372662075.873  preseq_00000023
372662075.957  372662258.757  multiqc_00000041

=== Processor 12 ===
     0.000     974.933  get_software_versions_00000022
306197574.118  306198549.052  preseq_00000083

=== Processor 13 ===
     0.000     974.933  get_software_versions_00000034
306197576.812  306198551.745  bismark_summary_00000062

=== Processor 14 ===
     0.000     974.933  get_software_versions_00000166
306197576.967  306198551.900  preseq_00000071

=== Processor 15 ===
     0.000     974.933  get_software_versions_00000130
306197574.274  306198549.207  bismark_summary_00000074

=== Processor 16 ===
     0.000     974.933  get_software_versions_00000094
306197574.429  306198549.362  preseq_00000155

=== Processor 17 ===
     0.000     974.933  get_software_versions_00000154
306197574.584  306198549.518  bismark_summary_00000170

=== Processor 18 ===
     0.000  2916333.167  fastqc_00000164
261222673.266  261243046.400  bismark_methXtract_00000184
283706300.004  283712936.870  qualimap_00000085
306197572.812  306198060.279  preseq_00000059
306198060.279  306198547.746  bismark_summary_00000098

=== Processor 19 ===
     0.000  2916333.167  fastqc_00000188
261222673.422  261243046.555  bismark_methXtract_00000076
283706300.314  283712937.181  qualimap_00000097
306197572.967  306198060.434  bismark_summary_00000146
306198060.434  306198547.901  preseq_00000179

=== Processor 20 ===
     0.000  2916333.167  fastqc_00000152
261222672.836  261229309.702  qualimap_00000073
283706484.273  283713121.139  qualimap_00000037
306197573.123  306198060.589  bismark_summary_00000050
306198060.589  306198548.056  preseq_00000107

=== Processor 21 ===
     0.000  2916333.167  fastqc_00000176
283706301.473  283712938.339  qualimap_00000049
306197575.195  306198062.662  preseq_00000047
306198062.662  306198550.128  bismark_summary_00000158

=== Processor 22 ===
283706484.537  283713121.404  qualimap_00000181
306197573.278  306198060.745  preseq_00000191
306198060.745  306198548.211  bismark_summary_00000110

=== Processor 23 ===
283706300.159  283712937.026  qualimap_00000109
306197575.350  306198062.817  bismark_summary_00000038
306198062.817  306198550.284  preseq_00000119

=== Processor 24 ===
     0.000     731.200  get_software_versions_00000190
306197573.589  306198304.789  bismark_summary_00000182

=== Processor 25 ===
     0.000     731.200  get_software_versions_00000058
306197573.744  306198304.944  preseq_00000035

=== Processor 26 ===
     0.000     731.200  get_software_versions_00000005
306197575.506  306198306.706  preseq_00000167

=== Processor 27 ===
     0.000     731.200  get_software_versions_00000046
306197575.661  306198306.861  bismark_summary_00000086

=== Processor 28 ===
     0.000     731.200  get_software_versions_00000178
306197575.816  306198307.016  preseq_00000095

=== Processor 29 ===
283706300.004  283716255.304  qualimap_00000025
306197573.433  306198304.633  bismark_summary_00000026

=== Processor 30 ===
     0.000  8887618.950  trim_galore_00000060
31278147.830  187676987.936  trim_galore_00000156
187676987.936  193864700.961  bismark_align_00000147
193864700.961  200052413.986  bismark_align_00000075
232551145.609  238738858.634  bismark_align_00000027
255034774.401  261222487.426  bismark_align_00000183
277518403.193  283706116.218  bismark_align_00000051
300002031.985  306189745.010  bismark_align_00000171
306189745.010  306189927.810  bismark_deduplicate_00000177
306189927.810  306197567.735  bismark_methXtract_00000172
372654253.078  372656741.903  qualimap_00000011
372661892.673  372662075.473  bismark_summary_00000014
372662075.873  372662258.673  multiqc_00000053

=== Processor 31 ===
     0.000  8887618.950  trim_galore_00000096
31278147.830  187676987.936  trim_galore_00000120
187676987.936  193864700.961  bismark_align_00000111
193864700.961  200052413.986  bismark_align_00000159
232551145.609  238738858.634  bismark_align_00000099
255034774.401  261222487.426  bismark_align_00000087
277518403.193  283706116.218  bismark_align_00000039
300002031.985  306189745.010  bismark_align_00000063
306189745.010  306189927.810  bismark_deduplicate_00000069
306189927.810  306197567.735  bismark_methXtract_00000064
372654253.078  372656741.903  qualimap_00000133
372661892.673  372662075.473  bismark_summary_00000009
372662075.945  372662258.745  multiqc_00000065

=== Processor 32 ===
     0.000  8887618.950  trim_galore_00000084
31278147.830  187676987.936  trim_galore_00000036
210067516.816  366466356.923  trim_galore_00000003
366466356.923  372654069.948  bismark_align_00000004
372654069.948  372654252.748  bismark_deduplicate_00000006
372654252.748  372661892.673  bismark_methXtract_00000010
372661892.673  372662770.398  bismark_report_00000008
372662770.398  372662953.198  multiqc_00000002

=== Processor 33 ===
     0.000  8887618.950  trim_galore_00000072
31278147.830  187676987.936  trim_galore_00000180
210067516.816  366466356.923  trim_galore_00000144
366466356.923  372654069.948  bismark_align_00000135
372654069.948  372654252.748  bismark_deduplicate_00000141
372654252.748  372661892.673  bismark_methXtract_00000136
372661892.673  372662770.398  bismark_report_00000138
372662770.398  372662953.198  multiqc_00000137

=== Processor 34 ===
     0.000  8887618.950  trim_galore_00000168
31278147.830  187676987.936  trim_galore_00000048
210067516.816  366466356.923  trim_galore_00000132
366466356.923  372654069.948  bismark_align_00000123
372654069.948  372654252.748  bismark_deduplicate_00000129
372654252.748  372661892.673  bismark_methXtract_00000124
372661892.673  372662770.398  bismark_report_00000126
372662770.398  372662953.198  multiqc_00000125

=== Processor 35 ===
     0.000  8887618.950  trim_galore_00000192
31278147.830  187676987.936  trim_galore_00000108
210067516.816  366466356.923  trim_galore_00000024
366466356.923  372654069.948  bismark_align_00000015
372654069.948  372654252.748  bismark_deduplicate_00000021
372654252.748  372661892.673  bismark_methXtract_00000016
372661892.673  372662770.398  bismark_report_00000018
372662770.398  372662953.198  multiqc_00000017
------------------------------

=== Processor 0 ===
     0.000    1462.400  output_documentation_00000139

=== Processor 1 ===
     0.000    1462.400  output_documentation_00000187

=== Processor 2 ===
     0.000    1462.400  get_software_versions_00000070

=== Processor 3 ===
     0.000    1462.400  get_software_versions_00000142

=== Processor 4 ===
     0.000    1462.400  get_software_versions_00000082
  1462.400    2924.800  output_documentation_00000115

=== Processor 5 ===
     0.000    1462.400  get_software_versions_00000118
  1462.400    2924.800  output_documentation_00000103

=== Processor 6 ===
     0.000  1093624.938  fastqc_00000092
1093624.938  2187249.875  fastqc_00000001
30150850.527  30158490.452  bismark_methXtract_00000112
30158490.452  30166130.377  bismark_methXtract_00000052
32850756.297  32858396.222  bismark_methXtract_00000136
39038466.780  39040955.605  qualimap_00000097
39040955.605  39043444.430  qualimap_00000049
45226185.034  45227062.759  bismark_report_00000138
45227062.759  45227940.484  bismark_report_00000066
45233819.206  45234002.006  preseq_00000107
45234002.118  45234184.918  multiqc_00000137
45234184.918  45234367.718  multiqc_00000113

=== Processor 7 ===
     0.000  1093624.938  fastqc_00000032
1093624.938  2187249.875  fastqc_00000080
30150850.372  30158490.297  bismark_methXtract_00000088
32850756.297  32858396.222  bismark_methXtract_00000076
39038466.625  39040955.450  qualimap_00000061
39040955.450  39043444.275  qualimap_00000073
45226185.034  45227062.759  bismark_report_00000078
45227062.759  45227940.484  bismark_report_00000008
45233819.050  45234001.850  bismark_summary_00000098
45234001.850  45234184.650  bismark_summary_00000074
45234184.650  45234367.450  multiqc_00000077

=== Processor 8 ===
     0.000  1093624.938  fastqc_00000116
1093624.938  2187249.875  fastqc_00000140
30150664.506  30150847.306  bismark_deduplicate_00000153
39038283.456  39038466.256  bismark_deduplicate_00000165
39038466.256  39046106.181  bismark_methXtract_00000160
45226185.034  45227062.759  bismark_report_00000018
45227062.759  45227940.484  bismark_report_00000162
45233819.206  45234002.006  preseq_00000131
45234002.006  45234184.806  multiqc_00000017
45234184.806  45234367.606  multiqc_00000101

=== Processor 9 ===
     0.000  1093624.938  fastqc_00000044
1093624.938  2187249.875  fastqc_00000020
30150664.350  30150847.150  bismark_deduplicate_00000057
39038283.300  39038466.100  bismark_deduplicate_00000069
39038466.100  39046106.025  bismark_methXtract_00000064
45226185.034  45227062.759  bismark_report_00000126
45227062.759  45227940.484  bismark_report_00000102
45233819.050  45234001.850  preseq_00000167
45234001.850  45234184.650  multiqc_00000002
45234184.650  45234367.450  multiqc_00000089

=== Processor 10 ===
     0.000  1093624.938  fastqc_00000056
1093624.938  2187249.875  fastqc_00000128
30150664.506  30150847.306  bismark_deduplicate_00000117
32850570.275  32850753.075  bismark_deduplicate_00000141
39038283.300  39038466.100  bismark_deduplicate_00000006
39038466.100  39046106.025  bismark_methXtract_00000010
45226179.150  45228667.975  qualimap_00000025
45233819.050  45234001.850  preseq_00000035
45234001.850  45234184.650  bismark_summary_00000170
45234184.650  45234367.450  multiqc_00000053

=== Processor 11 ===
     0.000  1093624.938  fastqc_00000104
1093624.938  2187249.875  fastqc_00000068
30150664.350  30150847.150  bismark_deduplicate_00000093
32850570.275  32850753.075  bismark_deduplicate_00000081
39038283.456  39038466.256  bismark_deduplicate_00000105
39038466.256  39046106.181  bismark_methXtract_00000100
45226179.150  45228667.975  qualimap_00000169
45233818.650  45234001.450  bismark_summary_00000182
45234001.450  45234184.250  preseq_00000083
45234184.250  45234367.050  multiqc_00000065

=== Processor 12 ===
     0.000     974.933  get_software_versions_00000034
   974.933    1949.867  output_documentation_00000127
  1949.867    2924.800  output_documentation_00000175

=== Processor 13 ===
     0.000     974.933  get_software_versions_00000166
   974.933    1949.867  output_documentation_00000012
  1949.867    2924.800  output_documentation_00000079

=== Processor 14 ===
     0.000     974.933  get_software_versions_00000130
   974.933    1949.867  output_documentation_00000151
  1949.867    2924.800  output_documentation_00000043

=== Processor 15 ===
     0.000     974.933  get_software_versions_00000094
   974.933    1949.867  output_documentation_00000091
  1949.867    2924.800  output_documentation_00000019

=== Processor 16 ===
     0.000     974.933  get_software_versions_00000154
   974.933    1949.867  output_documentation_00000055
  1949.867    2924.800  output_documentation_00000163

=== Processor 17 ===
     0.000     974.933  get_software_versions_00000106
   974.933    1949.867  output_documentation_00000067
  1949.867    2924.800  output_documentation_00000031

=== Processor 18 ===
     0.000  2916333.167  fastqc_00000164
30150849.946  30171223.079  bismark_methXtract_00000148
32850755.129  32857391.996  qualimap_00000085
39038466.530  39045103.397  qualimap_00000011
39046110.712  39048451.312  bismark_report_00000090
45226183.967  45226671.433  preseq_00000007

=== Processor 19 ===
     0.000  2916333.167  fastqc_00000188
32850755.129  32857391.996  qualimap_00000133
39038466.795  39045103.662  qualimap_00000109
39046113.095  39048453.695  bismark_report_00000114
45226184.122  45226671.589  bismark_summary_00000009

=== Processor 20 ===
     0.000  2916333.167  fastqc_00000152
39038466.342  39045103.208  qualimap_00000013
39046110.712  39048451.312  bismark_report_00000150
45226183.967  45226671.433  bismark_summary_00000014
45227940.556  45228428.022  multiqc_00000149

=== Processor 21 ===
     0.000  2916333.167  fastqc_00000176
30150849.360  30157486.226  qualimap_00000145
39038466.342  39045103.208  qualimap_00000121
39046108.630  39046596.097  preseq_00000059
45226183.967  45226671.433  preseq_00000047

=== Processor 22 ===
39038466.686  39045103.552  qualimap_00000157
39046108.786  39046596.252  bismark_summary_00000146
45226184.122  45226671.589  preseq_00000023

=== Processor 23 ===
39038470.952  39040811.552  bismark_report_00000054
39046108.941  39046596.407  bismark_summary_00000050
45226184.277  45226671.744  preseq_00000191

=== Processor 24 ===
     0.000     731.200  get_software_versions_00000058
39046111.168  39046842.368  preseq_00000095
45226184.122  45226915.322  bismark_summary_00000134

=== Processor 25 ===
     0.000     731.200  get_software_versions_00000005
39046111.324  39046842.524  bismark_summary_00000110
45226184.277  45226915.477  bismark_summary_00000062

=== Processor 26 ===
     0.000     731.200  get_software_versions_00000046
39046111.479  39046842.679  preseq_00000119
45226184.433  45226915.633  preseq_00000071

=== Processor 27 ===
     0.000     731.200  get_software_versions_00000178
45226184.588  45226915.788  preseq_00000143

=== Processor 28 ===
     0.000     731.200  get_software_versions_00000022
39046109.096  39046840.296  preseq_00000155

=== Processor 29 ===
     0.000     731.200  get_software_versions_00000190
39046111.013  39046842.213  bismark_summary_00000086
45226183.967  45226915.167  preseq_00000179

=== Processor 30 ===
     0.000  8887618.950  trim_galore_00000060
8887618.950  17775237.900  trim_galore_00000156
17775237.900  23962950.925  bismark_align_00000147
23962950.925  30150663.950  bismark_align_00000051
39038283.211  39038466.011  bismark_deduplicate_00000129
39038466.011  39046105.936  bismark_methXtract_00000124
45226179.055  45228667.880  qualimap_00000181
45233818.650  45234001.450  bismark_summary_00000026
45234001.450  45234184.250  bismark_summary_00000158
45234184.250  45234367.050  multiqc_00000161

=== Processor 31 ===
     0.000  8887618.950  trim_galore_00000096
8887618.950  17775237.900  trim_galore_00000120
17775237.900  23962950.925  bismark_align_00000111
23962950.925  30150663.950  bismark_align_00000087
39038283.211  39038466.011  bismark_deduplicate_00000021
39038466.011  39046105.936  bismark_methXtract_00000016
45226179.055  45228667.880  qualimap_00000037
45233818.650  45234001.450  bismark_summary_00000038
45234001.450  45234184.250  bismark_summary_00000122
45234184.250  45234367.050  multiqc_00000125

=== Processor 32 ===
     0.000  8887618.950  trim_galore_00000084
8887618.950  17775237.900  trim_galore_00000036

In [5]:
#group = proc // 6
bl_and_heft["group_bl"] = bl_and_heft["proc_bl"] // 6
bl_and_heft["group_heft"] = bl_and_heft["proc_heft"] // 6
diff_groups = bl_and_heft[bl_and_heft["group_bl"] != bl_and_heft["group_heft"]]
print(diff_groups[[
    "vertex", "proc_bl", "group_bl", 
    "proc_heft", "group_heft"
]])

                            vertex  proc_bl  group_bl  proc_heft  group_heft
48    bismark_deduplicate_00000189       11         1         35           5
50    bismark_deduplicate_00000045       11         1         34           5
56    bismark_deduplicate_00000141       33         5         10           1
58    bismark_deduplicate_00000033        6         1         32           5
59    bismark_deduplicate_00000006       32         5         10           1
..                             ...      ...       ...        ...         ...
183               multiqc_00000041       11         1         34           5
184  output_documentation_00000163        0         0         16           2
185               multiqc_00000185       10         1         35           5
187  output_documentation_00000031        5         0         17           2
190               multiqc_00000029        8         1         32           5

[87 rows x 5 columns]

In [6]:
def compare_by_processor_full(df):
    processors = sorted(set(df["proc_bl"]) | set(df["proc_heft"]))

    for proc in processors:
        print(f"\n=== Processor {proc} ===")

        # Extract BL rows on this processor
        bl = df[df["proc_bl"] == proc][[
            "vertex", "start_bl", "finish_bl"
        ]].rename(columns={
            "start_bl": "start",
            "finish_bl": "finish",
        })
        bl["source"] = "BL"

        # Extract HEFT rows on this processor
        hf = df[df["proc_heft"] == proc][[
            "vertex1", "start_heft", "finish_heft"
        ]].rename(columns={
            "vertex1": "vertex",
            "start_heft": "start",
            "finish_heft": "finish",
        })
        hf["source"] = "HEFT"

        # Combine BL + HEFT
        merged = (
            pd.merge(
                bl, hf,
                on=["vertex", "start", "finish"],
                how="outer",
                suffixes=("_bl", "_heft")
            )
        )

        # Sort by start time
        merged = merged.sort_values("start")

        # Pretty print
        for _, r in merged.iterrows():
            print(f"{r.get('start', float('nan')):>10.3f}  "
                  f"{r.get('finish', float('nan')):>10.3f}  "
                  f"{r['vertex']:<40}  "
                  f"{'BL' if not pd.isna(r.get('source_bl')) else ''} "
                  f"{'HEFT' if not pd.isna(r.get('source_heft')) else ''}")
            
compare_by_processor_full(bl_and_heft)

=== Processor 0 ===
     0.000    1462.400  output_documentation_00000187             BL
     0.000    1462.400  output_documentation_00000139              HEFT
  1462.400    2924.800  output_documentation_00000055             BL
  2924.800    4387.200  output_documentation_00000163             BL

=== Processor 1 ===
     0.000    1462.400  get_software_versions_00000070            BL
     0.000    1462.400  output_documentation_00000187              HEFT
  1462.400    2924.800  output_documentation_00000091             BL
  2924.800    4387.200  output_documentation_00000019             BL

=== Processor 2 ===
     0.000    1462.400  get_software_versions_00000142            BL
     0.000    1462.400  get_software_versions_00000070             HEFT
  1462.400    2924.800  output_documentation_00000151             BL
  2924.800    4387.200  output_documentation_00000043             BL

=== Processor 3 ===
     0.000    1462.400  get_software_versions_00000082            BL
     0.000    1462.400  get_software_versions_00000142             HEFT
  1462.400    2924.800  output_documentation_00000012             BL
  2924.800    4387.200  output_documentation_00000079             BL
  4387.200    5849.600  output_documentation_00000115             BL

=== Processor 4 ===
     0.000    1462.400  get_software_versions_00000118            BL
     0.000    1462.400  get_software_versions_00000082             HEFT
  1462.400    2924.800  output_documentation_00000127             BL
  1462.400    2924.800  output_documentation_00000115              HEFT
  2924.800    4387.200  output_documentation_00000175             BL
  4387.200    5849.600  output_documentation_00000103             BL

=== Processor 5 ===
     0.000    1462.400  get_software_versions_00000106            BL
     0.000    1462.400  get_software_versions_00000118             HEFT
  1462.400    2924.800  output_documentation_00000139             BL
  1462.400    2924.800  output_documentation_00000103              HEFT
  2924.800    4387.200  output_documentation_00000067             BL
  4387.200    5849.600  output_documentation_00000031             BL

=== Processor 6 ===
     0.000  1093624.938  fastqc_00000092                           BL HEFT
1093624.938  2187249.875  fastqc_00000001                           BL HEFT
30150850.527  30158490.452  bismark_methXtract_00000112                HEFT
30158490.452  30166130.377  bismark_methXtract_00000052                HEFT
32850756.297  32858396.222  bismark_methXtract_00000136                HEFT
39038466.780  39040955.605  qualimap_00000097                          HEFT
39040955.605  39043444.430  qualimap_00000049                          HEFT
45226185.034  45227062.759  bismark_report_00000138                    HEFT
45227062.759  45227940.484  bismark_report_00000066                    HEFT
45233819.206  45234002.006  preseq_00000107                            HEFT
45234002.118  45234184.918  multiqc_00000137                           HEFT
45234184.918  45234367.718  multiqc_00000113                           HEFT
283706116.774  283706299.574  bismark_deduplicate_00000033              BL
283706299.574  283713939.499  bismark_methXtract_00000028               BL
283713939.499  283721579.424  bismark_methXtract_00000148               BL
306189934.119  306190811.844  bismark_report_00000042                   BL
306190811.844  306191689.569  bismark_report_00000090                   BL
306197573.879  306198451.604  bismark_report_00000150                   BL
306198451.604  306199329.329  bismark_report_00000162                   BL
306199329.329  306199512.129  multiqc_00000149                          BL
372662075.801  372662258.601  multiqc_00000089                          BL
372662258.601  372662441.401  multiqc_00000113                          BL

=== Processor 7 ===
     0.000  1093624.938  fastqc_00000032                           BL HEFT
1093624.938  2187249.875  fastqc_00000080                           BL HEFT
30150850.372  30158490.297  bismark_methXtract_00000088                HEFT
32850756.297  32858396.222  bismark_methXtract_00000076                HEFT
39038466.625  39040955.450  qualimap_00000061                          HEFT
39040955.450  39043444.275  qualimap_00000073                          HEFT
45226185.034  45227062.759  bismark_report_00000078                    HEFT
45227062.759  45227940.484  bismark_report_00000008                    HEFT
45233819.050  45234001.850  bismark_summary_00000098                   HEFT
45234001.850  45234184.650  bismark_summary_00000074                   HEFT
45234184.650  45234367.450  multiqc_00000077                           HEFT
283706117.084  283706299.884  bismark_deduplicate_00000105              BL
283706299.884  283713939.809  bismark_methXtract_00000100               BL
283713939.809  283716428.634  qualimap_00000157                         BL
306189938.885  306190816.610  bismark_report_00000054                   BL
306197573.879  306198451.604  bismark_report_00000114                   BL
372661892.857  372662075.657  multiqc_00000161                          BL
372662076.041  372662258.841  multiqc_00000101                          BL

=== Processor 8 ===
     0.000  1093624.938  fastqc_00000116                           BL HEFT
1093624.938  2187249.875  fastqc_00000140                           BL HEFT
30150664.506  30150847.306  bismark_deduplicate_00000153               HEFT
39038283.456  39038466.256  bismark_deduplicate_00000165               HEFT
39038466.256  39046106.181  bismark_methXtract_00000160                HEFT
45226185.034  45227062.759  bismark_report_00000018                    HEFT
45227062.759  45227940.484  bismark_report_00000162                    HEFT
45233819.206  45234002.006  preseq_00000131                            HEFT
45234002.006  45234184.806  multiqc_00000017                           HEFT
45234184.806  45234367.606  multiqc_00000101                           HEFT
283706116.618  283706299.418  bismark_deduplicate_00000057              BL
283706299.418  283706482.218  bismark_deduplicate_00000165              BL
283706482.218  283714122.143  bismark_methXtract_00000160               BL
306189936.502  306190814.227  bismark_report_00000078                   BL
306197567.735  306198445.460  bismark_report_00000066                   BL
306198445.460  306199323.185  bismark_report_00000102                   BL
372654253.313  372654436.113  preseq_00000131                           BL
372661893.073  372662075.873  preseq_00000143                           BL
372662075.873  372662258.673  multiqc_00000077                          BL
372662258.673  372662441.473  multiqc_00000029                          BL

=== Processor 9 ===
     0.000  1093624.938  fastqc_00000044                           BL HEFT
1093624.938  2187249.875  fastqc_00000020                           BL HEFT
30150664.350  30150847.150  bismark_deduplicate_00000057               HEFT
39038283.300  39038466.100  bismark_deduplicate_00000069               HEFT
39038466.100  39046106.025  bismark_methXtract_00000064                HEFT
45226185.034  45227062.759  bismark_report_00000126                    HEFT
45227062.759  45227940.484  bismark_report_00000102                    HEFT
45233819.050  45234001.850  preseq_00000167                            HEFT
45234001.850  45234184.650  multiqc_00000002                           HEFT
45234184.650  45234367.450  multiqc_00000089                           HEFT
261222487.981  261222670.781  bismark_deduplicate_00000081              BL
283706116.929  283706299.729  bismark_deduplicate_00000117              BL
283706299.729  283713939.654  bismark_methXtract_00000112               BL
283713939.654  283716428.479  qualimap_00000145                         BL
306189934.119  306190811.844  bismark_report_00000186                   BL
306197567.735  306198445.460  bismark_report_00000174                   BL
306198445.460  306199323.185  bismark_report_00000030                   BL
372654253.313  372654436.113  preseq_00000007                           BL
372661892.673  372662075.473  bismark_summary_00000134                  BL
372662075.885  372662258.685  multiqc_00000173                          BL

=== Processor 10 ===
     0.000  1093624.938  fastqc_00000056                           BL HEFT
1093624.938  2187249.875  fastqc_00000128                           BL HEFT
30150664.506  30150847.306  bismark_deduplicate_00000117               HEFT
32850570.275  32850753.075  bismark_deduplicate_00000141               HEFT
39038283.300  39038466.100  bismark_deduplicate_00000006               HEFT
39038466.100  39046106.025  bismark_methXtract_00000010                HEFT
45226179.150  45228667.975  qualimap_00000025                          HEFT
45233819.050  45234001.850  preseq_00000035                            HEFT
45234001.850  45234184.650  bismark_summary_00000170                   HEFT
45234184.650  45234367.450  multiqc_00000053                           HEFT
283706116.774  283706299.574  bismark_deduplicate_00000093              BL
283706299.574  283713939.499  bismark_methXtract_00000088               BL
283713939.499  283721579.424  bismark_methXtract_00000052               BL
306189928.235  306192417.060  qualimap_00000169                         BL
372654253.173  372656741.998  qualimap_00000121                         BL
372661892.673  372662075.473  bismark_summary_00000122                  BL
372662075.986  372662258.786  multiqc_00000185                          BL

=== Processor 11 ===
     0.000  1093624.938  fastqc_00000104                           BL HEFT
1093624.938  2187249.875  fastqc_00000068                           BL HEFT
30150664.350  30150847.150  bismark_deduplicate_00000093               HEFT
32850570.275  32850753.075  bismark_deduplicate_00000081               HEFT
39038283.456  39038466.256  bismark_deduplicate_00000105               HEFT
39038466.256  39046106.181  bismark_methXtract_00000100                HEFT
45226179.150  45228667.975  qualimap_00000169                          HEFT
45233818.650  45234001.450  bismark_summary_00000182                   HEFT
45234001.450  45234184.250  preseq_00000083                            HEFT
45234184.250  45234367.050  multiqc_00000065                           HEFT
261222487.826  261222670.626  bismark_deduplicate_00000189              BL
283706116.618  283706299.418  bismark_deduplicate_00000045              BL
283706299.418  283706482.218  bismark_deduplicate_00000153              BL
283706482.218  283714122.143  bismark_methXtract_00000040               BL
306189928.235  306192417.060  qualimap_00000061                         BL
372654253.173  372656741.998  qualimap_00000013                         BL
372661893.073  372662075.873  preseq_00000023                           BL
372662075.957  372662258.757  multiqc_00000041                          BL

=== Processor 12 ===
     0.000     974.933  get_software_versions_00000022            BL
     0.000     974.933  get_software_versions_00000034             HEFT
   974.933    1949.867  output_documentation_00000127              HEFT
  1949.867    2924.800  output_documentation_00000175              HEFT
306197574.118  306198549.052  preseq_00000083                           BL

=== Processor 13 ===
     0.000     974.933  get_software_versions_00000034            BL
     0.000     974.933  get_software_versions_00000166             HEFT
   974.933    1949.867  output_documentation_00000012              HEFT
  1949.867    2924.800  output_documentation_00000079              HEFT
306197576.812  306198551.745  bismark_summary_00000062                  BL

=== Processor 14 ===
     0.000     974.933  get_software_versions_00000166            BL
     0.000     974.933  get_software_versions_00000130             HEFT
   974.933    1949.867  output_documentation_00000151              HEFT
  1949.867    2924.800  output_documentation_00000043              HEFT
306197576.967  306198551.900  preseq_00000071                           BL

=== Processor 15 ===
     0.000     974.933  get_software_versions_00000130            BL
     0.000     974.933  get_software_versions_00000094             HEFT
   974.933    1949.867  output_documentation_00000091              HEFT
  1949.867    2924.800  output_documentation_00000019              HEFT
306197574.274  306198549.207  bismark_summary_00000074                  BL

=== Processor 16 ===
     0.000     974.933  get_software_versions_00000094            BL
     0.000     974.933  get_software_versions_00000154             HEFT
   974.933    1949.867  output_documentation_00000055              HEFT
  1949.867    2924.800  output_documentation_00000163              HEFT
306197574.429  306198549.362  preseq_00000155                           BL

=== Processor 17 ===
     0.000     974.933  get_software_versions_00000154            BL
     0.000     974.933  get_software_versions_00000106             HEFT
   974.933    1949.867  output_documentation_00000067              HEFT
  1949.867    2924.800  output_documentation_00000031              HEFT
306197574.584  306198549.518  bismark_summary_00000170                  BL

=== Processor 18 ===
     0.000  2916333.167  fastqc_00000164                           BL HEFT
30150849.946  30171223.079  bismark_methXtract_00000148                HEFT
32850755.129  32857391.996  qualimap_00000085                          HEFT
39038466.530  39045103.397  qualimap_00000011                          HEFT
39046110.712  39048451.312  bismark_report_00000090                    HEFT
45226183.967  45226671.433  preseq_00000007                            HEFT
261222673.266  261243046.400  bismark_methXtract_00000184               BL
283706300.004  283712936.870  qualimap_00000085                         BL
306197572.812  306198060.279  preseq_00000059                           BL
306198060.279  306198547.746  bismark_summary_00000098                  BL

=== Processor 19 ===
     0.000  2916333.167  fastqc_00000188                           BL HEFT
32850755.129  32857391.996  qualimap_00000133                          HEFT
39038466.795  39045103.662  qualimap_00000109                          HEFT
39046113.095  39048453.695  bismark_report_00000114                    HEFT
45226184.122  45226671.589  bismark_summary_00000009                   HEFT
261222673.422  261243046.555  bismark_methXtract_00000076               BL
283706300.314  283712937.181  qualimap_00000097                         BL
306197572.967  306198060.434  bismark_summary_00000146                  BL
306198060.434  306198547.901  preseq_00000179                           BL

=== Processor 20 ===
     0.000  2916333.167  fastqc_00000152                           BL HEFT
39038466.342  39045103.208  qualimap_00000013                          HEFT
39046110.712  39048451.312  bismark_report_00000150                    HEFT
45226183.967  45226671.433  bismark_summary_00000014                   HEFT
45227940.556  45228428.022  multiqc_00000149                           HEFT
261222672.836  261229309.702  qualimap_00000073                         BL
283706484.273  283713121.139  qualimap_00000037                         BL
306197573.123  306198060.589  bismark_summary_00000050                  BL
306198060.589  306198548.056  preseq_00000107                           BL

=== Processor 21 ===
     0.000  2916333.167  fastqc_00000176                           BL HEFT
30150849.360  30157486.226  qualimap_00000145                          HEFT
39038466.342  39045103.208  qualimap_00000121                          HEFT
39046108.630  39046596.097  preseq_00000059                            HEFT
45226183.967  45226671.433  preseq_00000047                            HEFT
283706301.473  283712938.339  qualimap_00000049                         BL
306197575.195  306198062.662  preseq_00000047                           BL
306198062.662  306198550.128  bismark_summary_00000158                  BL

=== Processor 22 ===
39038466.686  39045103.552  qualimap_00000157                          HEFT
39046108.786  39046596.252  bismark_summary_00000146                   HEFT
45226184.122  45226671.589  preseq_00000023                            HEFT
283706484.537  283713121.404  qualimap_00000181                         BL
306197573.278  306198060.745  preseq_00000191                           BL
306198060.745  306198548.211  bismark_summary_00000110                  BL

=== Processor 23 ===
39038470.952  39040811.552  bismark_report_00000054                    HEFT
39046108.941  39046596.407  bismark_summary_00000050                   HEFT
45226184.277  45226671.744  preseq_00000191                            HEFT
283706300.159  283712937.026  qualimap_00000109                         BL
306197575.350  306198062.817  bismark_summary_00000038                  BL
306198062.817  306198550.284  preseq_00000119                           BL

=== Processor 24 ===
     0.000     731.200  get_software_versions_00000190            BL
     0.000     731.200  get_software_versions_00000058             HEFT
39046111.168  39046842.368  preseq_00000095                            HEFT
45226184.122  45226915.322  bismark_summary_00000134                   HEFT
306197573.589  306198304.789  bismark_summary_00000182                  BL

=== Processor 25 ===
     0.000     731.200  get_software_versions_00000058            BL
     0.000     731.200  get_software_versions_00000005             HEFT
39046111.324  39046842.524  bismark_summary_00000110                   HEFT
45226184.277  45226915.477  bismark_summary_00000062                   HEFT
306197573.744  306198304.944  preseq_00000035                           BL

=== Processor 26 ===
     0.000     731.200  get_software_versions_00000005            BL
     0.000     731.200  get_software_versions_00000046             HEFT
39046111.479  39046842.679  preseq_00000119                            HEFT
45226184.433  45226915.633  preseq_00000071                            HEFT
306197575.506  306198306.706  preseq_00000167                           BL

=== Processor 27 ===
     0.000     731.200  get_software_versions_00000046            BL
     0.000     731.200  get_software_versions_00000178             HEFT
45226184.588  45226915.788  preseq_00000143                            HEFT
306197575.661  306198306.861  bismark_summary_00000086                  BL

=== Processor 28 ===
     0.000     731.200  get_software_versions_00000178            BL
     0.000     731.200  get_software_versions_00000022             HEFT
39046109.096  39046840.296  preseq_00000155                            HEFT
306197575.816  306198307.016  preseq_00000095                           BL

=== Processor 29 ===
     0.000     731.200  get_software_versions_00000190             HEFT
39046111.013  39046842.213  bismark_summary_00000086                   HEFT
45226183.967  45226915.167  preseq_00000179                            HEFT
283706300.004  283716255.304  qualimap_00000025                         BL
306197573.433  306198304.633  bismark_summary_00000026                  BL

=== Processor 30 ===
     0.000  8887618.950  trim_galore_00000060                      BL HEFT
8887618.950  17775237.900  trim_galore_00000156                       HEFT
17775237.900  23962950.925  bismark_align_00000147                     HEFT
23962950.925  30150663.950  bismark_align_00000051                     HEFT
31278147.830  187676987.936  trim_galore_00000156                      BL
39038283.211  39038466.011  bismark_deduplicate_00000129               HEFT
39038466.011  39046105.936  bismark_methXtract_00000124                HEFT
45226179.055  45228667.880  qualimap_00000181                          HEFT
45233818.650  45234001.450  bismark_summary_00000026                   HEFT
45234001.450  45234184.250  bismark_summary_00000158                   HEFT

In [36]:
fname= "./methylseq_1000_dynamic_starts_and_finishes.txt"
dyn_methylseq = pd.read_csv(fname, delimiter=' ', header=0, on_bad_lines="warn")
#print(dyn_methylseq.head())

# Pivot start/finish times
df_wide = (
    dyn_methylseq.pivot(index="vertex", columns="startOrFinish", values="time")
      .rename(columns={"start": "start_time", "finish": "end_time"})
      .reset_index()
)

# Add processor where start happens
df_wide = df_wide.merge(
    dyn_methylseq[dyn_methylseq["startOrFinish"] == "start"][["vertex", "proc"]], 
    on="vertex"
)


df_wide["duration"] = df_wide["end_time"] - df_wide["start_time"]
df_wide2 = df_wide.rename(columns={"proc": "processor",
                                 "duration": "duration"})

#print(df_wide.head())

fname= "./methylseq_1000_static.txt"
stat_methylseq = pd.read_csv(fname, delimiter=' ', header=0, on_bad_lines="warn")
stat_methylseq["duration"] = stat_methylseq["finish"] - stat_methylseq["start"]

stat_methylseq2 = stat_methylseq.rename(columns={"start": "start_time",
                                 "finish": "end_time"})

#print(stat_methylseq.head())


merged = df_wide2.merge(
    stat_methylseq2,
    on="vertex",
    suffixes=("_dyn", "_stat")
)
#print(merged.head())


# Rows where duration differs
diff = merged[ merged["duration_dyn"] != merged["duration_stat"] ]

# Sort by dynamic start time
diff = diff.sort_values(by="start_time_dyn")

res = diff[[
    "vertex",
    "start_time_dyn",
    "duration_dyn", "processor_dyn",
    "start_time_stat",
    "duration_stat", "processor_stat"
]]

#print(res)


#res.to_csv("dyn_and_stat_methylseq_compared.csv", index=False)

same_proc_diff_duration = merged[
    (merged["duration_dyn"] != merged["duration_stat"]) &
    (merged["processor_dyn"] == merged["processor_stat"])
]

# Sort by start time (dynamic start)
same_proc_diff_duration = same_proc_diff_duration.sort_values(by="start_time_dyn")

print(same_proc_diff_duration[[
    "vertex",
    "processor_dyn",
    "duration_dyn",
    "duration_stat",
    "start_time_dyn",
    "start_time_stat"
]])

same_proc_diff_duration[[
    "vertex",
    "processor_dyn",
    "duration_dyn",
    "duration_stat",
    "start_time_dyn",
    "start_time_stat"
]].to_csv("same_proc_diff_duration.csv", index=False)

                             vertex  processor_dyn  duration_dyn  \
990            trim_galore_00000984             31  8.887619e+06
566  get_software_versions_00000862             12  9.749333e+02
557  get_software_versions_00000754              1  1.462400e+03
989            trim_galore_00000972             34  8.887619e+06
480                 fastqc_00000824             19  2.916333e+06
553  get_software_versions_00000706             13  9.749333e+02
542  get_software_versions_00000574              0  1.462400e+03
700   output_documentation_00000475             13  9.749333e+02
691   output_documentation_00000367             16  9.749333e+02
515  get_software_versions_00000250              0  1.462400e+03
682   output_documentation_00000259              1  1.462400e+03
668   output_documentation_00000091              3  1.462400e+03
498  get_software_versions_00000046              2  1.462400e+03
986            trim_galore_00000936             30  8.887619e+06
417                 fastqc_00000068             18  2.916333e+06
975            trim_galore_00000804             33  8.887619e+06
974            trim_galore_00000792             30  8.887619e+06
973            trim_galore_00000780             35  8.887619e+06
964            trim_galore_00000672             32  8.887619e+06
963            trim_galore_00000660             33  8.887619e+06
937            trim_galore_00000336             31  8.887619e+06
71           bismark_align_00000891             31  6.187713e+06
60           bismark_align_00000759             31  6.187713e+06
318         bismark_report_00000870              6  8.777250e+02
54           bismark_align_00000687             31  6.187713e+06
144    bismark_deduplicate_00000777              9  1.828000e+02
397        bismark_summary_00000818             11  1.828000e+02
137    bismark_deduplicate_00000693             11  1.828000e+02
221     bismark_methXtract_00000700             11  7.639925e+03
44           bismark_align_00000567             30  6.187713e+06
135    bismark_deduplicate_00000669             11  1.828000e+02
633                multiqc_00000665              8  1.828000e+02
134    bismark_deduplicate_00000657             11  1.828000e+02
132    bismark_deduplicate_00000633             11  1.828000e+02
631                multiqc_00000641             10  1.828000e+02
39           bismark_align_00000507             33  6.187713e+06
128    bismark_deduplicate_00000585             11  1.828000e+02
126    bismark_deduplicate_00000561             11  1.828000e+02
36           bismark_align_00000471             31  6.187713e+06
119    bismark_deduplicate_00000477             11  1.828000e+02
97     bismark_deduplicate_00000213             11  1.828000e+02
595                multiqc_00000209             10  1.828000e+02
845               qualimap_00000217             10  2.488825e+03
96     bismark_deduplicate_00000201             11  1.828000e+02
593                multiqc_00000185              6  1.828000e+02
585                multiqc_00000089              9  1.828000e+02
835               qualimap_00000097             11  2.488825e+03

     duration_stat  start_time_dyn  start_time_stat
990   8.887619e+06    0.000000e+00     3.127815e+08
566   9.749333e+02    0.000000e+00     6.288702e+08
557   1.462400e+03    0.000000e+00     6.425687e+08
989   8.887619e+06    1.828000e+02     2.815033e+08
480   2.916333e+06    4.874667e+02     5.832666e+06
553   9.749333e+02    9.749333e+02     6.474399e+08
542   1.462400e+03    1.462400e+03     6.425657e+08
700   9.749333e+02    3.899733e+03     6.474477e+08
691   9.749333e+02    5.849600e+03     6.474438e+08
515   1.462400e+03    8.774400e+03     6.288754e+08
682   1.462400e+03    8.774400e+03     6.474443e+08
668   1.462400e+03    1.608640e+04     6.474414e+08
498   1.462400e+03    1.754880e+04     6.425438e+08
986   8.887619e+06    1.093808e+06     6.255630e+07
417   2.916333e+06    5.834129e+06     2.916333e+06
975   8.887619e+06    6.364992e+07     3.440596e+08
974   8.887619e+06    6.365010e+07     2.815033e+08
973   8.887619e+06    9.383444e+07     1.251126e+08
964   8.887619e+06    1.251128e+08     3.127815e+08
963   8.887619e+06    1.262062e+08     2.815033e+08
937   8.887619e+06    2.815033e+08     3.127815e+07
71    6.187713e+06    4.440818e+08     6.001741e+08
60    7.599914e+06    4.502695e+08     4.155035e+08
318   8.777250e+02    4.502798e+08     6.474370e+08
54    6.187713e+06    4.564572e+08     5.776904e+08
144   1.828000e+02    4.564572e+08     6.288454e+08
397   1.828000e+02    4.564675e+08     6.513370e+08
137   1.828000e+02    4.626449e+08     6.288456e+08
221   7.639925e+03    4.626453e+08     6.288458e+08
44    6.187713e+06    4.673196e+08     4.652723e+08
135   1.828000e+02    4.673196e+08     5.574946e+08
633   1.828000e+02    4.673283e+08     6.513372e+08
134   1.828000e+02    4.699263e+08     5.389109e+08
132   1.828000e+02    4.727533e+08     5.125273e+08
631   1.828000e+02    4.727618e+08     6.513372e+08
39    6.187713e+06    4.761140e+08     4.430788e+08
128   1.828000e+02    4.761140e+08     6.249455e+08
126   1.828000e+02    4.789408e+08     6.151563e+08
36    7.599918e+06    4.812081e+08     4.307034e+08
119   1.828000e+02    4.873958e+08     4.383033e+08
97    1.828000e+02    5.044459e+08     6.063618e+08
595   1.828000e+02    5.044546e+08     6.513378e+08
845   2.488825e+03    5.070527e+08     6.288609e+08
96    1.828000e+02    5.098794e+08     6.200509e+08
593   1.828000e+02    5.121553e+08     6.513378e+08
585   1.828000e+02    5.160760e+08     6.513372e+08
835   2.488825e+03    5.183347e+08     6.288609e+08

In [31]:
def print_by_processor(df, label):
    print(f"\n===== {label.upper()} =====\n")
    for proc in sorted(df["processor"].unique()):
        print(f"\n--- Processor {proc} ---")
        block = df[df["processor"] == proc].sort_values(by="start_time")

        for _, row in block.iterrows():
            print(
                f"{row['start_time']:12.3f} → {row['end_time']:12.3f}   "
                f"{row['vertex']}   (duration {row['duration']:.3f})"
            )

In [32]:
print_by_processor(stat_methylseq2, "STATIC")
print_by_processor(df_wide2, "DYNAMIC")

===== STATIC =====


--- Processor 0 ---
       0.000 →  8748999.500   fastqc_00000308   (duration 8748999.500)
624945664.788 → 625006784.188   bismark_methXtract_00000640   (duration 61119.400)
625006784.188 → 625026694.788   qualimap_00000841   (duration 19910.600)
625026694.788 → 625046605.388   qualimap_00000865   (duration 19910.600)
625046605.388 → 625066515.988   qualimap_00000757   (duration 19910.600)
628845589.940 → 628865500.540   qualimap_00000121   (duration 19910.600)
628865500.540 → 628872522.340   bismark_report_00000474   (duration 7021.800)
628872522.340 → 628873984.740   get_software_versions_00000154   (duration 1462.400)
628873984.740 → 628875447.140   bismark_summary_00000038   (duration 1462.400)
628875447.140 → 628876909.540   get_software_versions_00000250   (duration 1462.400)
637647749.580 → 637649211.980   preseq_00000131   (duration 1462.400)
637649211.980 → 637650674.380   get_software_versions_00000238   (duration 1462.400)
637650674.380 → 637652136.780   get_software_versions_00000934   (duration 1462.400)
637652136.780 → 637653599.180   bismark_summary_00000050   (duration 1462.400)
637653599.180 → 637655061.580   get_software_versions_00000022   (duration 1462.400)
642542337.914 → 642543800.314   bismark_summary_00000230   (duration 1462.400)
642543800.314 → 642545262.714   bismark_summary_00000446   (duration 1462.400)
642545262.714 → 642546725.114   bismark_summary_00000602   (duration 1462.400)
642546725.114 → 642548187.514   preseq_00000791   (duration 1462.400)
642548187.514 → 642549649.914   get_software_versions_00000718   (duration 1462.400)
642549649.914 → 642551112.314   get_software_versions_00000418   (duration 1462.400)
642551112.314 → 642552574.714   bismark_summary_00000806   (duration 1462.400)
642552574.714 → 642554037.114   bismark_summary_00000482   (duration 1462.400)
642554037.114 → 642555499.514   get_software_versions_00000430   (duration 1462.400)
642555499.514 → 642556961.914   get_software_versions_00000802   (duration 1462.400)
642556961.914 → 642558424.314   preseq_00000803   (duration 1462.400)
642558424.314 → 642559886.714   bismark_summary_00000518   (duration 1462.400)
642559886.714 → 642561349.114   preseq_00000575   (duration 1462.400)
642561349.114 → 642562811.514   get_software_versions_00000742   (duration 1462.400)
642562811.514 → 642564273.914   bismark_summary_00000566   (duration 1462.400)
642564273.914 → 642565736.314   bismark_summary_00000758   (duration 1462.400)
642565736.314 → 642567198.714   get_software_versions_00000574   (duration 1462.400)
642567198.714 → 642568661.114   bismark_summary_00000542   (duration 1462.400)
642568661.114 → 642570123.514   preseq_00000563   (duration 1462.400)
642570123.514 → 642571585.914   get_software_versions_00000550   (duration 1462.400)
642571585.914 → 642573048.314   preseq_00000503   (duration 1462.400)
642573048.314 → 642574510.714   bismark_summary_00000590   (duration 1462.400)
642574510.714 → 642575973.114   get_software_versions_00000490   (duration 1462.400)
642575973.114 → 642577435.514   get_software_versions_00000586   (duration 1462.400)
642577435.514 → 642578897.914   preseq_00000695   (duration 1462.400)
642578897.914 → 642580360.314   get_software_versions_00000502   (duration 1462.400)
647436973.540 → 647438435.940   preseq_00000587   (duration 1462.400)
647438435.940 → 647439898.340   preseq_00000347   (duration 1462.400)
647439898.340 → 647441360.740   bismark_summary_00000638   (duration 1462.400)
647441360.740 → 647442823.140   output_documentation_00000055   (duration 1462.400)
647442823.140 → 647444285.540   output_documentation_00000247   (duration 1462.400)
647444285.540 → 647445747.940   output_documentation_00000775   (duration 1462.400)
647445747.940 → 647447210.340   output_documentation_00000799   (duration 1462.400)

--- Processor 1 ---
       0.000 →  8748999.500   fastqc_00000428   (duration 8748999.500)
624945677.624 → 625006797.024   bismark_methXtract_00000028   (duration 61119.400)
625006797.024 → 625026707.624   qualimap_00000613   (duration 19910.600)
625026707.624 → 625046618.224   qualimap_00000541   (duration 19910.600)
628845590.049 → 628865500.649   qualimap_00000361   (duration 19910.600)
628865500.649 → 628872522.449   bismark_report_00000042   (duration 7021.800)
628872522.449 → 628873984.849   get_software_versions_00000214   (duration 1462.400)
628873984.849 → 628875447.249   get_software_versions_00000190   (duration 1462.400)
637647749.425 → 637649211.825   preseq_00000059   (duration 1462.400)
637649211.825 → 637650674.225   get_software_versions_00000130   (duration 1462.400)
637650674.225 → 637652136.625   bismark_summary_00000890   (duration 1462.400)
637652136.625 → 637653599.025   preseq_00000143   (duration 1462.400)
637653599.025 → 637655061.425   get_software_versions_00000142   (duration 1462.400)
642542337.759 → 642543800.159   bismark_summary_00000974   (duration 1462.400)
642543800.159 → 642545262.559   preseq_00000227   (duration 1462.400)
642545262.559 → 642546724.959   preseq_00000611   (duration 1462.400)
642546724.959 → 642548187.359   bismark_summary_00000470   (duration 1462.400)
642548187.359 → 642549649.759   preseq_00000599   (duration 1462.400)
642549649.759 → 642551112.159   preseq_00000815   (duration 1462.400)
642551112.159 → 642552574.559   bismark_summary_00000422   (duration 1462.400)
642552574.559 → 642554036.959   preseq_00000431   (duration 1462.400)
642554036.959 → 642555499.359   get_software_versions_00000622   (duration 1462.400)
642555499.359 → 642556961.759   preseq_00000623   (duration 1462.400)
642556961.759 → 642558424.159   get_software_versions_00000442   (duration 1462.400)
642558424.159 → 642559886.559   get_software_versions_00000538   (duration 1462.400)
642559886.559 → 642561348.959   preseq_00000527   (duration 1462.400)
642561348.959 → 642562811.359   preseq_00000767   (duration 1462.400)
642562811.359 → 642564273.759   get_software_versions_00000526   (duration 1462.400)
642564273.759 → 642565736.159   bismark_summary_00000530   (duration 1462.400)
642565736.159 → 642567198.559   preseq_00000539   (duration 1462.400)
642567198.559 → 642568660.959   get_software_versions_00000562   (duration 1462.400)
642568660.959 → 642570123.359   get_software_versions_00000754   (duration 1462.400)
642570123.359 → 642571585.759   preseq_00000551   (duration 1462.400)
642571585.759 → 642573048.159   bismark_summary_00000554   (duration 1462.400)
642573048.159 → 642574510.559   preseq_00000491   (duration 1462.400)
642574510.559 → 642575972.959   get_software_versions_00000778   (duration 1462.400)
642575972.959 → 642577435.359   bismark_summary_00000734   (duration 1462.400)
642577435.359 → 642578897.759   bismark_summary_00000494   (duration 1462.400)
647436973.385 → 647438435.785   preseq_00000311   (duration 1462.400)
647438435.785 → 647439898.185   bismark_summary_00000338   (duration 1462.400)
647439898.185 → 647441360.585   preseq_00000863   (duration 1462.400)
647441360.585 → 647442822.985   output_documentation_00000559   (duration 1462.400)
647442822.985 → 647444285.385   output_documentation_00000883   (duration 1462.400)
647444285.385 → 647445747.785   output_documentation_00000259   (duration 1462.400)
647445747.785 → 647447210.185   output_documentation_00000199   (duration 1462.400)

--- Processor 2 ---
       0.000 →  8748999.500   fastqc_00000320   (duration 8748999.500)
624945676.000 → 625006795.400   bismark_methXtract_00000016   (duration 61119.400)
625006795.400 → 625026706.000   qualimap_00000877   (duration 19910.600)
625026706.000 → 625046616.600   qualimap_00000301   (duration 19910.600)
625046616.600 → 625066527.200   qualimap_00000265   (duration 19910.600)
628845589.785 → 628865500.385   qualimap_00000109   (duration 19910.600)
628865500.385 → 628872522.185   bismark_report_00000762   (duration 7021.800)
628872522.185 → 628873984.585   get_software_versions_00000994   (duration 1462.400)
628873984.585 → 628875446.985   get_software_versions_00000178   (duration 1462.400)
628875446.985 → 628876909.385   preseq_00000191   (duration 1462.400)
637647749.270 → 637649211.670   bismark_summary_00000122   (duration 1462.400)
637649211.670 → 637650674.070   bismark_summary_00000914   (duration 1462.400)
637650674.070 → 637652136.470   bismark_summary_00000134   (duration 1462.400)
637652136.470 → 637653598.870   preseq_00000887   (duration 1462.400)
642542337.603 → 642543800.003   preseq_00000239   (duration 1462.400)
642543800.003 → 642545262.403   get_software_versions_00000046   (duration 1462.400)
642545262.403 → 642546724.803   get_software_versions_00000454   (duration 1462.400)
642546724.803 → 642548187.203   get_software_versions_00000598   (duration 1462.400)
642548187.203 → 642549649.603   bismark_summary_00000782   (duration 1462.400)
647436973.229 → 647438435.629   bismark_summary_00000626   (duration 1462.400)
647438435.629 → 647439898.029   bismark_summary_00000350   (duration 1462.400)
647439898.029 → 647441360.429   preseq_00000407   (duration 1462.400)
647441360.429 → 647442822.829   output_documentation_00000571   (duration 1462.400)
647442822.829 → 647444285.229   output_documentation_00000703   (duration 1462.400)
647444285.229 → 647445747.629   output_documentation_00000835   (duration 1462.400)
647445747.629 → 647447210.029   output_documentation_00000547   (duration 1462.400)

--- Processor 3 ---
       0.000 →  8748999.500   fastqc_00000416   (duration 8748999.500)
624945663.319 → 625006782.719   bismark_methXtract_00000604   (duration 61119.400)
625006782.719 → 625026693.319   qualimap_00000985   (duration 19910.600)
625026693.319 → 625046603.919   qualimap_00000853   (duration 19910.600)
628845589.520 → 628865500.120   qualimap_00000673   (duration 19910.600)
628865500.120 → 628872521.920   bismark_report_00000642   (duration 7021.800)
628872521.920 → 628873984.320   preseq_00000047   (duration 1462.400)
628873984.320 → 628875446.720   get_software_versions_00000034   (duration 1462.400)
628875446.720 → 628876909.120   bismark_summary_00000182   (duration 1462.400)
642542337.448 → 642543799.848   bismark_summary_00000986   (duration 1462.400)
642543799.848 → 642545262.248   bismark_summary_00000026   (duration 1462.400)
642545262.248 → 642546724.648   bismark_summary_00000794   (duration 1462.400)
642546724.648 → 642548187.048   get_software_versions_00000466   (duration 1462.400)
642548187.048 → 642549649.448   get_software_versions_00000478   (duration 1462.400)
647436973.074 → 647438435.474   preseq_00000419   (duration 1462.400)
647438435.474 → 647439897.874   get_software_versions_00000682   (duration 1462.400)
647439897.874 → 647441360.274   get_software_versions_00000634   (duration 1462.400)
647441360.274 → 647442822.674   output_documentation_00000091   (duration 1462.400)
647442822.674 → 647444285.074   output_documentation_00000067   (duration 1462.400)
647444285.074 → 647445747.474   output_documentation_00000355   (duration 1462.400)
647445747.474 → 647447209.874   output_documentation_00000943   (duration 1462.400)

--- Processor 4 ---
       0.000 →  8748999.500   fastqc_00000848   (duration 8748999.500)
624945663.164 → 625006782.564   bismark_methXtract_00000676   (duration 61119.400)
625006782.564 → 625026693.164   qualimap_00000529   (duration 19910.600)
625026693.164 → 625046603.764   qualimap_00000337   (duration 19910.600)
628845589.675 → 628865500.275   qualimap_00000601   (duration 19910.600)
628865500.275 → 628872522.075   bismark_report_00000102   (duration 7021.800)
628872522.075 → 628873984.475   get_software_versions_00000898   (duration 1462.400)
628873984.475 → 628875446.875   get_software_versions_00000910   (duration 1462.400)
642542337.293 → 642543799.693   preseq_00000983   (duration 1462.400)
642543799.693 → 642545262.093   get_software_versions_00000226   (duration 1462.400)
642545262.093 → 642546724.493   get_software_versions_00000610   (duration 1462.400)
642546724.493 → 642548186.893   bismark_summary_00000614   (duration 1462.400)
642548186.893 → 642549649.293   get_software_versions_00000730   (duration 1462.400)
647436972.919 → 647438435.319   preseq_00000635   (duration 1462.400)
647438435.319 → 647439897.719   preseq_00000383   (duration 1462.400)
647439897.719 → 647441360.119   get_software_versions_00000406   (duration 1462.400)
647441360.119 → 647442822.519   output_documentation_00000739   (duration 1462.400)
647442822.519 → 647444284.919   output_documentation_00000727   (duration 1462.400)
647444284.919 → 647445747.319   output_documentation_00000271   (duration 1462.400)
647445747.319 → 647447209.719   output_documentation_00000751   (duration 1462.400)

--- Processor 5 ---
       0.000 →  8748999.500   fastqc_00000356   (duration 8748999.500)
606362266.046 → 606423385.446   bismark_methXtract_00000340   (duration 61119.400)
624945661.695 → 625006781.095   bismark_methXtract_00000712   (duration 61119.400)
625006781.095 → 625026691.695   qualimap_00000157   (duration 19910.600)
625026691.695 → 625046602.295   qualimap_00000349   (duration 19910.600)
628845589.256 → 628865499.856   qualimap_00000073   (duration 19910.600)
628865499.856 → 628872521.656   bismark_report_00000534   (duration 7021.800)
628872521.656 → 628873984.056   get_software_versions_00000274   (duration 1462.400)
628873984.056 → 628875446.456   get_software_versions_00000202   (duration 1462.400)
637647749.114 → 637649211.514   preseq_00000923   (duration 1462.400)
642542337.138 → 642543799.538   bismark_summary_00000194   (duration 1462.400)
642543799.538 → 642545261.938   preseq_00000899   (duration 1462.400)
642545261.938 → 642546724.338   preseq_00000455   (duration 1462.400)
642546724.338 → 642548186.738   get_software_versions_00000790   (duration 1462.400)
642548186.738 → 642549649.138   preseq_00000479   (duration 1462.400)
647436972.764 → 647438435.164   bismark_summary_00000410   (duration 1462.400)
647438435.164 → 647439897.564   bismark_summary_00000650   (duration 1462.400)
647439897.564 → 647441359.964   preseq_00000719   (duration 1462.400)
647441359.964 → 647442822.364   output_documentation_00000012   (duration 1462.400)
647442822.364 → 647444284.764   output_documentation_00000655   (duration 1462.400)
647444284.764 → 647445747.164   output_documentation_00000343   (duration 1462.400)
647445747.164 → 647447209.564   output_documentation_00000115   (duration 1462.400)

--- Processor 6 ---
       0.000 →  1093624.938   fastqc_00000560   (duration 1093624.938)
 1093624.938 →  2187249.875   fastqc_00000548   (duration 1093624.938)
 2187249.875 →  3280874.812   fastqc_00000572   (duration 1093624.938)
 3280874.812 →  4374499.750   fastqc_00000344   (duration 1093624.938)
 4374499.750 →  5468124.688   fastqc_00000236   (duration 1093624.938)
 5468124.688 →  6561749.625   fastqc_00000956   (duration 1093624.938)
 6561749.625 →  7655374.562   fastqc_00000932   (duration 1093624.938)
 7655374.562 →  8748999.500   fastqc_00000392   (duration 1093624.938)
579978218.506 → 579978401.306   bismark_deduplicate_00000321   (duration 182.800)
597567256.271 → 597567439.071   bismark_deduplicate_00000237   (duration 182.800)
597567439.071 → 597567621.871   bismark_deduplicate_00000333   (duration 182.800)
606361776.085 → 606361958.885   bismark_deduplicate_00000573   (duration 182.800)
615156295.123 → 615156477.923   bismark_deduplicate_00000381   (duration 182.800)
620050885.684 → 620051068.484   bismark_deduplicate_00000789   (duration 182.800)
620051068.484 → 620051251.284   bismark_deduplicate_00000981   (duration 182.800)
624945476.556 → 624945659.356   bismark_deduplicate_00000933   (duration 182.800)
628845405.033 → 628845587.833   bismark_deduplicate_00000729   (duration 182.800)
628845589.421 → 628853229.346   bismark_methXtract_00000244   (duration 7639.925)
628853229.346 → 628860869.271   bismark_methXtract_00000052   (duration 7639.925)
628860869.271 → 628863358.096   qualimap_00000565   (duration 2488.825)
637640111.847 → 637640989.572   bismark_report_00000378   (duration 877.725)
642534712.095 → 642535589.820   bismark_report_00000234   (duration 877.725)
647436952.103 → 647437829.828   bismark_report_00000870   (duration 877.725)
647437829.828 → 647438707.553   bismark_report_00000150   (duration 877.725)
651329243.047 → 651330120.772   bismark_report_00000966   (duration 877.725)
651336857.016 → 651337039.816   bismark_summary_00000746   (duration 182.800)
651337039.816 → 651337222.616   multiqc_00000569   (duration 182.800)
651337222.616 → 651337405.416   multiqc_00000701   (duration 182.800)
651337405.416 → 651337588.216   multiqc_00000317   (duration 182.800)
651337588.216 → 651337771.016   multiqc_00000149   (duration 182.800)
651337771.016 → 651337953.816   multiqc_00000185   (duration 182.800)

--- Processor 7 ---
       0.000 →  1093624.938   fastqc_00000644   (duration 1093624.938)
 1093624.938 →  2187249.875   fastqc_00000536   (duration 1093624.938)
 2187249.875 →  3280874.812   fastqc_00000632   (duration 1093624.938)
 3280874.812 →  4374499.750   fastqc_00000524   (duration 1093624.938)
 4374499.750 →  5468124.688   fastqc_00000224   (duration 1093624.938)
 5468124.688 →  6561749.625   fastqc_00000080   (duration 1093624.938)
 6561749.625 →  7655374.562   fastqc_00000128   (duration 1093624.938)
 7655374.562 →  8748999.500   fastqc_00000332   (duration 1093624.938)
579978218.351 → 579978401.151   bismark_deduplicate_00000309   (duration 182.800)
583878146.827 → 583878329.627   bismark_deduplicate_00000273   (duration 182.800)
606361775.930 → 606361958.730   bismark_deduplicate_00000549   (duration 182.800)
615156294.968 → 615156477.768   bismark_deduplicate_00000489   (duration 182.800)
620050885.529 → 620051068.329   bismark_deduplicate_00000813   (duration 182.800)
624945476.401 → 624945659.201   bismark_deduplicate_00000909   (duration 182.800)
628845404.877 → 628845587.677   bismark_deduplicate_00000957   (duration 182.800)
628845587.677 → 628853227.602   bismark_methXtract_00000952   (duration 7639.925)
628853227.602 → 628860867.527   bismark_methXtract_00000976   (duration 7639.925)
628860867.527 → 628863356.352   qualimap_00000697   (duration 2488.825)
647436942.572 → 647437820.297   bismark_report_00000306   (duration 877.725)
651329231.133 → 651330108.858   bismark_report_00000270   (duration 877.725)
651336856.860 → 651337039.660   bismark_summary_00000722   (duration 182.800)
651337039.660 → 651337222.460   multiqc_00000101   (duration 182.800)
651337222.460 → 651337405.260   multiqc_00000965   (duration 182.800)
651337405.260 → 651337588.060   multiqc_00000341   (duration 182.800)
651337588.060 → 651337770.860   multiqc_00000497   (duration 182.800)
651337770.860 → 651337953.660   multiqc_00000557   (duration 182.800)

--- Processor 8 ---
       0.000 →  1093624.938   fastqc_00000656   (duration 1093624.938)
 1093624.938 →  2187249.875   fastqc_00000692   (duration 1093624.938)
 2187249.875 →  3280874.812   fastqc_00000704   (duration 1093624.938)
 3280874.812 →  4374499.750   fastqc_00000740   (duration 1093624.938)
 4374499.750 →  5468124.688   fastqc_00000140   (duration 1093624.938)
 5468124.688 →  6561749.625   fastqc_00000896   (duration 1093624.938)
 6561749.625 →  7655374.562   fastqc_00000116   (duration 1093624.938)
 7655374.562 →  8748999.500   fastqc_00000812   (duration 1093624.938)
448976373.763 → 448976556.563   bismark_deduplicate_00000405   (duration 182.800)
471460002.555 → 471460185.355   bismark_deduplicate_00000465   (duration 182.800)
507632741.412 → 507632924.212   bismark_deduplicate_00000453   (duration 182.800)
606361775.775 → 606361958.575   bismark_deduplicate_00000537   (duration 182.800)
615156294.812 → 615156477.612   bismark_deduplicate_00000165   (duration 182.800)
624945476.246 → 624945659.046   bismark_deduplicate_00000837   (duration 182.800)
624945659.046 → 624945841.846   bismark_deduplicate_00000945   (duration 182.800)

In [38]:
merged.to_csv("merged.csv")

In [39]:
import pandas as pd
import numpy as np

# === CONFIG: update file names as needed ===
merged_file = "merged.csv"          # your merged dynamic + static dataframe
# If merged.csv doesn't exist, you can use separate dynamic/static files:
dyn_file = "df_wide2.csv"
stat_file = "stat_methylseq2.csv"

# === 1. Load merged dataframe ===
try:
    df = pd.read_csv(merged_file)
    print(f"Loaded merged file: {merged_file}")
except FileNotFoundError:
    print(f"merged file not found, attempting to merge {dyn_file} + {stat_file}")
    dfdyn = pd.read_csv(dyn_file)
    dfstat = pd.read_csv(stat_file)
    # rename to canonical column names
    dfdyn = dfdyn.rename(columns={
        "start_time": "start_time_dyn",
        "end_time": "end_time_dyn",
        "duration": "duration_dyn",
        "proc": "processor_dyn",
        "processor": "processor_dyn"
    })
    dfstat = dfstat.rename(columns={
        "start_time": "start_time_stat",
        "end_time": "end_time_stat",
        "duration": "duration_stat",
        "processor": "processor_stat",
        "proc": "processor_stat"
    })
    df = dfdyn.merge(dfstat, on="vertex", suffixes=("_dyn","_stat"))
    print("Merged dynamic + static into dataframe.")

# === 2. Sanity check columns ===
needed = ["vertex",
          "start_time_dyn","end_time_dyn","duration_dyn","processor_dyn",
          "start_time_stat","end_time_stat","duration_stat","processor_stat"]
print("Column presence:")
for c in needed:
    print(f"  {c}: {'OK' if c in df.columns else 'MISSING'}")

# === 3. Convert numeric columns ===
for c in ["start_time_dyn","end_time_dyn","duration_dyn","start_time_stat","end_time_stat","duration_stat"]:
    if c in df.columns:
        df[c] = pd.to_numeric(df[c], errors="coerce")
for c in ["processor_dyn","processor_stat"]:
    if c in df.columns:
        df[c] = pd.to_numeric(df[c], errors="coerce", downcast='integer')

# === 4. Compute differences & flags ===
df["dur_diff_abs"] = df["duration_stat"] - df["duration_dyn"]
df["dur_ratio"] = df["duration_stat"] / df["duration_dyn"].replace(0,np.nan)
df["static_worse"] = df["dur_diff_abs"] > 0
df["same_processor"] = df["processor_dyn"] == df["processor_stat"]

# === 5. Summary ===
total = len(df)
total_worse = df["static_worse"].sum()
same_proc_worse = df[df["static_worse"] & df["same_processor"]].shape[0]
print(f"Total tasks: {total}; static worse: {total_worse} ({total_worse/total:.2%})")
print(f"Static worse on same processor: {same_proc_worse} ({same_proc_worse/total:.2%})")

# === 6. Per-processor aggregates ===
per_proc = []
for proc in sorted(df["processor_dyn"].dropna().unique()):
    g = df[df["processor_dyn"] == proc]
    n = len(g)
    n_worse = g["static_worse"].sum()
    median_ratio = g["dur_ratio"].median()
    median_abs = g["dur_diff_abs"].median()
    per_proc.append((proc, n, n_worse, median_ratio, median_abs))

per_proc_df = pd.DataFrame(per_proc, columns=["processor","count","count_static_worse","median_dur_ratio","median_abs_diff"])
per_proc_df = per_proc_df.sort_values("median_dur_ratio", ascending=False)
print("\nPer-processor summary (sorted by median ratio):")
display(per_proc_df)

# === 7. Top offenders ===
top_abs = df[df["dur_diff_abs"]>0].sort_values("dur_diff_abs", ascending=False)
top_rel = df[df["dur_ratio"]>1].sort_values("dur_ratio", ascending=False)

print("\nTop 20 tasks by absolute static>dynamic duration difference:")
display(top_abs.head(20)[["vertex","processor_dyn","processor_stat","duration_dyn","duration_stat","dur_diff_abs","dur_ratio"]])

print("\nTop 20 tasks by relative ratio (static/dynamic):")
display(top_rel.head(20)[["vertex","processor_dyn","processor_stat","duration_dyn","duration_stat","dur_ratio","dur_diff_abs"]])

# === 8. Optional: per-processor top 5 worst tasks ===
for proc in sorted(df["processor_dyn"].dropna().unique()):
    g = df[(df["processor_dyn"]==proc) & (df["dur_diff_abs"]>0)].sort_values("dur_diff_abs", ascending=False).head(5)
    if len(g):
        print(f"\nProcessor {int(proc)}: top {len(g)} static-worse tasks:")
        display(g[["vertex","duration_dyn","duration_stat","dur_diff_abs","dur_ratio"]])

Loaded merged file: merged.csv
Column presence:
  vertex: OK
  start_time_dyn: OK
  end_time_dyn: OK
  duration_dyn: OK
  processor_dyn: OK
  start_time_stat: OK
  end_time_stat: OK
  duration_stat: OK
  processor_stat: OK
Total tasks: 992; static worse: 604 (60.89%)
Static worse on same processor: 19 (1.92%)

Per-processor summary (sorted by median ratio):

    processor  count  count_static_worse  median_dur_ratio  median_abs_diff
10         10    204                 175          4.000000     7.921333e+02
8           8     65                  47          4.000000     5.484000e+02
9           9     85                  67          2.666667     7.921333e+02
7           7     24                  18          2.666667     5.484000e+02
6           6     26                  16          2.666667     3.046667e+02
18         18      6                   4          2.250000     6.093333e+02
27         27      5                   4          2.000000     7.312000e+02
21         21      6                   4          1.750000     3.656000e+02
28         28      6                   4          1.666667     4.874667e+02
26         26      4                   3          1.666667     4.874667e+02
20         20      5                   4          1.500000     4.874667e+02
14         14      8                   5          1.500000     4.874667e+02
29         29      5                   3          1.333333     2.437333e+02
25         25      5                   3          1.333333     2.437333e+02
12         12      7                   4          1.000000     6.596212e-07
11         11    188                 128          1.000000     1.192093e-07
17         17      8                   4          1.000000     1.827861e-07
24         24      5                   3          1.000000     4.768367e-08
35         35     39                  20          1.000000     3.725290e-09
30         30     43                  16          1.000000     0.000000e+00
34         34     33                  13          1.000000     0.000000e+00
33         33     33                  11          1.000000     0.000000e+00
32         32     32                  14          1.000000     0.000000e+00
31         31     31                  10          1.000000     0.000000e+00
0           0     13                   1          1.000000    -2.384377e-08
16         16      8                   3          1.000000    -2.940477e-07
15         15      7                   2          1.000000    -2.940531e-07
13         13      7                   3          1.000000    -2.940531e-07
23         23      6                   3          0.937500    -9.112322e+05
4           4     14                   0          0.833333    -2.437333e+02
19         19      4                   2          0.687500    -9.113541e+05
2           2     14                   3          0.666667    -4.874667e+02
3           3     14                   3          0.666667    -4.874667e+02
5           5     14                   2          0.666667    -4.874667e+02
1           1     14                   1          0.666667    -4.874667e+02
22         22      4                   1          0.375000    -1.822708e+06

Top 20 tasks by absolute static>dynamic duration difference:

,vertex,processor_dyn,processor_stat,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
482,fastqc_00000848,9,4,1.093625e+06,8.749000e+06,7.655375e+06,8.000000
438,fastqc_00000320,11,2,1.093625e+06,8.749000e+06,7.655375e+06,8.000000
437,fastqc_00000308,8,0,1.093625e+06,8.749000e+06,7.655375e+06,8.000000
447,fastqc_00000428,18,1,2.916333e+06,8.749000e+06,5.832666e+06,3.000000
446,fastqc_00000416,21,3,2.916333e+06,8.749000e+06,5.832666e+06,3.000000
432,fastqc_00000248,11,13,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
485,fastqc_00000884,8,12,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
435,fastqc_00000284,10,17,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
434,fastqc_00000272,9,15,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
433,fastqc_00000260,6,14,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
484,fastqc_00000872,7,16,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
425,fastqc_00000164,8,25,1.093625e+06,4.374500e+06,3.280875e+06,4.000000
488,fastqc_00000920,9,26,1.093625e+06,4.374500e+06,3.280875e+06,4.000000
427,fastqc_00000188,6,28,1.093625e+06,4.374500e+06,3.280875e+06,4.000000
426,fastqc_00000176,11,27,1.093625e+06,4.374500e+06,3.280875e+06,4.000000
424,fastqc_00000152,7,24,1.093625e+06,4.374500e+06,3.280875e+06,4.000000
441,fastqc_00000356,14,5,5.832666e+06,8.749000e+06,2.916333e+06,1.500000
454,fastqc_00000512,7,22,1.093625e+06,2.916333e+06,1.822708e+06,2.666667
436,fastqc_00000296,7,22,1.093625e+06,2.916333e+06,1.822708e+06,2.666667
483,fastqc_00000860,10,20,1.093625e+06,2.916333e+06,1.822708e+06,2.666667

Top 20 tasks by relative ratio (static/dynamic):

,vertex,processor_dyn,processor_stat,duration_dyn,duration_stat,dur_ratio,dur_diff_abs
781,preseq_00000455,10,5,182.800,1462.400000,8.0,1279.600000
809,preseq_00000791,10,0,182.800,1462.400000,8.0,1279.600000
372,bismark_summary_00000518,8,0,182.800,1462.400000,8.0,1279.600000
779,preseq_00000431,10,1,182.800,1462.400000,8.0,1279.600000
793,preseq_00000599,10,1,182.800,1462.400000,8.0,1279.600000
383,bismark_summary_00000650,10,5,182.800,1462.400000,8.0,1279.600000
370,bismark_summary_00000494,10,1,182.800,1462.400000,8.0,1279.600000
825,preseq_00000983,10,4,182.800,1462.400000,8.0,1279.600000
792,preseq_00000587,10,0,182.800,1462.400000,8.0,1279.600000
382,bismark_summary_00000638,10,0,182.800,1462.400000,8.0,1279.600000
340,bismark_summary_00000134,10,2,182.800,1462.400000,8.0,1279.600000
762,preseq_00000227,10,1,182.800,1462.400000,8.0,1279.600000
890,qualimap_00000757,6,0,2488.825,19910.600001,8.0,17421.775001
883,qualimap_00000673,10,3,2488.825,19910.600001,8.0,17421.775001
900,qualimap_00000877,6,2,2488.825,19910.600001,8.0,17421.775001
837,qualimap_00000121,8,0,2488.825,19910.600000,8.0,17421.775000
878,qualimap_00000613,8,1,2488.825,19910.600000,8.0,17421.775000
871,qualimap_00000529,10,4,2488.825,19910.600000,8.0,17421.775000
909,qualimap_00000985,9,3,2488.825,19910.600000,8.0,17421.775000
833,qualimap_00000073,11,5,2488.825,19910.600000,8.0,17421.775000

Processor 0: top 1 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
497,get_software_versions_00000034,1462.4,1462.4,9.536575e-08,1.0

Processor 1: top 1 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
535,get_software_versions_00000490,1462.4,1462.4,9.536780e-08,1.0

Processor 2: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
661,output_documentation_00000012,1462.4,1462.4,9.536961e-08,1.0
507,get_software_versions_00000154,1462.4,1462.4,9.536780e-08,1.0
498,get_software_versions_00000046,1462.4,1462.4,9.536575e-08,1.0

Processor 3: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
677,output_documentation_00000199,1462.4,1462.4,9.536780e-08,1.0
683,output_documentation_00000271,1462.4,1462.4,9.536780e-08,1.0
665,output_documentation_00000055,1462.4,1462.4,9.536575e-08,1.0

Processor 5: top 2 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
690,output_documentation_00000355,1462.4,1462.4,9.536780e-08,1.0
559,get_software_versions_00000778,1462.4,1462.4,9.536734e-08,1.0

Processor 6: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
433,fastqc_00000260,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
427,fastqc_00000188,1.093625e+06,4.374500e+06,3.280875e+06,4.000000
890,qualimap_00000757,2.488825e+03,1.991060e+04,1.742178e+04,8.000000
900,qualimap_00000877,2.488825e+03,1.991060e+04,1.742178e+04,8.000000
240,bismark_methXtract_00000928,7.639925e+03,2.037313e+04,1.273321e+04,2.666667

Processor 7: top 5 static-worse tasks:

              vertex  duration_dyn  duration_stat  dur_diff_abs  dur_ratio
484  fastqc_00000872  1.093625e+06   5.832666e+06  4.739041e+06   5.333333
424  fastqc_00000152  1.093625e+06   4.374500e+06  3.280875e+06   4.000000
454  fastqc_00000512  1.093625e+06   2.916333e+06  1.822708e+06   2.666667
436  fastqc_00000296  1.093625e+06   2.916333e+06  1.822708e+06   2.666667
472  fastqc_00000728  1.093625e+06   2.916333e+06  1.822708e+06   2.666667

Processor 8: top 5 static-worse tasks:

                vertex  duration_dyn  duration_stat  dur_diff_abs  dur_ratio
437    fastqc_00000308  1.093625e+06   8.749000e+06  7.655375e+06   8.000000
485    fastqc_00000884  1.093625e+06   5.832666e+06  4.739041e+06   5.333333
425    fastqc_00000164  1.093625e+06   4.374500e+06  3.280875e+06   4.000000
849  qualimap_00000265  2.488825e+03   1.991060e+04  1.742178e+04   8.000000
852  qualimap_00000301  2.488825e+03   1.991060e+04  1.742178e+04   8.000000

Processor 9: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
482,fastqc_00000848,1.093625e+06,8.749000e+06,7.655375e+06,8.000000
434,fastqc_00000272,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
488,fastqc_00000920,1.093625e+06,4.374500e+06,3.280875e+06,4.000000
216,bismark_methXtract_00000640,7.639925e+03,6.111940e+04,5.347947e+04,8.000000
179,bismark_methXtract_00000196,7.639925e+03,4.074627e+04,3.310634e+04,5.333333

Processor 10: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
435,fastqc_00000284,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
483,fastqc_00000860,1.093625e+06,2.916333e+06,1.822708e+06,2.666667
238,bismark_methXtract_00000904,7.639925e+03,4.074627e+04,3.310634e+04,5.333333
232,bismark_methXtract_00000832,7.639925e+03,3.055970e+04,2.291978e+04,4.000000
230,bismark_methXtract_00000808,7.639925e+03,3.055970e+04,2.291977e+04,4.000000

Processor 11: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
438,fastqc_00000320,1.093625e+06,8.749000e+06,7.655375e+06,8.000000
432,fastqc_00000248,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
426,fastqc_00000176,1.093625e+06,4.374500e+06,3.280875e+06,4.000000
493,fastqc_00000980,1.093625e+06,2.916333e+06,1.822708e+06,2.666667
222,bismark_methXtract_00000712,7.639925e+03,6.111940e+04,5.347948e+04,8.000000

Processor 12: top 4 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
534,get_software_versions_00000478,974.933333,1462.400000,4.874667e+02,1.5
540,get_software_versions_00000550,974.933333,1462.400000,4.874667e+02,1.5
531,get_software_versions_00000442,974.933333,1462.400000,4.874667e+02,1.5
720,output_documentation_00000715,974.933333,974.933334,6.596212e-07,1.0

Processor 13: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
706,output_documentation_00000547,974.933333,1462.400000,4.874667e+02,1.5
547,get_software_versions_00000634,974.933333,1462.400000,4.874667e+02,1.5
697,output_documentation_00000439,974.933333,974.933334,6.596272e-07,1.0

Processor 14: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
441,fastqc_00000356,5.832666e+06,8748999.5,2.916333e+06,1.5
539,get_software_versions_00000538,9.749333e+02,1462.4,4.874667e+02,1.5
530,get_software_versions_00000430,9.749333e+02,1462.4,4.874667e+02,1.5
719,output_documentation_00000703,9.749333e+02,1462.4,4.874667e+02,1.5
533,get_software_versions_00000466,9.749333e+02,1462.4,4.874667e+02,1.5

Processor 15: top 2 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
546,get_software_versions_00000622,974.933333,1462.400000,4.874667e+02,1.5
699,output_documentation_00000463,974.933333,974.933334,6.596182e-07,1.0

Processor 16: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
538,get_software_versions_00000526,974.933333,1462.4,487.466667,1.5
529,get_software_versions_00000418,974.933333,1462.4,487.466667,1.5
532,get_software_versions_00000454,974.933333,1462.4,487.466667,1.5

Processor 17: top 4 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
545,get_software_versions_00000610,974.933333,1462.400000,4.874667e+02,1.5
730,output_documentation_00000835,974.933333,1462.400000,4.874667e+02,1.5
551,get_software_versions_00000682,974.933333,1462.400000,4.874667e+02,1.5
698,output_documentation_00000451,974.933333,974.933334,6.596182e-07,1.0

Processor 18: top 4 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
447,fastqc_00000428,2.916333e+06,8748999.5,5.832666e+06,3.0
572,get_software_versions_00000934,4.874667e+02,1462.4,9.749333e+02,3.0
561,get_software_versions_00000802,4.874667e+02,1462.4,9.749333e+02,3.0
563,get_software_versions_00000826,4.874667e+02,731.2,2.437333e+02,1.5

Processor 19: top 2 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
738,output_documentation_00000931,4.874667e+02,9.749333e+02,4.874667e+02,2.0
480,fastqc_00000824,2.916333e+06,2.916333e+06,6.053597e-09,1.0

Processor 20: top 4 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
448,fastqc_00000440,2.916333e+06,4.374500e+06,1.458167e+06,1.5
571,get_software_versions_00000922,4.874667e+02,9.749333e+02,4.874667e+02,2.0
729,output_documentation_00000823,4.874667e+02,9.749333e+02,4.874667e+02,2.0
478,fastqc_00000800,2.916333e+06,2.916333e+06,2.793968e-09,1.0

Processor 21: top 4 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
446,fastqc_00000416,2.916333e+06,8.749000e+06,5.832666e+06,3.0
727,output_documentation_00000799,4.874667e+02,1.462400e+03,9.749333e+02,3.0
737,output_documentation_00000919,4.874667e+02,9.749333e+02,4.874667e+02,2.0
562,get_software_versions_00000814,4.874667e+02,7.312000e+02,2.437333e+02,1.5

Processor 22: top 1 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
570,get_software_versions_00000910,487.466667,1462.4,974.933333,3.0

Processor 23: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
560,get_software_versions_00000790,487.466667,1462.400000,974.933333,3.0
736,output_documentation_00000907,487.466667,974.933333,487.466666,2.0
728,output_documentation_00000811,487.466667,731.200000,243.733333,1.5

Processor 24: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
556,get_software_versions_00000742,731.2,1462.4,7.312000e+02,2.0
550,get_software_versions_00000670,731.2,731.2,4.768390e-08,1.0
735,output_documentation_00000895,731.2,731.2,4.768367e-08,1.0

Processor 25: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
722,output_documentation_00000739,731.2,1462.400000,731.200000,2.000000
716,output_documentation_00000667,731.2,974.933333,243.733333,1.333333
568,get_software_versions_00000886,731.2,974.933333,243.733333,1.333333

Processor 26: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
555,get_software_versions_00000730,731.2,1462.400000,731.200000,2.000000
734,output_documentation_00000883,731.2,1462.400000,731.200000,2.000000
549,get_software_versions_00000658,731.2,974.933333,243.733333,1.333333

Processor 27: top 4 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
715,output_documentation_00000655,731.2,1462.400000,731.200000,2.000000
721,output_documentation_00000727,731.2,1462.400000,731.200000,2.000000
708,output_documentation_00000571,731.2,1462.400000,731.200000,2.000000
567,get_software_versions_00000874,731.2,974.933333,243.733333,1.333333

Processor 28: top 4 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
541,get_software_versions_00000562,731.2,1462.400000,731.200000,2.000000
707,output_documentation_00000559,731.2,1462.400000,731.200000,2.000000
554,get_software_versions_00000718,731.2,1462.400000,731.200000,2.000000
733,output_documentation_00000871,731.2,974.933334,243.733334,1.333333

Processor 29: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
569,get_software_versions_00000898,731.2,1462.400000,731.200000,2.000000
717,output_documentation_00000679,731.2,974.933333,243.733333,1.333333
726,output_documentation_00000787,731.2,974.933333,243.733333,1.333333

Processor 30: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
169,bismark_methXtract_00000076,7639.925,40746.266667,33106.341667,5.333333
168,bismark_methXtract_00000064,7639.925,30559.700000,22919.775000,4.000000
171,bismark_methXtract_00000100,7639.925,30559.700000,22919.775000,4.000000
172,bismark_methXtract_00000112,7639.925,30559.700000,22919.775000,4.000000
254,bismark_report_00000102,877.725,7021.800000,6144.075000,8.000000

Processor 31: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
36,bismark_align_00000471,6187713.025,7.599918e+06,1.412205e+06,1.228227
60,bismark_align_00000759,6187713.025,7.599914e+06,1.412201e+06,1.228227
164,bismark_methXtract_00000016,7639.925,6.111940e+04,5.347947e+04,8.000000
54,bismark_align_00000687,6187713.025,6.187713e+06,1.192093e-07,1.000000
972,trim_galore_00000768,8887618.950,8.887619e+06,8.940697e-08,1.000000

Processor 32: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
34,bismark_align_00000447,6187713.025,7.599916e+06,1.412203e+06,1.228227
66,bismark_align_00000831,6187713.025,7.599916e+06,1.412203e+06,1.228227
64,bismark_align_00000807,6187713.025,7.599914e+06,1.412201e+06,1.228227
828,qualimap_00000013,2488.825,9.955300e+03,7.466475e+03,4.000000
250,bismark_report_00000054,877.725,3.510900e+03,2.633175e+03,4.000000

Processor 33: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
494,fastqc_00000992,1.093625e+06,2.916333e+06,1.822708e+06,2.666667
33,bismark_align_00000435,6.187713e+06,7.599916e+06,1.412203e+06,1.228227
63,bismark_align_00000795,6.187713e+06,7.599916e+06,1.412203e+06,1.228227
23,bismark_align_00000291,6.187713e+06,7.599916e+06,1.412203e+06,1.228227
163,bismark_methXtract_00000010,7.639925e+03,2.037313e+04,1.273321e+04,2.666667

Processor 34: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
25,bismark_align_00000315,6187713.025,7.599918e+06,1.412205e+06,1.228227
69,bismark_align_00000867,6187713.025,7.599914e+06,1.412201e+06,1.228227
41,bismark_align_00000531,6187713.025,7.599914e+06,1.412201e+06,1.228227
165,bismark_methXtract_00000028,7639.925,6.111940e+04,5.347947e+04,8.000000
248,bismark_report_00000030,877.725,2.340600e+03,1.462875e+03,2.666667

Processor 35: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
61,bismark_align_00000771,6187713.025,7.599918e+06,1.412205e+06,1.228227
37,bismark_align_00000483,6187713.025,7.599914e+06,1.412201e+06,1.228227
22,bismark_align_00000267,6187713.025,7.599914e+06,1.412201e+06,1.228227
831,qualimap_00000049,2488.825,6.636867e+03,4.148042e+03,2.666667
829,qualimap_00000025,2488.825,6.636867e+03,4.148042e+03,2.666667

In [54]:
fname= "./dynamic_results_atacseq_200.txt"
dyn_atacseq = pd.read_csv(fname, delimiter=' ', header=0, on_bad_lines="warn")
#print(dyn_atacseq.head())

# Pivot start/finish times
df_wide = (
    dyn_atacseq.pivot(index="vertex", columns="startOrFinish", values="time")
      .rename(columns={"start": "start_time", "finish": "end_time"})
      .reset_index()
)

# Add processor where start happens
df_wide = df_wide.merge(
    dyn_atacseq[dyn_atacseq["startOrFinish"] == "start"][["vertex", "proc"]], 
    on="vertex"
)


df_wide["duration"] = df_wide["end_time"] - df_wide["start_time"]
df_wide2 = df_wide.rename(columns={"proc": "processor",
                                 "duration": "duration"})

#print(df_wide.head())
df_wide2.to_csv("dynamic_schedule_atac_200.csv")

fname= "./static_results_atacseq_200.txt"
stat_atacseq = pd.read_csv(fname, delimiter=' ', header=0, on_bad_lines="warn")

stat_atacseq["duration"] = stat_atacseq["finish"] - stat_atacseq["start"]

stat_atacseq2 = stat_atacseq.rename(columns={"start": "start_time",                
                                 "finish": "end_time", "proc": "processor"})



#print(stat_methylseq.head())
stat_atacseq2.to_csv("static_schedule_atac_200.csv")

merged = df_wide2.merge(
    stat_atacseq2,
    on="vertex",
    suffixes=("_dyn", "_stat")
)
print(merged.head())


# Rows where duration differs
diff = merged[ merged["duration_dyn"] != merged["duration_stat"] ]

# Sort by dynamic start time
diff = diff.sort_values(by="start_time_dyn")

res = diff[[
    "vertex",
    "start_time_dyn",
    "duration_dyn", "processor_dyn",
    "start_time_stat",
    "duration_stat", "processor_stat"
]]

#print(res)


#res.to_csv("dyn_and_stat_ATAC200_compared.csv", index=False)

same_proc_diff_duration = merged[
    (merged["duration_dyn"] != merged["duration_stat"]) &
    (merged["processor_dyn"] == merged["processor_stat"])
]

# Sort by start time (dynamic start)
same_proc_diff_duration = same_proc_diff_duration.sort_values(by="start_time_dyn")

print(same_proc_diff_duration[[
    "vertex",
    "processor_dyn",
    "duration_dyn",
    "duration_stat",
    "start_time_dyn",
    "start_time_stat"
]])

same_proc_diff_duration[[
    "vertex",
    "processor_dyn",
    "duration_dyn",
    "duration_stat",
    "start_time_dyn",
    "start_time_stat"
]].to_csv("same_proc_diff_durationATAC.csv", index=False)
merged.to_csv("mergedAtacseq.csv")

               vertex  end_time_dyn  start_time_dyn  processor_dyn  \
0  BWA_INDEX_00000005   154726.3000          0.0000             22
1  BWA_INDEX_00000069   116044.7250      58022.3625              8
2  BWA_INDEX_00000108   116044.7250      58022.3625             32
3  BWA_INDEX_00000147    58022.3625          0.0000              9
4  BWA_INDEX_00000186    58022.3625          0.0000             32

   duration_dyn  start_time_stat  end_time_stat  processor_stat  duration_stat
0   154726.3000              0.0     58022.3625              11     58022.3625
1    58022.3625              0.0     58022.3625               8     58022.3625
2    58022.3625              0.0     58022.3625              10     58022.3625
3    58022.3625              0.0     58022.3625              30     58022.3625
4    58022.3625              0.0     58022.3625               9     58022.3625
                                   vertex  processor_dyn  duration_dyn  \
11                  CHECK_DESIGN_00000075             32  6.045661e+06
176                     SORT_BAM_00000064             32  2.748968e+05
51                MERGED_LIB_BAM_00000068             32  9.214023e+05
56         MERGED_LIB_BAM_FILTER_00000049             32  6.793800e+05
106    MERGED_LIB_PICARD_METRICS_00000066             32  2.025881e+05
111   MERGED_LIB_PLOTFINGERPRINT_00000067             32  5.802236e+04
88   MERGED_LIB_CONSENSUS_DESEQ2_00000118             19  1.547263e+05
21                           IGV_00000043             32  5.802236e+04
48        MERGED_LIB_ATAQV_MKARV_00000124             33  5.802236e+04
172                      MULTIQC_00000104             31  5.802236e+04
84   MERGED_LIB_CONSENSUS_COUNTS_00000167             34  5.802236e+04

     duration_stat  start_time_dyn  start_time_stat
11    6.045661e+06    1.162652e+05     0.000000e+00
176   2.748968e+05    8.323935e+06     7.966976e+06
51    9.214023e+05    8.598831e+06     8.241873e+06
56    6.793800e+05    9.520234e+06     9.163275e+06
106   2.025881e+05    1.090880e+07     2.651213e+07
111   5.802236e+04    1.111139e+07     3.885979e+07
88    1.547263e+05    2.429011e+07     3.564666e+07
21    5.802236e+04    2.462222e+07     4.063729e+07
48    5.802236e+04    2.585854e+07     4.436816e+07
172   5.802236e+04    2.647130e+07     4.430665e+07
84    5.802236e+04    2.742937e+07     3.394040e+07

In [53]:
import pandas as pd
import numpy as np

# === CONFIG: update file names as needed ===
merged_file = "merged.csv"          # your merged dynamic + static dataframe
# If merged.csv doesn't exist, you can use separate dynamic/static files:
dyn_file = "df_wide2.csv"
stat_file = "stat_methylseq2.csv"

# === 1. Load merged dataframe ===
try:
    df = pd.read_csv(merged_file)
    print(f"Loaded merged file: {merged_file}")
except FileNotFoundError:
    print(f"merged file not found, attempting to merge {dyn_file} + {stat_file}")
    dfdyn = pd.read_csv(dyn_file)
    dfstat = pd.read_csv(stat_file)
    # rename to canonical column names
    dfdyn = dfdyn.rename(columns={
        "start_time": "start_time_dyn",
        "end_time": "end_time_dyn",
        "duration": "duration_dyn",
        "proc": "processor_dyn",
        "processor": "processor_dyn"
    })
    dfstat = dfstat.rename(columns={
        "start_time": "start_time_stat",
        "end_time": "end_time_stat",
        "duration": "duration_stat",
        "processor": "processor_stat",
        "proc": "processor_stat"
    })
    df = dfdyn.merge(dfstat, on="vertex", suffixes=("_dyn","_stat"))
    print("Merged dynamic + static into dataframe.")

# === 2. Sanity check columns ===
needed = ["vertex",
          "start_time_dyn","end_time_dyn","duration_dyn","processor_dyn",
          "start_time_stat","end_time_stat","duration_stat","processor_stat"]
print("Column presence:")
for c in needed:
    print(f"  {c}: {'OK' if c in df.columns else 'MISSING'}")

# === 3. Convert numeric columns ===
for c in ["start_time_dyn","end_time_dyn","duration_dyn","start_time_stat","end_time_stat","duration_stat"]:
    if c in df.columns:
        df[c] = pd.to_numeric(df[c], errors="coerce")
for c in ["processor_dyn","processor_stat"]:
    if c in df.columns:
        df[c] = pd.to_numeric(df[c], errors="coerce", downcast='integer')

# === 4. Compute differences & flags ===
df["dur_diff_abs"] = df["duration_stat"] - df["duration_dyn"]
df["dur_ratio"] = df["duration_stat"] / df["duration_dyn"].replace(0,np.nan)
df["static_worse"] = df["dur_diff_abs"] > 0
df["same_processor"] = df["processor_dyn"] == df["processor_stat"]

# === 5. Summary ===
total = len(df)
total_worse = df["static_worse"].sum()
same_proc_worse = df[df["static_worse"] & df["same_processor"]].shape[0]
print(f"Total tasks: {total}; static worse: {total_worse} ({total_worse/total:.2%})")
print(f"Static worse on same processor: {same_proc_worse} ({same_proc_worse/total:.2%})")

# === 6. Per-processor aggregates ===
per_proc = []
for proc in sorted(df["processor_dyn"].dropna().unique()):
    g = df[df["processor_dyn"] == proc]
    n = len(g)
    n_worse = g["static_worse"].sum()
    median_ratio = g["dur_ratio"].median()
    median_abs = g["dur_diff_abs"].median()
    per_proc.append((proc, n, n_worse, median_ratio, median_abs))

per_proc_df = pd.DataFrame(per_proc, columns=["processor","count","count_static_worse","median_dur_ratio","median_abs_diff"])
per_proc_df = per_proc_df.sort_values("median_dur_ratio", ascending=False)
print("\nPer-processor summary (sorted by median ratio):")
display(per_proc_df)

# === 7. Top offenders ===
top_abs = df[df["dur_diff_abs"]>0].sort_values("dur_diff_abs", ascending=False)
top_rel = df[df["dur_ratio"]>1].sort_values("dur_ratio", ascending=False)

print("\nTop 20 tasks by absolute static>dynamic duration difference:")
display(top_abs.head(20)[["vertex","processor_dyn","processor_stat","duration_dyn","duration_stat","dur_diff_abs","dur_ratio"]])

print("\nTop 20 tasks by relative ratio (static/dynamic):")
display(top_rel.head(20)[["vertex","processor_dyn","processor_stat","duration_dyn","duration_stat","dur_ratio","dur_diff_abs"]])

# === 8. Optional: per-processor top 5 worst tasks ===
for proc in sorted(df["processor_dyn"].dropna().unique()):
    g = df[(df["processor_dyn"]==proc) & (df["dur_diff_abs"]>0)].sort_values("dur_diff_abs", ascending=False).head(5)
    if len(g):
        print(f"\nProcessor {int(proc)}: top {len(g)} static-worse tasks:")
        display(g[["vertex","duration_dyn","duration_stat","dur_diff_abs","dur_ratio"]])

Loaded merged file: merged.csv
Column presence:
  vertex: OK
  start_time_dyn: OK
  end_time_dyn: OK
  duration_dyn: OK
  processor_dyn: OK
  start_time_stat: OK
  end_time_stat: OK
  duration_stat: OK
  processor_stat: OK
Total tasks: 992; static worse: 604 (60.89%)
Static worse on same processor: 19 (1.92%)

Per-processor summary (sorted by median ratio):

    processor  count  count_static_worse  median_dur_ratio  median_abs_diff
10         10    204                 175          4.000000     7.921333e+02
8           8     65                  47          4.000000     5.484000e+02
9           9     85                  67          2.666667     7.921333e+02
7           7     24                  18          2.666667     5.484000e+02
6           6     26                  16          2.666667     3.046667e+02
18         18      6                   4          2.250000     6.093333e+02
27         27      5                   4          2.000000     7.312000e+02
21         21      6                   4          1.750000     3.656000e+02
28         28      6                   4          1.666667     4.874667e+02
26         26      4                   3          1.666667     4.874667e+02
20         20      5                   4          1.500000     4.874667e+02
14         14      8                   5          1.500000     4.874667e+02
29         29      5                   3          1.333333     2.437333e+02
25         25      5                   3          1.333333     2.437333e+02
12         12      7                   4          1.000000     6.596212e-07
11         11    188                 128          1.000000     1.192093e-07
17         17      8                   4          1.000000     1.827861e-07
24         24      5                   3          1.000000     4.768367e-08
35         35     39                  20          1.000000     3.725290e-09
30         30     43                  16          1.000000     0.000000e+00
34         34     33                  13          1.000000     0.000000e+00
33         33     33                  11          1.000000     0.000000e+00
32         32     32                  14          1.000000     0.000000e+00
31         31     31                  10          1.000000     0.000000e+00
0           0     13                   1          1.000000    -2.384377e-08
16         16      8                   3          1.000000    -2.940477e-07
15         15      7                   2          1.000000    -2.940531e-07
13         13      7                   3          1.000000    -2.940531e-07
23         23      6                   3          0.937500    -9.112322e+05
4           4     14                   0          0.833333    -2.437333e+02
19         19      4                   2          0.687500    -9.113541e+05
2           2     14                   3          0.666667    -4.874667e+02
3           3     14                   3          0.666667    -4.874667e+02
5           5     14                   2          0.666667    -4.874667e+02
1           1     14                   1          0.666667    -4.874667e+02
22         22      4                   1          0.375000    -1.822708e+06

Top 20 tasks by absolute static>dynamic duration difference:

,vertex,processor_dyn,processor_stat,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
482,fastqc_00000848,9,4,1.093625e+06,8.749000e+06,7.655375e+06,8.000000
438,fastqc_00000320,11,2,1.093625e+06,8.749000e+06,7.655375e+06,8.000000
437,fastqc_00000308,8,0,1.093625e+06,8.749000e+06,7.655375e+06,8.000000
447,fastqc_00000428,18,1,2.916333e+06,8.749000e+06,5.832666e+06,3.000000
446,fastqc_00000416,21,3,2.916333e+06,8.749000e+06,5.832666e+06,3.000000
432,fastqc_00000248,11,13,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
485,fastqc_00000884,8,12,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
435,fastqc_00000284,10,17,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
434,fastqc_00000272,9,15,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
433,fastqc_00000260,6,14,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
484,fastqc_00000872,7,16,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
425,fastqc_00000164,8,25,1.093625e+06,4.374500e+06,3.280875e+06,4.000000
488,fastqc_00000920,9,26,1.093625e+06,4.374500e+06,3.280875e+06,4.000000
427,fastqc_00000188,6,28,1.093625e+06,4.374500e+06,3.280875e+06,4.000000
426,fastqc_00000176,11,27,1.093625e+06,4.374500e+06,3.280875e+06,4.000000
424,fastqc_00000152,7,24,1.093625e+06,4.374500e+06,3.280875e+06,4.000000
441,fastqc_00000356,14,5,5.832666e+06,8.749000e+06,2.916333e+06,1.500000
454,fastqc_00000512,7,22,1.093625e+06,2.916333e+06,1.822708e+06,2.666667
436,fastqc_00000296,7,22,1.093625e+06,2.916333e+06,1.822708e+06,2.666667
483,fastqc_00000860,10,20,1.093625e+06,2.916333e+06,1.822708e+06,2.666667

Top 20 tasks by relative ratio (static/dynamic):

,vertex,processor_dyn,processor_stat,duration_dyn,duration_stat,dur_ratio,dur_diff_abs
781,preseq_00000455,10,5,182.800,1462.400000,8.0,1279.600000
809,preseq_00000791,10,0,182.800,1462.400000,8.0,1279.600000
372,bismark_summary_00000518,8,0,182.800,1462.400000,8.0,1279.600000
779,preseq_00000431,10,1,182.800,1462.400000,8.0,1279.600000
793,preseq_00000599,10,1,182.800,1462.400000,8.0,1279.600000
383,bismark_summary_00000650,10,5,182.800,1462.400000,8.0,1279.600000
370,bismark_summary_00000494,10,1,182.800,1462.400000,8.0,1279.600000
825,preseq_00000983,10,4,182.800,1462.400000,8.0,1279.600000
792,preseq_00000587,10,0,182.800,1462.400000,8.0,1279.600000
382,bismark_summary_00000638,10,0,182.800,1462.400000,8.0,1279.600000
340,bismark_summary_00000134,10,2,182.800,1462.400000,8.0,1279.600000
762,preseq_00000227,10,1,182.800,1462.400000,8.0,1279.600000
890,qualimap_00000757,6,0,2488.825,19910.600001,8.0,17421.775001
883,qualimap_00000673,10,3,2488.825,19910.600001,8.0,17421.775001
900,qualimap_00000877,6,2,2488.825,19910.600001,8.0,17421.775001
837,qualimap_00000121,8,0,2488.825,19910.600000,8.0,17421.775000
878,qualimap_00000613,8,1,2488.825,19910.600000,8.0,17421.775000
871,qualimap_00000529,10,4,2488.825,19910.600000,8.0,17421.775000
909,qualimap_00000985,9,3,2488.825,19910.600000,8.0,17421.775000
833,qualimap_00000073,11,5,2488.825,19910.600000,8.0,17421.775000

Processor 0: top 1 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
497,get_software_versions_00000034,1462.4,1462.4,9.536575e-08,1.0

Processor 1: top 1 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
535,get_software_versions_00000490,1462.4,1462.4,9.536780e-08,1.0

Processor 2: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
661,output_documentation_00000012,1462.4,1462.4,9.536961e-08,1.0
507,get_software_versions_00000154,1462.4,1462.4,9.536780e-08,1.0
498,get_software_versions_00000046,1462.4,1462.4,9.536575e-08,1.0

Processor 3: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
677,output_documentation_00000199,1462.4,1462.4,9.536780e-08,1.0
683,output_documentation_00000271,1462.4,1462.4,9.536780e-08,1.0
665,output_documentation_00000055,1462.4,1462.4,9.536575e-08,1.0

Processor 5: top 2 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
690,output_documentation_00000355,1462.4,1462.4,9.536780e-08,1.0
559,get_software_versions_00000778,1462.4,1462.4,9.536734e-08,1.0

Processor 6: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
433,fastqc_00000260,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
427,fastqc_00000188,1.093625e+06,4.374500e+06,3.280875e+06,4.000000
890,qualimap_00000757,2.488825e+03,1.991060e+04,1.742178e+04,8.000000
900,qualimap_00000877,2.488825e+03,1.991060e+04,1.742178e+04,8.000000
240,bismark_methXtract_00000928,7.639925e+03,2.037313e+04,1.273321e+04,2.666667

Processor 7: top 5 static-worse tasks:

              vertex  duration_dyn  duration_stat  dur_diff_abs  dur_ratio
484  fastqc_00000872  1.093625e+06   5.832666e+06  4.739041e+06   5.333333
424  fastqc_00000152  1.093625e+06   4.374500e+06  3.280875e+06   4.000000
454  fastqc_00000512  1.093625e+06   2.916333e+06  1.822708e+06   2.666667
436  fastqc_00000296  1.093625e+06   2.916333e+06  1.822708e+06   2.666667
472  fastqc_00000728  1.093625e+06   2.916333e+06  1.822708e+06   2.666667

Processor 8: top 5 static-worse tasks:

                vertex  duration_dyn  duration_stat  dur_diff_abs  dur_ratio
437    fastqc_00000308  1.093625e+06   8.749000e+06  7.655375e+06   8.000000
485    fastqc_00000884  1.093625e+06   5.832666e+06  4.739041e+06   5.333333
425    fastqc_00000164  1.093625e+06   4.374500e+06  3.280875e+06   4.000000
849  qualimap_00000265  2.488825e+03   1.991060e+04  1.742178e+04   8.000000
852  qualimap_00000301  2.488825e+03   1.991060e+04  1.742178e+04   8.000000

Processor 9: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
482,fastqc_00000848,1.093625e+06,8.749000e+06,7.655375e+06,8.000000
434,fastqc_00000272,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
488,fastqc_00000920,1.093625e+06,4.374500e+06,3.280875e+06,4.000000
216,bismark_methXtract_00000640,7.639925e+03,6.111940e+04,5.347947e+04,8.000000
179,bismark_methXtract_00000196,7.639925e+03,4.074627e+04,3.310634e+04,5.333333

Processor 10: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
435,fastqc_00000284,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
483,fastqc_00000860,1.093625e+06,2.916333e+06,1.822708e+06,2.666667
238,bismark_methXtract_00000904,7.639925e+03,4.074627e+04,3.310634e+04,5.333333
232,bismark_methXtract_00000832,7.639925e+03,3.055970e+04,2.291978e+04,4.000000
230,bismark_methXtract_00000808,7.639925e+03,3.055970e+04,2.291977e+04,4.000000

Processor 11: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
438,fastqc_00000320,1.093625e+06,8.749000e+06,7.655375e+06,8.000000
432,fastqc_00000248,1.093625e+06,5.832666e+06,4.739041e+06,5.333333
426,fastqc_00000176,1.093625e+06,4.374500e+06,3.280875e+06,4.000000
493,fastqc_00000980,1.093625e+06,2.916333e+06,1.822708e+06,2.666667
222,bismark_methXtract_00000712,7.639925e+03,6.111940e+04,5.347948e+04,8.000000

Processor 12: top 4 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
534,get_software_versions_00000478,974.933333,1462.400000,4.874667e+02,1.5
540,get_software_versions_00000550,974.933333,1462.400000,4.874667e+02,1.5
531,get_software_versions_00000442,974.933333,1462.400000,4.874667e+02,1.5
720,output_documentation_00000715,974.933333,974.933334,6.596212e-07,1.0

Processor 13: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
706,output_documentation_00000547,974.933333,1462.400000,4.874667e+02,1.5
547,get_software_versions_00000634,974.933333,1462.400000,4.874667e+02,1.5
697,output_documentation_00000439,974.933333,974.933334,6.596272e-07,1.0

Processor 14: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
441,fastqc_00000356,5.832666e+06,8748999.5,2.916333e+06,1.5
539,get_software_versions_00000538,9.749333e+02,1462.4,4.874667e+02,1.5
530,get_software_versions_00000430,9.749333e+02,1462.4,4.874667e+02,1.5
719,output_documentation_00000703,9.749333e+02,1462.4,4.874667e+02,1.5
533,get_software_versions_00000466,9.749333e+02,1462.4,4.874667e+02,1.5

Processor 15: top 2 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
546,get_software_versions_00000622,974.933333,1462.400000,4.874667e+02,1.5
699,output_documentation_00000463,974.933333,974.933334,6.596182e-07,1.0

Processor 16: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
538,get_software_versions_00000526,974.933333,1462.4,487.466667,1.5
529,get_software_versions_00000418,974.933333,1462.4,487.466667,1.5
532,get_software_versions_00000454,974.933333,1462.4,487.466667,1.5

Processor 17: top 4 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
545,get_software_versions_00000610,974.933333,1462.400000,4.874667e+02,1.5
730,output_documentation_00000835,974.933333,1462.400000,4.874667e+02,1.5
551,get_software_versions_00000682,974.933333,1462.400000,4.874667e+02,1.5
698,output_documentation_00000451,974.933333,974.933334,6.596182e-07,1.0

Processor 18: top 4 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
447,fastqc_00000428,2.916333e+06,8748999.5,5.832666e+06,3.0
572,get_software_versions_00000934,4.874667e+02,1462.4,9.749333e+02,3.0
561,get_software_versions_00000802,4.874667e+02,1462.4,9.749333e+02,3.0
563,get_software_versions_00000826,4.874667e+02,731.2,2.437333e+02,1.5

Processor 19: top 2 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
738,output_documentation_00000931,4.874667e+02,9.749333e+02,4.874667e+02,2.0
480,fastqc_00000824,2.916333e+06,2.916333e+06,6.053597e-09,1.0

Processor 20: top 4 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
448,fastqc_00000440,2.916333e+06,4.374500e+06,1.458167e+06,1.5
571,get_software_versions_00000922,4.874667e+02,9.749333e+02,4.874667e+02,2.0
729,output_documentation_00000823,4.874667e+02,9.749333e+02,4.874667e+02,2.0
478,fastqc_00000800,2.916333e+06,2.916333e+06,2.793968e-09,1.0

Processor 21: top 4 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
446,fastqc_00000416,2.916333e+06,8.749000e+06,5.832666e+06,3.0
727,output_documentation_00000799,4.874667e+02,1.462400e+03,9.749333e+02,3.0
737,output_documentation_00000919,4.874667e+02,9.749333e+02,4.874667e+02,2.0
562,get_software_versions_00000814,4.874667e+02,7.312000e+02,2.437333e+02,1.5

Processor 22: top 1 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
570,get_software_versions_00000910,487.466667,1462.4,974.933333,3.0

Processor 23: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
560,get_software_versions_00000790,487.466667,1462.400000,974.933333,3.0
736,output_documentation_00000907,487.466667,974.933333,487.466666,2.0
728,output_documentation_00000811,487.466667,731.200000,243.733333,1.5

Processor 24: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
556,get_software_versions_00000742,731.2,1462.4,7.312000e+02,2.0
550,get_software_versions_00000670,731.2,731.2,4.768390e-08,1.0
735,output_documentation_00000895,731.2,731.2,4.768367e-08,1.0

Processor 25: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
722,output_documentation_00000739,731.2,1462.400000,731.200000,2.000000
716,output_documentation_00000667,731.2,974.933333,243.733333,1.333333
568,get_software_versions_00000886,731.2,974.933333,243.733333,1.333333

Processor 26: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
555,get_software_versions_00000730,731.2,1462.400000,731.200000,2.000000
734,output_documentation_00000883,731.2,1462.400000,731.200000,2.000000
549,get_software_versions_00000658,731.2,974.933333,243.733333,1.333333

Processor 27: top 4 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
715,output_documentation_00000655,731.2,1462.400000,731.200000,2.000000
721,output_documentation_00000727,731.2,1462.400000,731.200000,2.000000
708,output_documentation_00000571,731.2,1462.400000,731.200000,2.000000
567,get_software_versions_00000874,731.2,974.933333,243.733333,1.333333

Processor 28: top 4 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
541,get_software_versions_00000562,731.2,1462.400000,731.200000,2.000000
707,output_documentation_00000559,731.2,1462.400000,731.200000,2.000000
554,get_software_versions_00000718,731.2,1462.400000,731.200000,2.000000
733,output_documentation_00000871,731.2,974.933334,243.733334,1.333333

Processor 29: top 3 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
569,get_software_versions_00000898,731.2,1462.400000,731.200000,2.000000
717,output_documentation_00000679,731.2,974.933333,243.733333,1.333333
726,output_documentation_00000787,731.2,974.933333,243.733333,1.333333

Processor 30: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
169,bismark_methXtract_00000076,7639.925,40746.266667,33106.341667,5.333333
168,bismark_methXtract_00000064,7639.925,30559.700000,22919.775000,4.000000
171,bismark_methXtract_00000100,7639.925,30559.700000,22919.775000,4.000000
172,bismark_methXtract_00000112,7639.925,30559.700000,22919.775000,4.000000
254,bismark_report_00000102,877.725,7021.800000,6144.075000,8.000000

Processor 31: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
36,bismark_align_00000471,6187713.025,7.599918e+06,1.412205e+06,1.228227
60,bismark_align_00000759,6187713.025,7.599914e+06,1.412201e+06,1.228227
164,bismark_methXtract_00000016,7639.925,6.111940e+04,5.347947e+04,8.000000
54,bismark_align_00000687,6187713.025,6.187713e+06,1.192093e-07,1.000000
972,trim_galore_00000768,8887618.950,8.887619e+06,8.940697e-08,1.000000

Processor 32: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
34,bismark_align_00000447,6187713.025,7.599916e+06,1.412203e+06,1.228227
66,bismark_align_00000831,6187713.025,7.599916e+06,1.412203e+06,1.228227
64,bismark_align_00000807,6187713.025,7.599914e+06,1.412201e+06,1.228227
828,qualimap_00000013,2488.825,9.955300e+03,7.466475e+03,4.000000
250,bismark_report_00000054,877.725,3.510900e+03,2.633175e+03,4.000000

Processor 33: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
494,fastqc_00000992,1.093625e+06,2.916333e+06,1.822708e+06,2.666667
33,bismark_align_00000435,6.187713e+06,7.599916e+06,1.412203e+06,1.228227
63,bismark_align_00000795,6.187713e+06,7.599916e+06,1.412203e+06,1.228227
23,bismark_align_00000291,6.187713e+06,7.599916e+06,1.412203e+06,1.228227
163,bismark_methXtract_00000010,7.639925e+03,2.037313e+04,1.273321e+04,2.666667

Processor 34: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
25,bismark_align_00000315,6187713.025,7.599918e+06,1.412205e+06,1.228227
69,bismark_align_00000867,6187713.025,7.599914e+06,1.412201e+06,1.228227
41,bismark_align_00000531,6187713.025,7.599914e+06,1.412201e+06,1.228227
165,bismark_methXtract_00000028,7639.925,6.111940e+04,5.347947e+04,8.000000
248,bismark_report_00000030,877.725,2.340600e+03,1.462875e+03,2.666667

Processor 35: top 5 static-worse tasks:

,vertex,duration_dyn,duration_stat,dur_diff_abs,dur_ratio
61,bismark_align_00000771,6187713.025,7.599918e+06,1.412205e+06,1.228227
37,bismark_align_00000483,6187713.025,7.599914e+06,1.412201e+06,1.228227
22,bismark_align_00000267,6187713.025,7.599914e+06,1.412201e+06,1.228227
831,qualimap_00000049,2488.825,6.636867e+03,4.148042e+03,2.666667
829,qualimap_00000025,2488.825,6.636867e+03,4.148042e+03,2.666667

In [4]:
path = "./results-26-12/merged/*.txt"
#print(path)

patterndevs = r'^(BASE|A\d+)-(ndev)'

dfs26=read_dfs(path,patterndevs, 2)

path = "./results-18-12/merged/*.txt"
#print(path)

patterndevs = r'^(BASE|A\d+)-(ndev)'

dfs18=read_dfs(path,patterndevs, 2)
#print(dfs18)

{('A1', 'ndev'):      algo_nr              wf_name     inp_size    dur_alg1          ms_1  \
0          1    atacseq_30000.dot  14091675276   27.869306  2.208628e+09
1          1    chipseq_15000.dot  41366257414   10.057338  3.608378e+09
2          1  methylseq_15000.dot   6761426956  108.373746  5.701489e+08
3          1    atacseq_15000.dot   3908761308   13.129148  3.323044e+08
4          1                eager  19075314980    0.034273  7.610497e+06
..       ...                  ...          ...         ...           ...
259        1                eager  19132169434    0.034361  7.614341e+06
260        1  methylseq_10000.dot  17027257018   29.445993  1.142015e+09
261        1        eager_200.dot   8330435694    0.126112  4.959908e+06
262        1              atacseq  11809629756    0.009802  3.111618e+06
263        1    chipseq_10000.dot   4807293396    7.670184  3.880994e+08

          ms_perc   dur_alg2          ms_2
0    2.324460e+09  46.129945  2.324460e+09
1    3.471522e+09   3.988488  3.471522e+09
2    5.465778e+08  75.588718  5.465778e+08
3    3.683984e+08  14.383803  3.683984e+08
4    6.621707e+06   0.004666  6.621707e+06
..            ...        ...           ...
259  6.624688e+06   0.004657  6.624688e+06
260  7.790729e+08  24.455373  7.790729e+08
261  3.205377e+06   0.017195  3.205377e+06
262  2.831476e+06   0.001090  2.831476e+06
263  4.275515e+08   7.379186  4.275515e+08

[264 rows x 8 columns], ('A2', 'ndev'):      algo_nr              wf_name     inp_size    dur_alg1          ms_1  \
0          2    atacseq_30000.dot  14091675276   31.477878  2.210782e+09
1          2    chipseq_15000.dot  41366257414   10.766891  3.603170e+09
2          2  methylseq_15000.dot   6761426956  111.156245  5.701489e+08
3          2    atacseq_15000.dot   3908761308   13.553760  3.320068e+08
4          2                eager  19075314980    0.038365  7.610497e+06
..       ...                  ...          ...         ...           ...
259        2                eager  19132169434    0.038254  7.614341e+06
260        2  methylseq_10000.dot  17027257018   29.565511  1.142015e+09
261        2        eager_200.dot   8330435694    0.144370  4.959908e+06
262        2              atacseq  11809629756    0.009758  3.111618e+06
263        2    chipseq_10000.dot   4807293396    7.029781  3.867152e+08

          ms_perc   dur_alg2          ms_2
0    2.311846e+09  35.138750  2.311846e+09
1    3.547902e+09   4.796195  3.547902e+09
2    5.465778e+08  77.710879  5.465778e+08
3    3.374041e+08  14.177936  3.374041e+08
4    6.621707e+06   0.006111  6.621707e+06
..            ...        ...           ...
259  6.624688e+06   0.006085  6.624688e+06
260  7.790729e+08  24.421233  7.790729e+08
261  3.176845e+06   0.020896  3.176845e+06
262  2.826262e+06   0.001050  2.826262e+06
263  3.854847e+08   7.165789  3.854847e+08

[264 rows x 8 columns], ('A3', 'ndev'):      algo_nr              wf_name     inp_size     dur_alg1          ms_1  \
0          3    atacseq_30000.dot  14091675276  2170.664409  2.211349e+09
1          3    chipseq_15000.dot  41366257414   378.100196  3.608029e+09
2          3  methylseq_15000.dot   6761426956   476.504093  5.701486e+08
3          3    atacseq_15000.dot   3908761308   370.917595  3.305401e+08
4          3                eager  19075314980     0.037267  7.604206e+06
..       ...                  ...          ...          ...           ...
259        3                eager  19132169434     0.037015  7.607661e+06
260        3  methylseq_10000.dot  17027257018   146.976856  1.142015e+09
261        3        eager_200.dot   8330435694     0.141033  5.166300e+06
262        3              atacseq  11809629756     0.010795  3.137488e+06
263        3    chipseq_10000.dot   4807293396    89.029698  3.853055e+08

          ms_perc     dur_alg2          ms_2
0    2.372926e+09  3234.067289  2.372926e+09
1    4.893512e+09   473.058566  4.893512e+09
2    4.503956e+08   496.801479  4.503956e+08
3    3.760129e+08   500.222452  3.760129e+08
4    6.628001e+06     0.005746  6.628001e+06
..            ...          ...           ...
259  6.631370e+06     0.005766  6.631370e+06
260  6.047543e+08   149.893158  6.047543e+08
261  4.914918e+06     0.020903  4.914918e+06
262  2.775182e+06     0.001497  2.775182e+06
263  3.223597e+08   140.935314  3.223597e+08

[264 rows x 8 columns], ('BASE', 'ndev'):      algo_nr              wf_name     inp_size    dur_alg1          ms_1  \
0          0    atacseq_30000.dot  14091675276   28.620346  2.208628e+09
1          0    chipseq_15000.dot  41366257414   10.135267  3.608378e+09
2          0  methylseq_15000.dot   6761426956  156.798077  5.701489e+08
3          0    atacseq_15000.dot   3908761308   13.721100  3.323044e+08
4          0                eager  19075314980    0.034531  7.610497e+06
..       ...                  ...          ...         ...           ...
259        0                eager  19132169434    0.034513  7.614341e+06
260        0  methylseq_10000.dot  17027257018   32.051966  1.142015e+09
261        0        eager_200.dot   8330435694    0.130119  4.959908e+06
262        0              atacseq  11809629756    0.009755  3.111618e+06
263        0    chipseq_10000.dot   4807293396    7.784349  3.880994e+08

          ms_perc    dur_alg2          ms_2
0    7.574613e+08  567.618196  4.914243e+09
1    1.280105e+09   59.783597  6.244074e+09
2    2.230730e+08  273.968279  7.948886e+08
3    1.030118e+08   54.243140  8.628367e+08
4    5.660097e+06    0.008689  7.309766e+06
..            ...         ...           ...
259  5.645709e+06    0.008747  7.331329e+06
260  3.001326e+08   40.601832  1.714336e+09
261  3.178859e+06    0.031517  3.851851e+06
262  2.658573e+06    0.001943  2.891796e+06
263  8.890805e+07   21.842036  9.333676e+08

[264 rows x 8 columns]}

In [23]:

def compare_equal_2dates(dfs1, dfs2):
  
    comparison_results = {}

    for key in dfs1.keys():
        if key not in dfs2:
            print(f"Key {key} missing in dfs26, skipping")
            continue

        df1 = dfs1[key]
        df2 = dfs2[key]

        # merge by workflow and input size
        merged = df1.merge(
            df2,
            on=["wf_name", "inp_size"],
            suffixes=("_1", "_2")
        )
       # print(merged)

        # compare equality
        merged["equal_ms_1"] = merged["ms_1_1"] == merged["ms_1_2"]
        merged["equal_ms_2"] = merged["ms_2_1"] == merged["ms_2_2"]

        # store for later inspection
        comparison_results[key] = merged

        # quick summary
        print(f"\nResults for {key}:")
        print("ms_1 equal:", merged["equal_ms_1"].mean(), "fraction of cases")
        print("ms_2 equal:", merged["equal_ms_2"].mean(), "fraction of cases")

In [9]:
path = "./results-26-12/merged/*.txt"
#print(path)

patterndevs = r'^(BASE|A\d+)-(ndev)'

dfs26=read_dfs(path,patterndevs, 2)

path = "./results-18-12/merged/*.txt"
#print(path)

patterndevs = r'^(BASE|A\d+)-(ndev)'

dfs18=read_dfs(path,patterndevs, 2)
#print(dfs18)

compare_equal_2dates(dfs18, dfs26)

Results for ('A1', 'ndev'):
ms_1 equal: 1.0 fraction of cases
ms_2 equal: 1.0 fraction of cases

Results for ('A2', 'ndev'):
ms_1 equal: 1.0 fraction of cases
ms_2 equal: 1.0 fraction of cases

Results for ('A3', 'ndev'):
ms_1 equal: 1.0 fraction of cases
ms_2 equal: 1.0 fraction of cases

Results for ('BASE', 'ndev'):
ms_1 equal: 1.0 fraction of cases
ms_2 equal: 1.0 fraction of cases

In [24]:
path = "./results-26-12/merged/*.txt"
#print(path)

patterndevs = r'^(BASE|A\d+)-(bdev)'

dfs26=read_dfs(path,patterndevs, 2)
#print(dfs26)

path = "./results-18-12/merged/*.txt"
#print(path)

patterndevs = r'^(BASE|A\d+)-(50dev)'

dfs18=read_dfs(path,patterndevs, 2)
dfs18 = {
    (k1, "bdev" if k2 == "50dev" else k2): df
    for (k1, k2), df in dfs18.items()
}
#print(dfs18.keys())

compare_equal_2dates(dfs18, dfs26)

Results for ('BASE', 'bdev'):
ms_1 equal: 0.0 fraction of cases
ms_2 equal: 0.0 fraction of cases

Results for ('A1', 'bdev'):
ms_1 equal: 0.0 fraction of cases
ms_2 equal: 0.0 fraction of cases

Results for ('A2', 'bdev'):
ms_1 equal: 0.0 fraction of cases
ms_2 equal: 0.0 fraction of cases

Results for ('A3', 'bdev'):
ms_1 equal: 0.0 fraction of cases
ms_2 equal: 0.0 fraction of cases

In [16]:
out_stat= '''
CHECK_DESIGN_00000001 0 30 0 1676.96166666667 1676.96166666667
CHECK_DESIGN_00000049 0 31 0 1676.96166666667 1676.96166666667
CHECK_DESIGN_00000074 0 32 0 1676.96166666667 1676.96166666667
CHECK_DESIGN_00000099 0 33 0 1676.96166666667 1676.96166666667
CHECK_DESIGN_00000124 0 34 0 1676.96166666667 1676.96166666667
CHECK_DESIGN_00000149 0 35 0 1676.96166666667 1676.96166666667
CHECK_DESIGN_00000174 0 30 1676.96166666667 3353.92333333333 1676.96166666667
TRIMGALORE_00000002 0 30 3353.92333333333 7865.3925 4511.46916666667
TRIMGALORE_00000030 0 31 1676.96166666667 6188.43083333333 4511.46916666667
TRIMGALORE_00000055 0 32 1676.96166666667 6188.43083333333 4511.46916666667
TRIMGALORE_00000080 0 33 1676.96166666667 6188.43083333333 4511.46916666667
TRIMGALORE_00000105 0 34 1676.96166666667 6188.43083333333 4511.46916666667
TRIMGALORE_00000130 0 35 1676.96166666667 6188.43083333333 4511.46916666667
TRIMGALORE_00000155 0 30 7865.3925 12376.8616666667 4511.46916666667
BWA_MEM_00000009 1 30 12376.8616666667 614541.05117905 602164.189512383
BWA_MEM_00000038 0 31 6188.43083333333 23942.1258333333 17753.695
BWA_MEM_00000063 0 32 6188.43083333333 23942.1258333333 17753.695
BWA_MEM_00000088 0 33 6188.43083333333 23942.1258333333 17753.695
BWA_MEM_00000113 0 34 6188.43083333333 23942.1258333333 17753.695
BWA_MEM_00000138 0 35 6188.43083333333 23942.1258333333 17753.695
BWA_MEM_00000163 1 30 614541.05117905 715066.86300286 100525.81182381
SORT_BAM_00000011 0 30 715066.86300286 717761.574669527 2694.71166666667
SORT_BAM_00000040 0 31 23942.1258333333 26636.8375 2694.71166666667
SORT_BAM_00000065 0 32 23942.1258333333 26636.8375 2694.71166666667
SORT_BAM_00000090 0 33 23942.1258333333 26636.8375 2694.71166666667
SORT_BAM_00000115 0 34 23942.1258333333 26636.8375 2694.71166666667
SORT_BAM_00000140 0 35 23942.1258333333 26636.8375 2694.71166666667
SORT_BAM_00000165 0 30 717761.574669527 720456.286336193 2694.71166666667
MERGED_BAM_00000012 1 30 720456.286336193 731192.467893983 10736.1815577899
MERGED_BAM_00000046 0 31 26636.8375 36401.6779166667 9764.84041666667
MERGED_BAM_00000071 0 32 26636.8375 36401.6779166667 9764.84041666667
MERGED_BAM_00000096 0 33 26636.8375 36401.6779166667 9764.84041666667
MERGED_BAM_00000121 0 34 26636.8375 36401.6779166667 9764.84041666667
MERGED_BAM_00000146 0 35 26636.8375 36401.6779166667 9764.84041666667
MERGED_BAM_00000171 1 30 731192.467893983 819163.924288843 87971.4563948598
MAKE_GENOME_FILTER_00000020 0 6 0 419.240416666667 419.240416666667
MAKE_GENOME_FILTER_00000031 0 7 0 419.240416666667 419.240416666667
MAKE_GENOME_FILTER_00000056 0 8 0 419.240416666667 419.240416666667
MAKE_GENOME_FILTER_00000081 0 9 0 419.240416666667 419.240416666667
MAKE_GENOME_FILTER_00000106 0 10 0 419.240416666667 419.240416666667
MAKE_GENOME_FILTER_00000131 0 11 0 419.240416666667 419.240416666667
MAKE_GENOME_FILTER_00000156 0 6 419.240416666667 838.480833333333 419.240416666667
MERGED_BAM_FILTER_00000005 2 30 956967.916531918 962017.080698584 5049.16416666668
MERGED_BAM_FILTER_00000037 0 31 36401.6779166667 41450.8420833333 5049.16416666667
MERGED_BAM_FILTER_00000062 0 32 36401.6779166667 41450.8420833333 5049.16416666667
MERGED_BAM_FILTER_00000087 0 33 36401.6779166667 41450.8420833333 5049.16416666667
MERGED_BAM_FILTER_00000112 0 34 36401.6779166667 41450.8420833333 5049.16416666667
MERGED_BAM_FILTER_00000137 0 35 36401.6779166667 41450.8420833333 5049.16416666667
MERGED_BAM_FILTER_00000162 2 31 1537705.4652334 1542754.62940006 5049.16416666657
MACS2_00000006 0 30 962017.080698584 963694.042365251 1676.96166666667
MACS2_00000028 0 18 1043528.65138124 1044646.62582569 1117.97444444441
MACS2_00000053 0 32 41450.8420833333 43127.80375 1676.96166666667
MACS2_00000078 0 33 41450.8420833333 43127.80375 1676.96166666667
MACS2_00000103 0 34 41450.8420833333 43127.80375 1676.96166666667
MACS2_00000128 0 35 41450.8420833333 43127.80375 1676.96166666667
MACS2_00000153 0 31 1542754.62940006 1544431.59106673 1676.96166666667
BIGWIG_00000021 0 30 963694.042365251 968375.981531918 4681.93916666671
BIGWIG_00000039 0 30 1389781.02992408 1394462.96909075 4681.93916666671
BIGWIG_00000064 0 32 43127.80375 47809.7429166667 4681.93916666666
BIGWIG_00000089 0 33 43127.80375 47809.7429166667 4681.93916666666
BIGWIG_00000114 0 34 43127.80375 47809.7429166667 4681.93916666666
BIGWIG_00000139 0 35 43127.80375 47809.7429166667 4681.93916666666
BIGWIG_00000164 0 31 1544431.59106673 1549113.5302334 4681.93916666671
CONSENSUS_PEAKS_00000008 0 18 1334993.59222667 1336111.56667111 1117.97444444452
CONSENSUS_PEAKS_00000047 0 19 1132895.0438273 1134013.01827175 1117.97444444452
CONSENSUS_PEAKS_00000072 0 32 47809.7429166667 49486.7045833333 1676.96166666667
CONSENSUS_PEAKS_00000097 0 33 47809.7429166667 49486.7045833333 1676.96166666667
CONSENSUS_PEAKS_00000122 0 34 47809.7429166667 49486.7045833333 1676.96166666667
CONSENSUS_PEAKS_00000147 0 35 47809.7429166667 49486.7045833333 1676.96166666667
CONSENSUS_PEAKS_00000172 0 31 1549113.5302334 1550790.49190006 1676.96166666667
CONSENSUS_PEAKS_COUNTS_00000007 0 19 1379004.5876125 1380122.56205695 1117.97444444452
CONSENSUS_PEAKS_COUNTS_00000026 0 20 1282363.17566654 1283481.15011099 1117.97444444452
CONSENSUS_PEAKS_COUNTS_00000051 0 32 49486.7045833333 51163.66625 1676.96166666667
CONSENSUS_PEAKS_COUNTS_00000076 0 33 49486.7045833333 51163.66625 1676.96166666667
CONSENSUS_PEAKS_COUNTS_00000101 0 34 49486.7045833333 51163.66625 1676.96166666667
CONSENSUS_PEAKS_COUNTS_00000126 0 35 49486.7045833333 51163.66625 1676.96166666667
CONSENSUS_PEAKS_COUNTS_00000151 0 31 1550790.49190006 1552467.45356673 1676.96166666667
MACS2_ANNOTATE_00000023 0 30 1394462.96909075 1396139.93075741 1676.96166666667
MACS2_ANNOTATE_00000034 0 18 1336111.56667111 1337229.54111556 1117.97444444452
MACS2_ANNOTATE_00000059 0 32 51163.66625 52840.6279166667 1676.96166666667
MACS2_ANNOTATE_00000084 0 33 51163.66625 52840.6279166667 1676.96166666667
MACS2_ANNOTATE_00000109 0 34 51163.66625 52840.6279166667 1676.96166666667
MACS2_ANNOTATE_00000134 0 35 51163.66625 52840.6279166667 1676.96166666667
MACS2_ANNOTATE_00000159 0 31 1552467.45356673 1554144.4152334 1676.96166666667
PHANTOMPEAKQUALTOOLS_00000014 0 30 1396139.93075741 1403977.32534075 7837.39458333328
PHANTOMPEAKQUALTOOLS_00000027 0 31 1554144.4152334 1561981.80981673 7837.39458333328
PHANTOMPEAKQUALTOOLS_00000052 0 32 52840.6279166667 60678.0225 7837.39458333333
PHANTOMPEAKQUALTOOLS_00000077 0 33 52840.6279166667 60678.0225 7837.39458333333
PHANTOMPEAKQUALTOOLS_00000102 0 34 52840.6279166667 60678.0225 7837.39458333333
PHANTOMPEAKQUALTOOLS_00000127 0 35 52840.6279166667 60678.0225 7837.39458333333
PHANTOMPEAKQUALTOOLS_00000152 0 31 1561981.80981673 1569819.20440006 7837.39458333328
PLOTPROFILE_00000016 0 30 1403977.32534075 1413302.18992408 9324.86458333326
PLOTPROFILE_00000044 0 30 1413302.18992408 1422627.05450741 9324.86458333326
PLOTPROFILE_00000069 0 32 60678.0225 70002.8870833333 9324.86458333334
PLOTPROFILE_00000094 0 33 60678.0225 70002.8870833333 9324.86458333334
PLOTPROFILE_00000119 0 34 60678.0225 70002.8870833333 9324.86458333334
PLOTPROFILE_00000144 0 35 60678.0225 70002.8870833333 9324.86458333334
PLOTPROFILE_00000169 0 31 1569819.20440006 1579144.0689834 9324.86458333326
PRESEQ_00000013 0 30 1422627.05450741 1426489.69659075 3862.64208333334
PRESEQ_00000032 0 31 1579144.0689834 1583006.71106673 3862.64208333334
PRESEQ_00000057 0 32 70002.8870833333 73865.5291666667 3862.64208333334
PRESEQ_00000082 0 33 70002.8870833333 73865.5291666667 3862.64208333334
PRESEQ_00000107 0 34 70002.8870833333 73865.5291666667 3862.64208333334
PRESEQ_00000132 0 35 70002.8870833333 73865.5291666667 3862.64208333334
PRESEQ_00000157 0 30 1426489.69659075 1430352.33867408 3862.64208333334
FASTQC_00000003 0 30 1430352.33867408 1432593.36742408 2241.02875000006
FASTQC_00000042 0 32 1912870.07901269 1915111.10776269 2241.02875000006
FASTQC_00000067 0 33 1912870.07901269 1915111.10776269 2241.02875000006
FASTQC_00000092 0 34 1912870.07901269 1915111.10776269 2241.02875000006
FASTQC_00000117 0 35 1912870.07901269 1915111.10776269 2241.02875000006
FASTQC_00000142 0 35 1915111.10776269 1917352.13651269 2241.02875000006
FASTQC_00000167 0 12 2307688.0300654 2310676.06839873 2988.03833333356
CONSENSUS_PEAKS_DESEQ2_00000018 0 19 1380122.56205695 1381240.53650139 1117.97444444452
CONSENSUS_PEAKS_DESEQ2_00000029 0 20 1283481.15011099 1284599.12455543 1117.97444444452
CONSENSUS_PEAKS_DESEQ2_00000054 0 21 1043539.37286687 1044657.34731131 1117.97444444441
CONSENSUS_PEAKS_DESEQ2_00000079 0 22 1043539.37286687 1044657.34731131 1117.97444444441
CONSENSUS_PEAKS_DESEQ2_00000104 0 23 1043539.37286687 1044657.34731131 1117.97444444441
CONSENSUS_PEAKS_DESEQ2_00000129 0 24 139412.084251617 141089.045918284 1676.96166666667
CONSENSUS_PEAKS_DESEQ2_00000154 0 31 1583006.71106673 1584683.6727334 1676.96166666667
PICARD_METRICS_00000015 0 30 1432593.36742408 1434270.32909075 1676.96166666667
PICARD_METRICS_00000033 0 31 1584683.6727334 1586360.63440006 1676.96166666667
PICARD_METRICS_00000058 0 32 1915111.10776269 1916788.06942935 1676.96166666667
PICARD_METRICS_00000083 0 33 1915111.10776269 1916788.06942935 1676.96166666667
PICARD_METRICS_00000108 0 34 1915111.10776269 1916788.06942935 1676.96166666667
PICARD_METRICS_00000133 0 35 1917352.13651269 1919029.09817935 1676.96166666667
PICARD_METRICS_00000158 0 31 1586360.63440006 1588037.59606673 1676.96166666667
PLOTFINGERPRINT_00000004 0 18 1423048.24853847 1424166.22298292 1117.97444444452
MACS2_QC_00000017 0 30 1434270.32909075 1435947.29075741 1676.96166666667
get_software_versions_00000019 0 7 419.240416666667 838.480833333333 419.240416666667
MACS2_QC_00000035 0 20 1402354.62773535 1403472.60217979 1117.97444444452
PLOTFINGERPRINT_00000050 0 21 1326406.88194879 1327524.85639324 1117.97444444452
get_software_versions_00000045 0 8 419.240416666667 838.480833333333 419.240416666667
MACS2_QC_00000060 0 24 1065555.77544437 1067232.73711104 1676.96166666667
PLOTFINGERPRINT_00000075 0 22 1131594.02796832 1132712.00241276 1117.97444444452
get_software_versions_00000070 0 9 419.240416666667 838.480833333333 419.240416666667
MACS2_QC_00000085 0 25 1065555.77544437 1067232.73711104 1676.96166666667
PLOTFINGERPRINT_00000100 0 23 1131594.02796832 1132712.00241276 1117.97444444452
get_software_versions_00000095 0 10 419.240416666667 838.480833333333 419.240416666667
MACS2_QC_00000110 0 26 1065555.77544437 1067232.73711104 1676.96166666667
PLOTFINGERPRINT_00000125 0 24 1131594.02796832 1133270.98963498 1676.96166666667
get_software_versions_00000120 0 11 419.240416666667 838.480833333333 419.240416666667
MACS2_QC_00000135 0 27 161428.48682912 163105.448495787 1676.96166666667
PLOTFINGERPRINT_00000150 0 27 227466.739353067 229143.701019734 1676.96166666667
get_software_versions_00000145 0 6 838.480833333333 1257.72125 419.240416666667
MACS2_QC_00000160 0 31 1588037.59606673 1589714.5577334 1676.96166666667
PLOTFINGERPRINT_00000175 0 31 1589714.5577334 1591391.51940006 1676.96166666667
get_software_versions_00000170 0 7 838.480833333333 1257.72125 419.240416666667
MULTIQC_00000010 0 30 1435947.29075741 1437624.25242408 1676.96166666667
IGV_00000022 0 30 1437624.25242408 1439301.21409075 1676.96166666667
CONSENSUS_PEAKS_ANNOTATE_00000024 0 18 1424166.22298292 1425284.19742736 1117.97444444452
output_documentation_00000025 0 8 838.480833333333 1257.72125 419.240416666667
MULTIQC_00000041 0 8 1915117.79632754 1915537.03674421 419.240416666726
IGV_00000036 0 30 1439301.21409075 1440978.17575741 1676.96166666667
CONSENSUS_PEAKS_ANNOTATE_00000043 0 19 1381240.53650139 1382358.51094583 1117.97444444452
output_documentation_00000048 0 9 838.480833333333 1257.72125 419.240416666667
MULTIQC_00000066 0 32 1916788.06942935 1918465.03109602 1676.96166666667
IGV_00000061 0 32 1918465.03109602 1920141.99276269 1676.96166666667
CONSENSUS_PEAKS_ANNOTATE_00000068 0 32 1920141.99276269 1921818.95442935 1676.96166666667
output_documentation_00000073 0 10 838.480833333333 1257.72125 419.240416666667
MULTIQC_00000091 0 33 1916788.06942935 1918465.03109602 1676.96166666667
IGV_00000086 0 33 1918465.03109602 1920141.99276269 1676.96166666667
CONSENSUS_PEAKS_ANNOTATE_00000093 0 33 1920141.99276269 1921818.95442935 1676.96166666667
output_documentation_00000098 0 11 838.480833333333 1257.72125 419.240416666667
MULTIQC_00000116 0 34 1916788.06942935 1918465.03109602 1676.96166666667
IGV_00000111 0 34 1918465.03109602 1920141.99276269 1676.96166666667
CONSENSUS_PEAKS_ANNOTATE_00000118 0 34 1920141.99276269 1921818.95442935 1676.96166666667
output_documentation_00000123 0 28 0 1676.96166666667 1676.96166666667
MULTIQC_00000141 0 35 1919029.09817935 1920706.05984602 1676.96166666667
IGV_00000136 0 35 1920706.05984602 1922383.02151269 1676.96166666667
CONSENSUS_PEAKS_ANNOTATE_00000143 0 35 1922383.02151269 1924059.98317935 1676.96166666667
output_documentation_00000148 0 29 0 1676.96166666667 1676.96166666667
MULTIQC_00000166 0 7 2310683.89185791 2311103.13227457 419.240416666493
IGV_00000161 0 31 1591391.51940006 1593068.48106673 1676.96166666667
CONSENSUS_PEAKS_ANNOTATE_00000168 0 31 1593068.48106673 1594745.4427334 1676.96166666667
output_documentation_00000173 0 6 1257.72125 1676.96166666667 419.240416666667
'''

out_dyn = '''
CHECK_DESIGN_00000001 0 30 0 1676.96166666667 1676.96166666667
TRIMGALORE_00000002 0 30 1676.96166666667 6188.43083333333 4511.46916666667
CHECK_DESIGN_00000049 0 31 0 1676.96166666667 1676.96166666667
TRIMGALORE_00000030 0 31 1676.96166666667 6188.43083333333 4511.46916666667
CHECK_DESIGN_00000074 0 32 0 1676.96166666667 1676.96166666667
TRIMGALORE_00000055 0 32 1676.96166666667 6188.43083333333 4511.46916666667
CHECK_DESIGN_00000099 0 33 0 1676.96166666667 1676.96166666667
TRIMGALORE_00000080 0 33 1676.96166666667 6188.43083333333 4511.46916666667
CHECK_DESIGN_00000124 0 34 0 1676.96166666667 1676.96166666667
TRIMGALORE_00000105 0 34 1676.96166666667 6188.43083333333 4511.46916666667
CHECK_DESIGN_00000149 0 35 0 1676.96166666667 1676.96166666667
TRIMGALORE_00000130 0 35 1676.96166666667 6188.43083333333 4511.46916666667
CHECK_DESIGN_00000174 0 30 6188.43083333333 7865.3925 1676.96166666667
TRIMGALORE_00000155 0 30 7865.3925 12376.8616666667 4511.46916666667
BWA_MEM_00000009 1 30 12376.8616666667 614541.05117905 602164.189512384
BWA_MEM_00000038 0 31 6188.43083333333 23942.1258333333 17753.695
BWA_MEM_00000063 0 32 6188.43083333333 23942.1258333333 17753.695
BWA_MEM_00000088 0 33 6188.43083333333 23942.1258333333 17753.695
BWA_MEM_00000113 0 34 6188.43083333333 23942.1258333333 17753.695
BWA_MEM_00000138 0 35 6188.43083333333 23942.1258333333 17753.695
BWA_MEM_00000163 1 30 614541.05117905 715066.863002861 100525.81182381
MAKE_GENOME_FILTER_00000031 0 6 0 419.240416666667 419.240416666667
MAKE_GENOME_FILTER_00000056 0 7 0 419.240416666667 419.240416666667
MAKE_GENOME_FILTER_00000081 0 8 0 419.240416666667 419.240416666667
MAKE_GENOME_FILTER_00000106 0 9 0 419.240416666667 419.240416666667
MAKE_GENOME_FILTER_00000131 0 10 0 419.240416666667 419.240416666667
MAKE_GENOME_FILTER_00000156 0 11 0 419.240416666667 419.240416666667
SORT_BAM_00000011 0 30 715066.863002861 717761.574669527 2694.71166666667
SORT_BAM_00000040 0 31 23942.1258333333 26636.8375 2694.71166666667
SORT_BAM_00000065 0 32 23942.1258333333 26636.8375 2694.71166666667
SORT_BAM_00000090 0 33 23942.1258333333 26636.8375 2694.71166666667
SORT_BAM_00000115 0 34 23942.1258333333 26636.8375 2694.71166666667
SORT_BAM_00000140 0 35 23942.1258333333 26636.8375 2694.71166666667
SORT_BAM_00000165 0 30 717761.574669527 720456.286336194 2694.71166666667
MERGED_BAM_00000012 1 30 720456.286336194 731192.467893984 10736.18155779
MERGED_BAM_00000046 0 31 26636.8375 36401.6779166667 9764.84041666667
MERGED_BAM_FILTER_00000037 0 31 36401.6779166667 41450.8420833333 5049.16416666667
MERGED_BAM_00000071 0 32 26636.8375 36401.6779166667 9764.84041666667
MERGED_BAM_FILTER_00000062 0 32 36401.6779166667 41450.8420833333 5049.16416666667
MERGED_BAM_00000096 0 33 26636.8375 36401.6779166667 9764.84041666667
MERGED_BAM_FILTER_00000087 0 33 36401.6779166667 41450.8420833333 5049.16416666667
MERGED_BAM_00000121 0 34 26636.8375 36401.6779166667 9764.84041666667
MERGED_BAM_FILTER_00000112 0 34 36401.6779166667 41450.8420833333 5049.16416666667
MERGED_BAM_00000146 0 35 26636.8375 36401.6779166667 9764.84041666667
MERGED_BAM_FILTER_00000137 0 35 36401.6779166667 41450.8420833333 5049.16416666667
MERGED_BAM_00000171 1 30 731192.467893984 819163.924288844 87971.4563948599
MERGED_BAM_FILTER_00000162 2 30 953613.993198584 966528.549865251 12914.5566666666
MACS2_00000028 0 31 41450.8420833333 43127.80375 1676.96166666667
MACS2_00000053 0 32 41450.8420833333 43127.80375 1676.96166666667
MACS2_00000078 0 33 41450.8420833333 43127.80375 1676.96166666667
MACS2_00000103 0 34 41450.8420833333 43127.80375 1676.96166666667
MACS2_00000128 0 35 41450.8420833333 43127.80375 1676.96166666667
MACS2_00000153 0 30 966528.549865251 968205.511531918 1676.96166666667
BIGWIG_00000039 0 31 43127.80375 47809.7429166667 4681.93916666666
BIGWIG_00000064 0 32 43127.80375 47809.7429166667 4681.93916666666
BIGWIG_00000089 0 33 43127.80375 47809.7429166667 4681.93916666666
BIGWIG_00000114 0 34 43127.80375 47809.7429166667 4681.93916666666
BIGWIG_00000139 0 35 43127.80375 47809.7429166667 4681.93916666666
BIGWIG_00000164 0 30 968205.511531918 972887.450698584 4681.93916666671
CONSENSUS_PEAKS_00000047 0 31 47809.7429166667 49486.7045833333 1676.96166666667
CONSENSUS_PEAKS_COUNTS_00000026 0 31 49486.7045833333 51163.66625 1676.96166666667
CONSENSUS_PEAKS_00000072 0 32 47809.7429166667 49486.7045833333 1676.96166666667
CONSENSUS_PEAKS_COUNTS_00000051 0 32 49486.7045833333 51163.66625 1676.96166666667
CONSENSUS_PEAKS_00000097 0 33 47809.7429166667 49486.7045833333 1676.96166666667
CONSENSUS_PEAKS_COUNTS_00000076 0 33 49486.7045833333 51163.66625 1676.96166666667
CONSENSUS_PEAKS_00000122 0 34 47809.7429166667 49486.7045833333 1676.96166666667
CONSENSUS_PEAKS_COUNTS_00000101 0 34 49486.7045833333 51163.66625 1676.96166666667
CONSENSUS_PEAKS_00000147 0 35 47809.7429166667 49486.7045833333 1676.96166666667
CONSENSUS_PEAKS_COUNTS_00000126 0 35 49486.7045833333 51163.66625 1676.96166666667
CONSENSUS_PEAKS_00000172 0 30 972887.450698584 974564.412365251 1676.96166666667
CONSENSUS_PEAKS_COUNTS_00000151 0 30 974564.412365251 976241.374031918 1676.96166666667
MACS2_ANNOTATE_00000034 0 31 51163.66625 52840.6279166667 1676.96166666667
MACS2_ANNOTATE_00000059 0 32 51163.66625 52840.6279166667 1676.96166666667
MACS2_ANNOTATE_00000084 0 33 51163.66625 52840.6279166667 1676.96166666667
MACS2_ANNOTATE_00000109 0 34 51163.66625 52840.6279166667 1676.96166666667
MACS2_ANNOTATE_00000134 0 35 51163.66625 52840.6279166667 1676.96166666667
MACS2_ANNOTATE_00000159 0 30 976241.374031918 977918.335698584 1676.96166666667
PHANTOMPEAKQUALTOOLS_00000027 0 31 52840.6279166667 60678.0225 7837.39458333333
PHANTOMPEAKQUALTOOLS_00000052 0 32 52840.6279166667 60678.0225 7837.39458333333
PHANTOMPEAKQUALTOOLS_00000077 0 33 52840.6279166667 60678.0225 7837.39458333333
PHANTOMPEAKQUALTOOLS_00000102 0 34 52840.6279166667 60678.0225 7837.39458333333
PHANTOMPEAKQUALTOOLS_00000127 0 35 52840.6279166667 60678.0225 7837.39458333333
PHANTOMPEAKQUALTOOLS_00000152 0 30 977918.335698584 985755.730281918 7837.39458333328
MAKE_GENOME_FILTER_00000020 0 6 419.240416666667 838.480833333333 419.240416666667
MERGED_BAM_FILTER_00000005 0 31 1542315.09820021 1547364.26236687 5049.16416666657
MACS2_00000006 0 31 1547364.26236687 1549041.22403354 1676.96166666667
BIGWIG_00000021 2 31 1549041.22403354 1553723.16320021 4681.93916666671
CONSENSUS_PEAKS_00000008 0 31 1553723.16320021 1555400.12486687 1676.96166666667
CONSENSUS_PEAKS_COUNTS_00000007 0 31 1555400.12486687 1557077.08653354 1676.96166666667
MACS2_ANNOTATE_00000023 0 31 1557077.08653354 1558754.04820021 1676.96166666667
PHANTOMPEAKQUALTOOLS_00000014 0 31 1558754.04820021 1566591.44278354 7837.39458333328
PLOTPROFILE_00000016 0 31 1566591.44278354 1575916.30736687 9324.86458333326
PLOTPROFILE_00000044 0 30 1043539.5595959 1052864.42417924 9324.86458333326
PLOTPROFILE_00000069 0 32 60678.0225 70002.8870833333 9324.86458333334
PLOTPROFILE_00000094 0 33 60678.0225 70002.8870833333 9324.86458333334
PLOTPROFILE_00000119 0 34 60678.0225 70002.8870833333 9324.86458333334
PLOTPROFILE_00000144 0 35 60678.0225 70002.8870833333 9324.86458333334
PLOTPROFILE_00000169 0 30 1052864.42417924 1062189.28876257 9324.86458333326
PRESEQ_00000013 0 30 1062189.28876257 1066051.9308459 3862.64208333334
PRESEQ_00000032 0 31 1575916.30736687 1579778.94945021 3862.64208333334
PRESEQ_00000057 0 32 70002.8870833333 73865.5291666667 3862.64208333334
PRESEQ_00000082 0 33 70002.8870833333 73865.5291666667 3862.64208333334
PRESEQ_00000107 0 34 70002.8870833333 73865.5291666667 3862.64208333334
PRESEQ_00000132 0 35 70002.8870833333 73865.5291666667 3862.64208333334
PRESEQ_00000157 0 30 1066051.9308459 1069914.57292924 3862.64208333334
FASTQC_00000003 0 30 1069914.57292924 1072155.60167924 2241.02875000006
FASTQC_00000042 0 32 1912870.07901269 1915111.10776269 2241.02875000006
FASTQC_00000067 0 33 1912870.07901269 1915111.10776269 2241.02875000006
FASTQC_00000092 0 34 1912870.07901269 1915111.10776269 2241.02875000006
FASTQC_00000117 0 35 1912870.07901269 1915111.10776269 2241.02875000006
FASTQC_00000142 0 35 1915111.10776269 1917352.13651269 2241.02875000006
FASTQC_00000167 0 30 2027493.69707667 2029734.72582667 2241.02875000006
CONSENSUS_PEAKS_DESEQ2_00000029 0 18 1087572.13103642 1088690.10548086 1117.97444444452
CONSENSUS_PEAKS_DESEQ2_00000054 0 19 1043539.37286687 1044657.34731131 1117.97444444441
CONSENSUS_PEAKS_DESEQ2_00000079 0 20 1043539.37286687 1044657.34731131 1117.97444444441
CONSENSUS_PEAKS_DESEQ2_00000104 0 21 1043539.37286687 1044657.34731131 1117.97444444441
CONSENSUS_PEAKS_DESEQ2_00000129 0 22 139412.084251617 140530.058696061 1117.97444444444
CONSENSUS_PEAKS_DESEQ2_00000154 0 18 1643637.5920396 1644755.56648405 1117.97444444452
CONSENSUS_PEAKS_DESEQ2_00000018 0 31 1579778.94945021 1581455.91111687 1676.96166666667
PICARD_METRICS_00000015 0 31 1581455.91111687 1583132.87278354 1676.96166666667
PICARD_METRICS_00000033 0 31 1583132.87278354 1584809.83445021 1676.96166666667
PICARD_METRICS_00000058 0 32 1915111.10776269 1916788.06942935 1676.96166666667
PICARD_METRICS_00000083 0 33 1915111.10776269 1916788.06942935 1676.96166666667
PICARD_METRICS_00000108 0 34 1915111.10776269 1916788.06942935 1676.96166666667
PICARD_METRICS_00000133 0 35 1917352.13651269 1919029.09817935 1676.96166666667
PICARD_METRICS_00000158 0 30 2029734.72582667 2031411.68749334 1676.96166666667
PLOTFINGERPRINT_00000004 0 31 1599443.70076389 1601120.66243056 1676.96166666667
MACS2_QC_00000017 0 31 1601120.66243056 1602797.62409722 1676.96166666667
get_software_versions_00000019 0 7 419.240416666667 838.480833333333 419.240416666667
MACS2_QC_00000035 0 19 1109588.53361392 1110706.50805836 1117.97444444452
PLOTFINGERPRINT_00000050 0 19 1175718.3302368 1176836.30468125 1117.97444444452
get_software_versions_00000045 0 8 419.240416666667 838.480833333333 419.240416666667
MACS2_QC_00000060 0 22 1065555.77544437 1066673.74988882 1117.97444444452
PLOTFINGERPRINT_00000075 0 20 1131685.57206725 1132803.5465117 1117.97444444452
get_software_versions_00000070 0 9 419.240416666667 838.480833333333 419.240416666667
MACS2_QC_00000085 0 23 1065555.77544437 1066673.74988882 1117.97444444452
PLOTFINGERPRINT_00000100 0 21 1131685.57206725 1132803.5465117 1117.97444444452
get_software_versions_00000095 0 10 419.240416666667 838.480833333333 419.240416666667
MACS2_QC_00000110 0 24 1065555.77544437 1067232.73711104 1676.96166666667
PLOTFINGERPRINT_00000125 0 22 1131685.57206725 1132803.5465117 1117.97444444452
get_software_versions_00000120 0 11 419.240416666667 838.480833333333 419.240416666667
MACS2_QC_00000135 0 25 161428.48682912 163105.448495787 1676.96166666667
PLOTFINGERPRINT_00000150 0 25 227558.283452004 229235.24511867 1676.96166666667
get_software_versions_00000145 0 6 838.480833333333 1257.72125 419.240416666667
MACS2_QC_00000160 0 19 1665664.90280255 1666782.877247 1117.97444444452
PLOTFINGERPRINT_00000175 0 18 1731794.69942543 1732912.67386988 1117.97444444452
get_software_versions_00000170 0 7 838.480833333333 1257.72125 419.240416666667
MULTIQC_00000010 0 31 1794363.77520209 1796040.73686875 1676.96166666667
IGV_00000022 0 20 1641955.67763947 1643073.65208392 1117.97444444452
CONSENSUS_PEAKS_ANNOTATE_00000024 0 19 1730200.06053686 1731318.03498131 1117.97444444452
output_documentation_00000025 0 8 838.480833333333 1257.72125 419.240416666667
MULTIQC_00000041 0 8 1915117.79632754 1915537.03674421 419.240416666726
IGV_00000036 0 31 1796040.73686875 1797717.69853542 1676.96166666667
CONSENSUS_PEAKS_ANNOTATE_00000043 0 31 1797717.69853542 1799394.66020209 1676.96166666667
output_documentation_00000048 0 9 838.480833333333 1257.72125 419.240416666667
MULTIQC_00000066 0 32 1916792.60642522 1918469.56809189 1676.96166666667
IGV_00000061 0 32 1918469.56809189 1920146.52975856 1676.96166666667
CONSENSUS_PEAKS_ANNOTATE_00000068 0 32 1920146.52975856 1921823.49142522 1676.96166666667
output_documentation_00000073 0 10 838.480833333333 1257.72125 419.240416666667
MULTIQC_00000091 0 33 1916794.53592399 1918471.49759065 1676.96166666667
IGV_00000086 0 33 1918471.49759065 1920148.45925732 1676.96166666667
CONSENSUS_PEAKS_ANNOTATE_00000093 0 33 1920148.45925732 1921825.42092399 1676.96166666667
output_documentation_00000098 0 11 838.480833333333 1257.72125 419.240416666667
MULTIQC_00000116 0 34 1916796.46542275 1918473.42708942 1676.96166666667
IGV_00000111 0 34 1918473.42708942 1920150.38875608 1676.96166666667
CONSENSUS_PEAKS_ANNOTATE_00000118 0 34 1920150.38875608 1921827.35042275 1676.96166666667
output_documentation_00000123 0 26 0 1676.96166666667 1676.96166666667
MULTIQC_00000141 0 35 1919031.03034501 1920707.99201168 1676.96166666667
IGV_00000136 0 35 1920707.99201168 1922384.95367835 1676.96166666667
CONSENSUS_PEAKS_ANNOTATE_00000143 0 35 1922384.95367835 1924061.91534501 1676.96166666667
output_documentation_00000148 0 27 0 1676.96166666667 1676.96166666667
MULTIQC_00000166 0 30 2031413.619659 2033090.58132567 1676.96166666667
IGV_00000161 0 18 1883641.7532271 1884759.72767154 1117.97444444452
CONSENSUS_PEAKS_ANNOTATE_00000168 0 19 1927686.42998029 1928804.40442474 1117.97444444452
output_documentation_00000173 0 28 0 1676.96166666667 1676.96166666667
'''

from io import StringIO

s = StringIO(out_dyn)

dfdyn = pd.read_csv(s, sep=" ", names=["workflow", "variant", "processor", "from", "to", "duration"])
#print(df)


s = StringIO(out_stat)

dfstat = pd.read_csv(s, sep=" ", names=["workflow", "variant", "processor", "from", "to", "duration"])
#print(df)

merged_df = pd.merge(dfdyn, dfstat, on='workflow', how='outer')
#print(merged_df)

noteq = merged_df.loc[~(merged_df['processor_x'] == merged_df['processor_y'])]
noteq = noteq.loc[~(noteq['duration_x'] == noteq['duration_y'])]
print(noteq[['workflow','processor_x', 'processor_y', 'duration_x', 'duration_y', 'variant_x', 'variant_y']])

                              workflow  processor_x  processor_y  \
46          MERGED_BAM_FILTER_00000162           30           31
47                      MACS2_00000028           31           18
53                     BIGWIG_00000039           31           30
59            CONSENSUS_PEAKS_00000047           31           19
60     CONSENSUS_PEAKS_COUNTS_00000026           31           20
71             MACS2_ANNOTATE_00000034           31           18
84          MERGED_BAM_FILTER_00000005           31           30
87            CONSENSUS_PEAKS_00000008           31           18
88     CONSENSUS_PEAKS_COUNTS_00000007           31           19
111                    FASTQC_00000167           30           12
116    CONSENSUS_PEAKS_DESEQ2_00000129           22           24
117    CONSENSUS_PEAKS_DESEQ2_00000154           18           31
118    CONSENSUS_PEAKS_DESEQ2_00000018           31           19
126           PLOTFINGERPRINT_00000004           31           18
132                  MACS2_QC_00000060           22           24
135                  MACS2_QC_00000085           23           25
139           PLOTFINGERPRINT_00000125           22           24
144                  MACS2_QC_00000160           19           31
145           PLOTFINGERPRINT_00000175           18           31
148                       IGV_00000022           20           30
153  CONSENSUS_PEAKS_ANNOTATE_00000043           31           19
171                   MULTIQC_00000166           30            7
172                       IGV_00000161           18           31
173  CONSENSUS_PEAKS_ANNOTATE_00000168           19           31
174      output_documentation_00000173           28            6

       duration_x   duration_y  variant_x  variant_y
46   12914.556667  5049.164167          2          2
47    1676.961667  1117.974444          0          0
53    4681.939167  4681.939167          0          0
59    1676.961667  1117.974444          0          0
60    1676.961667  1117.974444          0          0
71    1676.961667  1117.974444          0          0
84    5049.164167  5049.164167          0          2
87    1676.961667  1117.974444          0          0
88    1676.961667  1117.974444          0          0
111   2241.028750  2988.038333          0          0
116   1117.974444  1676.961667          0          0
117   1117.974444  1676.961667          0          0
118   1676.961667  1117.974444          0          0
126   1676.961667  1117.974444          0          0
132   1117.974444  1676.961667          0          0
135   1117.974444  1676.961667          0          0
139   1117.974444  1676.961667          0          0
144   1117.974444  1676.961667          0          0
145   1117.974444  1676.961667          0          0
148   1117.974444  1676.961667          0          0
153   1676.961667  1117.974444          0          0
171   1676.961667   419.240417          0          0
172   1117.974444  1676.961667          0          0
173   1117.974444  1676.961667          0          0
174   1676.961667   419.240417          0          0

In [20]:
sorted_dfdyn = dfdyn.sort_values(['processor', 'from', 'to'])
pd.options.display.float_format = '{:.0f}'.format
print(sorted_dfdyn.to_string())

                              workflow  variant  processor    from      to  duration
21         MAKE_GENOME_FILTER_00000031        0          6       0     419       419
83         MAKE_GENOME_FILTER_00000020        0          6     419     838       419
143     get_software_versions_00000145        0          6     838    1258       419
22         MAKE_GENOME_FILTER_00000056        0          7       0     419       419
128     get_software_versions_00000019        0          7     419     838       419
146     get_software_versions_00000170        0          7     838    1258       419
23         MAKE_GENOME_FILTER_00000081        0          8       0     419       419
131     get_software_versions_00000045        0          8     419     838       419
150      output_documentation_00000025        0          8     838    1258       419
151                   MULTIQC_00000041        0          8 1915118 1915537       419
24         MAKE_GENOME_FILTER_00000106        0          9       0     419       419
134     get_software_versions_00000070        0          9     419     838       419
154      output_documentation_00000048        0          9     838    1258       419
25         MAKE_GENOME_FILTER_00000131        0         10       0     419       419
137     get_software_versions_00000095        0         10     419     838       419
158      output_documentation_00000073        0         10     838    1258       419
26         MAKE_GENOME_FILTER_00000156        0         11       0     419       419
140     get_software_versions_00000120        0         11     419     838       419
162      output_documentation_00000098        0         11     838    1258       419
112    CONSENSUS_PEAKS_DESEQ2_00000029        0         18 1087572 1088690      1118
117    CONSENSUS_PEAKS_DESEQ2_00000154        0         18 1643638 1644756      1118
145           PLOTFINGERPRINT_00000175        0         18 1731795 1732913      1118
172                       IGV_00000161        0         18 1883642 1884760      1118
113    CONSENSUS_PEAKS_DESEQ2_00000054        0         19 1043539 1044657      1118
129                  MACS2_QC_00000035        0         19 1109589 1110707      1118
130           PLOTFINGERPRINT_00000050        0         19 1175718 1176836      1118
144                  MACS2_QC_00000160        0         19 1665665 1666783      1118
149  CONSENSUS_PEAKS_ANNOTATE_00000024        0         19 1730200 1731318      1118
173  CONSENSUS_PEAKS_ANNOTATE_00000168        0         19 1927686 1928804      1118
114    CONSENSUS_PEAKS_DESEQ2_00000079        0         20 1043539 1044657      1118
133           PLOTFINGERPRINT_00000075        0         20 1131686 1132804      1118
148                       IGV_00000022        0         20 1641956 1643074      1118
115    CONSENSUS_PEAKS_DESEQ2_00000104        0         21 1043539 1044657      1118
136           PLOTFINGERPRINT_00000100        0         21 1131686 1132804      1118
116    CONSENSUS_PEAKS_DESEQ2_00000129        0         22  139412  140530      1118
132                  MACS2_QC_00000060        0         22 1065556 1066674      1118
139           PLOTFINGERPRINT_00000125        0         22 1131686 1132804      1118
135                  MACS2_QC_00000085        0         23 1065556 1066674      1118
138                  MACS2_QC_00000110        0         24 1065556 1067233      1677
141                  MACS2_QC_00000135        0         25  161428  163105      1677
142           PLOTFINGERPRINT_00000150        0         25  227558  229235      1677
166      output_documentation_00000123        0         26       0    1677      1677
170      output_documentation_00000148        0         27       0    1677      1677
174      output_documentation_00000173        0         28       0    1677      1677
0                CHECK_DESIGN_00000001        0         30       0    1677      1677
1                  TRIMGALORE_00000002        0         30    1677    6188      4511
12               CHECK_DESIGN_00000174        0         30    6188    7865      1677
13                 TRIMGALORE_00000155        0         30    7865   12377      4511
14                    BWA_MEM_00000009        1         30   12377  614541    602164
20                    BWA_MEM_00000163        1         30  614541  715067    100526
27                   SORT_BAM_00000011        0         30  715067  717762      2695
33                   SORT_BAM_00000165        0         30  717762  720456      2695
34                 MERGED_BAM_00000012        1         30  720456  731192     10736
45                 MERGED_BAM_00000171        1         30  731192  819164     87971
46          MERGED_BAM_FILTER_00000162        2         30  953614  966529     12915
52                      MACS2_00000153        0         30  966529  968206      1677
58                     BIGWIG_00000164        0         30  968206  972887      4682
69            CONSENSUS_PEAKS_00000172        0         30  972887  974564      1677
70     CONSENSUS_PEAKS_COUNTS_00000151        0         30  974564  976241      1677
76             MACS2_ANNOTATE_00000159        0         30  976241  977918      1677
82       PHANTOMPEAKQUALTOOLS_00000152        0         30  977918  985756      7837
92                PLOTPROFILE_00000044        0         30 1043540 1052864      9325
97                PLOTPROFILE_00000169        0         30 1052864 1062189      9325
98                     PRESEQ_00000013        0         30 1062189 1066052      3863
104                    PRESEQ_00000157        0         30 1066052 1069915      3863
105                    FASTQC_00000003        0         30 1069915 1072156      2241
111                    FASTQC_00000167        0         30 2027494 2029735      2241
125            PICARD_METRICS_00000158        0         30 2029735 2031412      1677
171                   MULTIQC_00000166        0         30 2031414 2033091      1677
2                CHECK_DESIGN_00000049        0         31       0    1677      1677
3                  TRIMGALORE_00000030        0         31    1677    6188      4511
15                    BWA_MEM_00000038        0         31    6188   23942     17754
28                   SORT_BAM_00000040        0         31   23942   26637      2695
35                 MERGED_BAM_00000046        0         31   26637   36402      9765
36          MERGED_BAM_FILTER_00000037        0         31   36402   41451      5049
47                      MACS2_00000028        0         31   41451   43128      1677
53                     BIGWIG_00000039        0         31   43128   47810      4682
59            CONSENSUS_PEAKS_00000047        0         31   47810   49487      1677
60     CONSENSUS_PEAKS_COUNTS_00000026        0         31   49487   51164      1677
71             MACS2_ANNOTATE_00000034        0         31   51164   52841      1677
77       PHANTOMPEAKQUALTOOLS_00000027        0         31   52841   60678      7837
84          MERGED_BAM_FILTER_00000005        0         31 1542315 1547364      5049
85                      MACS2_00000006        0         31 1547364 1549041      1677
86                     BIGWIG_00000021        2         31 1549041 1553723      4682
87            CONSENSUS_PEAKS_00000008        0         31 1553723 1555400      1677
88     CONSENSUS_PEAKS_COUNTS_00000007        0         31 1555400 1557077      1677
89             MACS2_ANNOTATE_00000023        0         31 1557077 1558754      1677
90       PHANTOMPEAKQUALTOOLS_00000014        0         31 1558754 1566591      7837
91                PLOTPROFILE_00000016        0         31 1566591 1575916      9325
99                     PRESEQ_00000032        0         31 1575916 1579779      3863
118    CONSENSUS_PEAKS_DESEQ2_00000018        0         31 1579779 1581456      1677
119            PICARD_METRICS_00000015        0         31 1581456 1583133      1677
120            PICARD_METRICS_00000033        0         31 1583133 1584810      1677
126           PLOTFINGERPRINT_00000004        0         31 1599444 1601121      1677
127                  MACS2_QC_00000017        0         31 1601121 1602798      1677
147                   MULTIQC_00000010        0         31 1794364 1796041      1677
152                       IGV_00000036        0         31 1796041 1797718      1677
153  CONSENSUS_PEAKS_ANNOTATE_00000043        0         31 1797718 1799395      1677
4                CHECK_DESIGN_00000074        0         32       0    1677      1677
5                  TRIMGALORE_00000055        0         32    1677    6188      4511
16                    BWA_MEM_00000063        0         32    6188   23942     17754
29                   SORT_BAM_00000065        0         32   23942   26637      2695
37                 MERGED_BAM_00000071        0         32   26637   36402      9765
38          MERGED_BAM_FILTER_00000062        0         32   36402   41451      5049
48                      MACS2_00000053        0         32   41451   43128      1677
54                     BIGWIG_00000064        0         32   43128   47810      4682
61            CONSENSUS_PEAKS_00000072        0         32   47810   49487      1677
62     CONSENSUS_PEAKS_COUNTS_00000051        0         32   49487   51164      1677
72             MACS2_ANNOTATE_00000059        0         32   51164   52841      1677
78       PHANTOMPEAKQUALTOOLS_00000052        0         32   52841   60678      7837
93                PLOTPROFILE_00000069        0         32   60678   70003      9325
100                    PRESEQ_00000057        0         32   70003   73866      3863
106                    FASTQC_00000042        0         32 1912870 1915111      2241
121            PICARD_METRICS_00000058        0         32 1915111 1916788      1677
155                   MULTIQC_00000066        0         32 1916793 1918470      1677
156                       IGV_00000061        0         32 1918470 1920147      1677
157  CONSENSUS_PEAKS_ANNOTATE_00000068        0         32 1920147 1921823      1677
6                CHECK_DESIGN_00000099        0         33       0    1677      1677
7                  TRIMGALORE_00000080        0         33    1677    6188      4511
17                    BWA_MEM_00000088        0         33    6188   23942     17754
30                   SORT_BAM_00000090        0         33   23942   26637      2695
39                 MERGED_BAM_00000096        0         33   26637   36402      9765
40          MERGED_BAM_FILTER_00000087        0         33   36402   41451      5049
49                      MACS2_00000078        0         33   41451   43128      1677
55                     BIGWIG_00000089        0         33   43128   47810      4682
63            CONSENSUS_PEAKS_00000097        0         33   47810   49487      1677
64     CONSENSUS_PEAKS_COUNTS_00000076        0         33   49487   51164      1677
73             MACS2_ANNOTATE_00000084        0         33   51164   52841      1677
79       PHANTOMPEAKQUALTOOLS_00000077        0         33   52841   60678      7837
94                PLOTPROFILE_00000094        0         33   60678   70003      9325
101                    PRESEQ_00000082        0         33   70003   73866      3863
107                    FASTQC_00000067        0         33 1912870 1915111      2241
122            PICARD_METRICS_00000083        0         33 1915111 1916788      1677
159                   MULTIQC_00000091        0         33 1916795 1918471      1677
160                       IGV_00000086        0         33 1918471 1920148      1677
161  CONSENSUS_PEAKS_ANNOTATE_00000093        0         33 1920148 1921825      1677
8                CHECK_DESIGN_00000124        0         34       0    1677      1677
9                  TRIMGALORE_00000105        0         34    1677    6188      4511
18                    BWA_MEM_00000113        0         34    6188   23942     17754
31                   SORT_BAM_00000115        0         34   23942   26637      2695
41                 MERGED_BAM_00000121        0         34   26637   36402      9765
42          MERGED_BAM_FILTER_00000112        0         34   36402   41451      5049
50                      MACS2_00000103        0         34   41451   43128      1677
56                     BIGWIG_00000114        0         34   43128   47810      4682
65            CONSENSUS_PEAKS_00000122        0         34   47810   49487      1677
66     CONSENSUS_PEAKS_COUNTS_00000101        0         34   49487   51164      1677
74             MACS2_ANNOTATE_00000109        0         34   51164   52841      1677
80       PHANTOMPEAKQUALTOOLS_00000102        0         34   52841   60678      7837
95                PLOTPROFILE_00000119        0         34   60678   70003      9325
102                    PRESEQ_00000107        0         34   70003   73866      3863
108                    FASTQC_00000092        0         34 1912870 1915111      2241
123            PICARD_METRICS_00000108        0         34 1915111 1916788      1677
163                   MULTIQC_00000116        0         34 1916796 1918473      1677
164                       IGV_00000111        0         34 1918473 1920150      1677
165  CONSENSUS_PEAKS_ANNOTATE_00000118        0         34 1920150 1921827      1677
10               CHECK_DESIGN_00000149        0         35       0    1677      1677
11                 TRIMGALORE_00000130        0         35    1677    6188      4511
19                    BWA_MEM_00000138        0         35    6188   23942     17754
32                   SORT_BAM_00000140        0         35   23942   26637      2695
43                 MERGED_BAM_00000146        0         35   26637   36402      9765
44          MERGED_BAM_FILTER_00000137        0         35   36402   41451      5049
51                      MACS2_00000128        0         35   41451   43128      1677
57                     BIGWIG_00000139        0         35   43128   47810      4682
67            CONSENSUS_PEAKS_00000147        0         35   47810   49487      1677
68     CONSENSUS_PEAKS_COUNTS_00000126        0         35   49487   51164      1677
75             MACS2_ANNOTATE_00000134        0         35   51164   52841      1677
81       PHANTOMPEAKQUALTOOLS_00000127        0         35   52841   60678      7837
96                PLOTPROFILE_00000144        0         35   60678   70003      9325
103                    PRESEQ_00000132        0         35   70003   73866      3863
109                    FASTQC_00000117        0         35 1912870 1915111      2241
110                    FASTQC_00000142        0         35 1915111 1917352      2241
124            PICARD_METRICS_00000133        0         35 1917352 1919029      1677
167                   MULTIQC_00000141        0         35 1919031 1920708      1677
168                       IGV_00000136        0         35 1920708 1922385      1677
169  CONSENSUS_PEAKS_ANNOTATE_00000143        0         35 1922385 1924062      1677

In [21]:
sorted_dfstat = dfstat.sort_values(['processor', 'from', 'to'])
pd.options.display.float_format = '{:.0f}'.format
print(sorted_dfstat.to_string())

                              workflow  variant  processor    from      to  duration
35         MAKE_GENOME_FILTER_00000020        0          6       0     419       419
41         MAKE_GENOME_FILTER_00000156        0          6     419     838       419
143     get_software_versions_00000145        0          6     838    1258       419
174      output_documentation_00000173        0          6    1258    1677       419
36         MAKE_GENOME_FILTER_00000031        0          7       0     419       419
128     get_software_versions_00000019        0          7     419     838       419
146     get_software_versions_00000170        0          7     838    1258       419
171                   MULTIQC_00000166        0          7 2310684 2311103       419
37         MAKE_GENOME_FILTER_00000056        0          8       0     419       419
131     get_software_versions_00000045        0          8     419     838       419
150      output_documentation_00000025        0          8     838    1258       419
151                   MULTIQC_00000041        0          8 1915118 1915537       419
38         MAKE_GENOME_FILTER_00000081        0          9       0     419       419
134     get_software_versions_00000070        0          9     419     838       419
154      output_documentation_00000048        0          9     838    1258       419
39         MAKE_GENOME_FILTER_00000106        0         10       0     419       419
137     get_software_versions_00000095        0         10     419     838       419
158      output_documentation_00000073        0         10     838    1258       419
40         MAKE_GENOME_FILTER_00000131        0         11       0     419       419
140     get_software_versions_00000120        0         11     419     838       419
162      output_documentation_00000098        0         11     838    1258       419
111                    FASTQC_00000167        0         12 2307688 2310676      2988
50                      MACS2_00000028        0         18 1043529 1044647      1118
63            CONSENSUS_PEAKS_00000008        0         18 1334994 1336112      1118
78             MACS2_ANNOTATE_00000034        0         18 1336112 1337230      1118
126           PLOTFINGERPRINT_00000004        0         18 1423048 1424166      1118
149  CONSENSUS_PEAKS_ANNOTATE_00000024        0         18 1424166 1425284      1118
64            CONSENSUS_PEAKS_00000047        0         19 1132895 1134013      1118
70     CONSENSUS_PEAKS_COUNTS_00000007        0         19 1379005 1380123      1118
112    CONSENSUS_PEAKS_DESEQ2_00000018        0         19 1380123 1381241      1118
153  CONSENSUS_PEAKS_ANNOTATE_00000043        0         19 1381241 1382359      1118
71     CONSENSUS_PEAKS_COUNTS_00000026        0         20 1282363 1283481      1118
113    CONSENSUS_PEAKS_DESEQ2_00000029        0         20 1283481 1284599      1118
129                  MACS2_QC_00000035        0         20 1402355 1403473      1118
114    CONSENSUS_PEAKS_DESEQ2_00000054        0         21 1043539 1044657      1118
130           PLOTFINGERPRINT_00000050        0         21 1326407 1327525      1118
115    CONSENSUS_PEAKS_DESEQ2_00000079        0         22 1043539 1044657      1118
133           PLOTFINGERPRINT_00000075        0         22 1131594 1132712      1118
116    CONSENSUS_PEAKS_DESEQ2_00000104        0         23 1043539 1044657      1118
136           PLOTFINGERPRINT_00000100        0         23 1131594 1132712      1118
117    CONSENSUS_PEAKS_DESEQ2_00000129        0         24  139412  141089      1677
132                  MACS2_QC_00000060        0         24 1065556 1067233      1677
139           PLOTFINGERPRINT_00000125        0         24 1131594 1133271      1677
135                  MACS2_QC_00000085        0         25 1065556 1067233      1677
138                  MACS2_QC_00000110        0         26 1065556 1067233      1677
141                  MACS2_QC_00000135        0         27  161428  163105      1677
142           PLOTFINGERPRINT_00000150        0         27  227467  229144      1677
166      output_documentation_00000123        0         28       0    1677      1677
170      output_documentation_00000148        0         29       0    1677      1677
0                CHECK_DESIGN_00000001        0         30       0    1677      1677
6                CHECK_DESIGN_00000174        0         30    1677    3354      1677
7                  TRIMGALORE_00000002        0         30    3354    7865      4511
13                 TRIMGALORE_00000155        0         30    7865   12377      4511
14                    BWA_MEM_00000009        1         30   12377  614541    602164
20                    BWA_MEM_00000163        1         30  614541  715067    100526
21                   SORT_BAM_00000011        0         30  715067  717762      2695
27                   SORT_BAM_00000165        0         30  717762  720456      2695
28                 MERGED_BAM_00000012        1         30  720456  731192     10736
34                 MERGED_BAM_00000171        1         30  731192  819164     87971
42          MERGED_BAM_FILTER_00000005        2         30  956968  962017      5049
49                      MACS2_00000006        0         30  962017  963694      1677
56                     BIGWIG_00000021        0         30  963694  968376      4682
57                     BIGWIG_00000039        0         30 1389781 1394463      4682
77             MACS2_ANNOTATE_00000023        0         30 1394463 1396140      1677
84       PHANTOMPEAKQUALTOOLS_00000014        0         30 1396140 1403977      7837
91                PLOTPROFILE_00000016        0         30 1403977 1413302      9325
92                PLOTPROFILE_00000044        0         30 1413302 1422627      9325
98                     PRESEQ_00000013        0         30 1422627 1426490      3863
104                    PRESEQ_00000157        0         30 1426490 1430352      3863
105                    FASTQC_00000003        0         30 1430352 1432593      2241
119            PICARD_METRICS_00000015        0         30 1432593 1434270      1677
127                  MACS2_QC_00000017        0         30 1434270 1435947      1677
147                   MULTIQC_00000010        0         30 1435947 1437624      1677
148                       IGV_00000022        0         30 1437624 1439301      1677
152                       IGV_00000036        0         30 1439301 1440978      1677
1                CHECK_DESIGN_00000049        0         31       0    1677      1677
8                  TRIMGALORE_00000030        0         31    1677    6188      4511
15                    BWA_MEM_00000038        0         31    6188   23942     17754
22                   SORT_BAM_00000040        0         31   23942   26637      2695
29                 MERGED_BAM_00000046        0         31   26637   36402      9765
43          MERGED_BAM_FILTER_00000037        0         31   36402   41451      5049
48          MERGED_BAM_FILTER_00000162        2         31 1537705 1542755      5049
55                      MACS2_00000153        0         31 1542755 1544432      1677
62                     BIGWIG_00000164        0         31 1544432 1549114      4682
69            CONSENSUS_PEAKS_00000172        0         31 1549114 1550790      1677
76     CONSENSUS_PEAKS_COUNTS_00000151        0         31 1550790 1552467      1677
83             MACS2_ANNOTATE_00000159        0         31 1552467 1554144      1677
85       PHANTOMPEAKQUALTOOLS_00000027        0         31 1554144 1561982      7837
90       PHANTOMPEAKQUALTOOLS_00000152        0         31 1561982 1569819      7837
97                PLOTPROFILE_00000169        0         31 1569819 1579144      9325
99                     PRESEQ_00000032        0         31 1579144 1583007      3863
118    CONSENSUS_PEAKS_DESEQ2_00000154        0         31 1583007 1584684      1677
120            PICARD_METRICS_00000033        0         31 1584684 1586361      1677
125            PICARD_METRICS_00000158        0         31 1586361 1588038      1677
144                  MACS2_QC_00000160        0         31 1588038 1589715      1677
145           PLOTFINGERPRINT_00000175        0         31 1589715 1591392      1677
172                       IGV_00000161        0         31 1591392 1593068      1677
173  CONSENSUS_PEAKS_ANNOTATE_00000168        0         31 1593068 1594745      1677
2                CHECK_DESIGN_00000074        0         32       0    1677      1677
9                  TRIMGALORE_00000055        0         32    1677    6188      4511
16                    BWA_MEM_00000063        0         32    6188   23942     17754
23                   SORT_BAM_00000065        0         32   23942   26637      2695
30                 MERGED_BAM_00000071        0         32   26637   36402      9765
44          MERGED_BAM_FILTER_00000062        0         32   36402   41451      5049
51                      MACS2_00000053        0         32   41451   43128      1677
58                     BIGWIG_00000064        0         32   43128   47810      4682
65            CONSENSUS_PEAKS_00000072        0         32   47810   49487      1677
72     CONSENSUS_PEAKS_COUNTS_00000051        0         32   49487   51164      1677
79             MACS2_ANNOTATE_00000059        0         32   51164   52841      1677
86       PHANTOMPEAKQUALTOOLS_00000052        0         32   52841   60678      7837
93                PLOTPROFILE_00000069        0         32   60678   70003      9325
100                    PRESEQ_00000057        0         32   70003   73866      3863
106                    FASTQC_00000042        0         32 1912870 1915111      2241
121            PICARD_METRICS_00000058        0         32 1915111 1916788      1677
155                   MULTIQC_00000066        0         32 1916788 1918465      1677
156                       IGV_00000061        0         32 1918465 1920142      1677
157  CONSENSUS_PEAKS_ANNOTATE_00000068        0         32 1920142 1921819      1677
3                CHECK_DESIGN_00000099        0         33       0    1677      1677
10                 TRIMGALORE_00000080        0         33    1677    6188      4511
17                    BWA_MEM_00000088        0         33    6188   23942     17754
24                   SORT_BAM_00000090        0         33   23942   26637      2695
31                 MERGED_BAM_00000096        0         33   26637   36402      9765
45          MERGED_BAM_FILTER_00000087        0         33   36402   41451      5049
52                      MACS2_00000078        0         33   41451   43128      1677
59                     BIGWIG_00000089        0         33   43128   47810      4682
66            CONSENSUS_PEAKS_00000097        0         33   47810   49487      1677
73     CONSENSUS_PEAKS_COUNTS_00000076        0         33   49487   51164      1677
80             MACS2_ANNOTATE_00000084        0         33   51164   52841      1677
87       PHANTOMPEAKQUALTOOLS_00000077        0         33   52841   60678      7837
94                PLOTPROFILE_00000094        0         33   60678   70003      9325
101                    PRESEQ_00000082        0         33   70003   73866      3863
107                    FASTQC_00000067        0         33 1912870 1915111      2241
122            PICARD_METRICS_00000083        0         33 1915111 1916788      1677
159                   MULTIQC_00000091        0         33 1916788 1918465      1677
160                       IGV_00000086        0         33 1918465 1920142      1677
161  CONSENSUS_PEAKS_ANNOTATE_00000093        0         33 1920142 1921819      1677
4                CHECK_DESIGN_00000124        0         34       0    1677      1677
11                 TRIMGALORE_00000105        0         34    1677    6188      4511
18                    BWA_MEM_00000113        0         34    6188   23942     17754
25                   SORT_BAM_00000115        0         34   23942   26637      2695
32                 MERGED_BAM_00000121        0         34   26637   36402      9765
46          MERGED_BAM_FILTER_00000112        0         34   36402   41451      5049
53                      MACS2_00000103        0         34   41451   43128      1677
60                     BIGWIG_00000114        0         34   43128   47810      4682
67            CONSENSUS_PEAKS_00000122        0         34   47810   49487      1677
74     CONSENSUS_PEAKS_COUNTS_00000101        0         34   49487   51164      1677
81             MACS2_ANNOTATE_00000109        0         34   51164   52841      1677
88       PHANTOMPEAKQUALTOOLS_00000102        0         34   52841   60678      7837
95                PLOTPROFILE_00000119        0         34   60678   70003      9325
102                    PRESEQ_00000107        0         34   70003   73866      3863
108                    FASTQC_00000092        0         34 1912870 1915111      2241
123            PICARD_METRICS_00000108        0         34 1915111 1916788      1677
163                   MULTIQC_00000116        0         34 1916788 1918465      1677
164                       IGV_00000111        0         34 1918465 1920142      1677
165  CONSENSUS_PEAKS_ANNOTATE_00000118        0         34 1920142 1921819      1677
5                CHECK_DESIGN_00000149        0         35       0    1677      1677
12                 TRIMGALORE_00000130        0         35    1677    6188      4511
19                    BWA_MEM_00000138        0         35    6188   23942     17754
26                   SORT_BAM_00000140        0         35   23942   26637      2695
33                 MERGED_BAM_00000146        0         35   26637   36402      9765
47          MERGED_BAM_FILTER_00000137        0         35   36402   41451      5049
54                      MACS2_00000128        0         35   41451   43128      1677
61                     BIGWIG_00000139        0         35   43128   47810      4682
68            CONSENSUS_PEAKS_00000147        0         35   47810   49487      1677
75     CONSENSUS_PEAKS_COUNTS_00000126        0         35   49487   51164      1677
82             MACS2_ANNOTATE_00000134        0         35   51164   52841      1677
89       PHANTOMPEAKQUALTOOLS_00000127        0         35   52841   60678      7837
96                PLOTPROFILE_00000144        0         35   60678   70003      9325
103                    PRESEQ_00000132        0         35   70003   73866      3863
109                    FASTQC_00000117        0         35 1912870 1915111      2241
110                    FASTQC_00000142        0         35 1915111 1917352      2241
124            PICARD_METRICS_00000133        0         35 1917352 1919029      1677
167                   MULTIQC_00000141        0         35 1919029 1920706      1677
168                       IGV_00000136        0         35 1920706 1922383      1677
169  CONSENSUS_PEAKS_ANNOTATE_00000143        0         35 1922383 1924060      1677